using System.CommandLine;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using Slice.Cli.Internal;

namespace Slice.Cli.Commands;

internal static partial class GenerateTypeScriptClientCommand
{
    internal static Command Build()
    {
        var projectOpt = SharedOptions.CreateProject();
        var outputOpt = new Option<FileInfo?>("--output")
        {
            Description = "Output .ts file. Defaults to slice-api-client.ts in the target project directory.",
        };
        var classOpt = new Option<string>("--class")
        {
            Description = "Generated client class name.",
            DefaultValueFactory = _ => "SliceApiClient",
        };
        var forceOpt = SharedOptions.CreateForce();

        var cmd = new Command("typescript", "Generate a TypeScript fetch client for portable Slice routes.")
        {
            projectOpt,
            outputOpt,
            classOpt,
            forceOpt
        };

        cmd.SetAction(async (parseResult, ct) =>
        {
            var project = parseResult.GetValue(projectOpt);
            var output = parseResult.GetValue(outputOpt);
            var className = parseResult.GetValue(classOpt) ?? "SliceApiClient";
            var force = parseResult.GetValue(forceOpt);

            try
            {
                await RunAsync(project, output, className, force, ct).ConfigureAwait(false);
                return 0;
            }
            catch (CliException ex)
            {
                Console.Error.WriteLine(ex.Message);
                return 1;
            }
        });

        return cmd;
    }

    private static async Task RunAsync(
        FileInfo? project,
        FileInfo? output,
        string className,
        bool force,
        CancellationToken ct)
    {
        var ctx = ProjectContextDiscovery.Discover(project);
        className = CliValidation.RequireClassName(className, "Class");

        var discovery = RouteCatalog.DiscoverDetailed(ctx);
        RouteCatalog.WriteAggregatedRouteNotice(discovery);
        var routes = discovery.Routes
            .Where(static route => route.Portability != RouteCatalog.PortabilityAspNetOnly)
            .ToArray();

        if (routes.Length == 0)
        {
            throw new CliException("No portable or partial Slice routes found for TypeScript client generation.");
        }

        var outputFile = output?.FullName ?? Path.Combine(ctx.ProjectDirectory.FullName, ToKebabCase(className) + ".ts");
        if (File.Exists(outputFile) && !force)
        {
            throw new CliException($"Output file already exists: {outputFile}. Pass --force to overwrite it.");
        }

        var outputDir = Path.GetDirectoryName(outputFile);
        if (!string.IsNullOrEmpty(outputDir))
        {
            Directory.CreateDirectory(outputDir);
        }

        var assemblyFiles = BuildOutputAssemblyFinder.FindAssemblyFiles(ctx);
        var content = RenderClient(className, routes, assemblyFiles);
        await File.WriteAllTextAsync(outputFile, content, ct).ConfigureAwait(false);
        Console.WriteLine($"Generated {outputFile}");
    }

    private static string RenderClient(string className, SliceRouteInfo[] routes, FileInfo[] assemblyFiles)
    {
        var groups = routes
            .GroupBy(static route => route.Tag)
            .OrderBy(static g => g.Key, StringComparer.Ordinal)
            .ToArray();
        var groupNames = groups.ToDictionary(
            static g => g.Key,
            static g => ClientGenerationHelpers.ToPascalIdentifier(g.Key, "Default"),
            StringComparer.Ordinal);

        var typeSchemas = CollectTypeSchemas(routes, assemblyFiles);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();

        EmitInterfaces(sb, typeSchemas);

        sb.AppendLine(CultureInfo.InvariantCulture, $"export class {className} {{");
        sb.AppendLine("  constructor(");
        sb.AppendLine("    private readonly baseUrl: string,");
        sb.AppendLine("    private readonly init?: RequestInit");
        sb.AppendLine("  ) {}");
        sb.AppendLine();
        foreach (var group in groups)
        {
            var groupName = groupNames[group.Key];
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"  readonly {LowerFirst(groupName)}: {groupName}Client = new {groupName}Client(this.baseUrl, this.init);");
        }

        sb.AppendLine("}");
        sb.AppendLine();

        foreach (var group in groups)
        {
            EmitGroupClient(sb, groupNames[group.Key],
                group.OrderBy(static r => r.FeatureName, StringComparer.Ordinal), typeSchemas);
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void EmitInterfaces(StringBuilder sb, IReadOnlyDictionary<string, TypeSchema> typeSchemas)
    {
        foreach (var schema in typeSchemas.Values.OrderBy(static schema => schema.TsName, StringComparer.Ordinal))
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"export interface {schema.TsName} {{");
            foreach (var (propName, propType) in schema.Properties)
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"  readonly '{EscapeSingleQuotedText(propName)}': {propType};");
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }
    }

    private static void EmitGroupClient(
        StringBuilder sb,
        string groupName,
        IEnumerable<SliceRouteInfo> routes,
        IReadOnlyDictionary<string, TypeSchema> typeSchemas)
    {
        sb.AppendLine(CultureInfo.InvariantCulture, $"export class {groupName}Client {{");
        sb.AppendLine("  constructor(");
        sb.AppendLine("    private readonly baseUrl: string,");
        sb.AppendLine("    private readonly init?: RequestInit");
        sb.AppendLine("  ) {}");

        foreach (var route in routes)
        {
            sb.AppendLine();
            EmitRouteMethod(sb, route, typeSchemas);
        }

        sb.AppendLine("}");
    }

    private static void EmitRouteMethod(
        StringBuilder sb,
        SliceRouteInfo route,
        IReadOnlyDictionary<string, TypeSchema> typeSchemas)
    {
        var rawReturn = ClientGenerationHelpers.UnwrapReturnType(route.ReturnType);
        var returnTsType = DotNetTypeToTs(rawReturn, typeSchemas);
        var bodyParameter = ClientGenerationHelpers.FindBodyParameter(route);
        var routeParameters = ClientGenerationHelpers.FindRouteParameters(route);
        var queryParameters = ClientGenerationHelpers.FindQueryParameters(route, routeParameters, bodyParameter);
        var headerParameters = ClientGenerationHelpers.FindHeaderParameters(route);

        var methodParams = routeParameters
            .Select(static p => $"{LowerFirst(p.Name)}: {PrimitiveDotNetTypeToTs(p.Type)}")
            .ToList();
        foreach (var qp in queryParameters)
        {
            methodParams.Add($"{LowerFirst(qp.Name)}: {PrimitiveDotNetTypeToTs(qp.Type)}");
        }

        foreach (var hp in headerParameters)
        {
            methodParams.Add($"{LowerFirst(hp.Name)}: {PrimitiveDotNetTypeToTs(hp.Type)}");
        }

        if (bodyParameter is not null)
        {
            var bodyTsType = DotNetTypeToTs(bodyParameter.Type, typeSchemas);
            methodParams.Add($"body: {bodyTsType}");
        }

        methodParams.Add("signal?: AbortSignal");

        var returnPromise = returnTsType == "void" ? "Promise<void>" : $"Promise<{returnTsType}>";
        var methodName = LowerFirst(route.FeatureName);

        sb.AppendLine(CultureInfo.InvariantCulture,
            $"  async {methodName}Async({string.Join(", ", methodParams)}): {returnPromise} {{");

        var pathExpr = BuildPathExpression(route.Pattern, routeParameters);
        sb.AppendLine(CultureInfo.InvariantCulture, $"    let url = `${{this.baseUrl}}{pathExpr}`;");

        if (queryParameters.Length > 0)
        {
            sb.AppendLine("    const params = new URLSearchParams();");
            foreach (var qp in queryParameters)
            {
                var name = LowerFirst(qp.Name);
                if (qp.Type.TrimEnd('?').EndsWith("[]", StringComparison.Ordinal))
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"    if ({name} != null) for (const v of {name}) params.append('{EscapeSingleQuotedText(qp.WireName)}', String(v));");
                }
                else
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"    if ({name} != null) params.set('{EscapeSingleQuotedText(qp.WireName)}', String({name}));");
                }
            }

            sb.AppendLine("    const qs = params.toString();");
            sb.AppendLine("    if (qs) url += '?' + qs;");
        }

        if (headerParameters.Length > 0 || bodyParameter is not null)
        {
            sb.AppendLine("    const headers = new Headers(this.init?.headers);");
            foreach (var hp in headerParameters)
            {
                var name = LowerFirst(hp.Name);
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"    if ({name} != null) headers.set('{EscapeSingleQuotedText(hp.WireName)}', String({name}));");
            }
        }

        if (route.Method == "GET" && bodyParameter is null)
        {
            var headersInit = headerParameters.Length > 0 ? ", headers" : "";
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"    const response = await fetch(url, {{ ...this.init{headersInit}, signal: signal ?? this.init?.signal }});");
        }
        else if (bodyParameter is not null)
        {
            sb.AppendLine("    headers.set('Content-Type', 'application/json');");
            sb.AppendLine("    const response = await fetch(url, {");
            sb.AppendLine("      ...this.init,");
            sb.AppendLine(CultureInfo.InvariantCulture, $"      method: '{route.Method}',");
            sb.AppendLine("      headers,");
            sb.AppendLine("      body: JSON.stringify(body),");
            sb.AppendLine("      signal: signal ?? this.init?.signal");
            sb.AppendLine("    });");
        }
        else
        {
            var headersInit = headerParameters.Length > 0 ? ", headers" : "";
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"    const response = await fetch(url, {{ ...this.init, method: '{route.Method}'{headersInit}, signal: signal ?? this.init?.signal }});");
        }

        sb.AppendLine("    if (!response.ok) {");
        sb.AppendLine("      await response.body?.cancel();");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"      throw new Error(`{methodName}Async failed: ${{response.status}} ${{response.statusText}}`);");
        sb.AppendLine("    }");

        if (returnTsType != "void")
        {
            sb.AppendLine("    const text = await response.text();");
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"    if (text.length === 0) throw new Error(`{methodName}Async returned an empty response body.`);");
            sb.AppendLine(CultureInfo.InvariantCulture, $"    return JSON.parse(text) as {returnTsType};");
        }

        sb.AppendLine("  }");
    }

    private static string BuildPathExpression(string pattern, SliceRouteParameter[] routeParameters)
    {
        var paramMap = routeParameters.ToDictionary(
            static p => p.WireName,
            static p => LowerFirst(p.Name),
            StringComparer.OrdinalIgnoreCase);

        var sb = new StringBuilder();
        var index = 0;
        foreach (Match match in ClientGenerationHelpers.RouteParameterRegex().Matches(pattern))
        {
            sb.Append(EscapeTemplateLiteralText(pattern[index..match.Index]));
            var routeName = match.Groups["name"].Value;
            if (paramMap.TryGetValue(routeName, out var paramName))
            {
                sb.Append("${encodeURIComponent(String(");
                sb.Append(paramName);
                sb.Append("))}");
            }
            else
            {
                sb.Append(EscapeTemplateLiteralText("{" + routeName + "}"));
            }

            index = match.Index + match.Length;
        }

        sb.Append(EscapeTemplateLiteralText(pattern[index..]));
        return sb.ToString();
    }

    private static Dictionary<string, TypeSchema> CollectTypeSchemas(
        SliceRouteInfo[] routes,
        FileInfo[] assemblyFiles)
    {
        var result = new Dictionary<string, TypeSchema>(StringComparer.Ordinal);
        if (assemblyFiles.Length == 0)
        {
            return result;
        }

        var reader = TypeSchemaReader.Create(assemblyFiles);
        var discovered = new Dictionary<string, IReadOnlyList<TypeSchemaProperty>>(StringComparer.Ordinal);
        var pending = new Queue<string>(routes
            .SelectMany(static route => new[] { route.RequestType, ClientGenerationHelpers.UnwrapReturnType(route.ReturnType) })
            .Where(static t => t is not null and not "void")
            .Select(static t => t!)
            .SelectMany(ExtractSchemaTypeNames)
            .Distinct(StringComparer.Ordinal));

        while (pending.Count > 0)
        {
            var typeName = pending.Dequeue();
            if (discovered.ContainsKey(typeName) || IsKnownPrimitive(typeName))
            {
                continue;
            }

            var props = reader.ReadPublicPropertySchemas(typeName);
            if (props.Count == 0)
            {
                continue;
            }

            discovered.Add(typeName, props);
            foreach (var prop in props)
            {
                foreach (var nestedType in ExtractSchemaTypeNames(prop.Type))
                {
                    pending.Enqueue(nestedType);
                }
            }
        }

        var interfaceNames = CreateInterfaceNames(discovered.Keys);
        foreach (var (typeName, props) in discovered)
        {
            var tsProps = props
                .Select(p => (Name: p.JsonName, TsType: p.IsStringEnum ? AddNullable("string", p.IsNullable) : DotNetTypeToTs(p.Type, interfaceNames)))
                .ToArray();
            result[typeName] = new TypeSchema(typeName, interfaceNames[typeName], tsProps);
        }

        return result;
    }

    private static string DotNetTypeToTs(string dotNetType, IReadOnlyDictionary<string, TypeSchema> typeSchemas)
        => DotNetTypeToTs(dotNetType, typeSchemas.ToDictionary(
            static kv => kv.Key,
            static kv => kv.Value.TsName,
            StringComparer.Ordinal));

    private static string DotNetTypeToTs(string dotNetType, IReadOnlyDictionary<string, string> interfaceNames)
    {
        var isNullable = TryUnwrapNullable(dotNetType, out var nullableInner);
        var normalized = NormalizeTypeName(isNullable ? nullableInner : dotNetType);

        if (IsBinaryType(normalized))
        {
            return AddNullable("string", isNullable);
        }

        if (TryUnwrapDictionary(normalized, out _, out var valueType))
        {
            return AddNullable($"Record<string, {DotNetTypeToTs(valueType, interfaceNames)}>", isNullable);
        }

        if (TryUnwrapCollection(normalized, out var elementType))
        {
            return AddNullable(ToArrayType(DotNetTypeToTs(elementType, interfaceNames)), isNullable);
        }

        if (interfaceNames.TryGetValue(normalized, out var tsName))
        {
            return AddNullable(tsName, isNullable);
        }

        return AddNullable(PrimitiveDotNetTypeToTs(normalized), isNullable);
    }

    private static IEnumerable<string> ExtractSchemaTypeNames(string dotNetType)
    {
        if (TryUnwrapNullable(dotNetType, out var nullableInner))
        {
            dotNetType = nullableInner;
        }

        var normalized = NormalizeTypeName(dotNetType);
        if (TryUnwrapDictionary(normalized, out _, out var valueType))
        {
            foreach (var typeName in ExtractSchemaTypeNames(valueType))
            {
                yield return typeName;
            }

            yield break;
        }

        if (TryUnwrapCollection(normalized, out var elementType))
        {
            foreach (var typeName in ExtractSchemaTypeNames(elementType))
            {
                yield return typeName;
            }

            yield break;
        }

        if (!IsKnownPrimitive(normalized))
        {
            yield return normalized;
        }
    }

    private static string PrimitiveDotNetTypeToTs(string dotNetType)
    {
        var isNullable = TryUnwrapNullable(dotNetType, out var nullableInner);
        var normalized = NormalizeTypeName(isNullable ? nullableInner : dotNetType);

        if (IsBinaryType(normalized))
        {
            return AddNullable("string", isNullable);
        }

        if (normalized.EndsWith("[]", StringComparison.Ordinal))
        {
            var element = PrimitiveDotNetTypeToTs(normalized[..^2]);
            return AddNullable(ToArrayType(element), isNullable);
        }

        var tsBase = normalized switch
        {
            "string" or "String" or "System.String" or
            "Guid" or "System.Guid" or
            "DateTime" or "System.DateTime" or
            "DateTimeOffset" or "System.DateTimeOffset" or
            "DateOnly" or "System.DateOnly" or
            "TimeOnly" or "System.TimeOnly" or
            "TimeSpan" or "System.TimeSpan" or
            "char" or "Char" or "System.Char" => "string",

            "bool" or "Boolean" or "System.Boolean" => "boolean",

            "int" or "Int32" or "System.Int32" or
            "long" or "Int64" or "System.Int64" or
            "short" or "Int16" or "System.Int16" or
            "uint" or "UInt32" or "System.UInt32" or
            "ulong" or "UInt64" or "System.UInt64" or
            "ushort" or "UInt16" or "System.UInt16" or
            "float" or "Single" or "System.Single" or
            "double" or "Double" or "System.Double" or
            "decimal" or "Decimal" or "System.Decimal" or
            "byte" or "Byte" or "System.Byte" or
            "sbyte" or "SByte" or "System.SByte" => "number",

            _ => "unknown",
        };

        return AddNullable(tsBase, isNullable);
    }

    private static bool IsKnownPrimitive(string typeName)
    {
        var normalized = ClientGenerationHelpers.NormalizeParameterType(typeName);
        if (IsBinaryType(normalized))
        {
            return true;
        }

        return normalized switch
        {
            "string" or "String" or "System.String" or
            "bool" or "Boolean" or "System.Boolean" or
            "int" or "long" or "short" or "uint" or "ulong" or "ushort" or
            "float" or "double" or "decimal" or "byte" or "sbyte" or "char" or
            "System.Int32" or "System.Int64" or "System.Int16" or
            "System.UInt32" or "System.UInt64" or "System.UInt16" or
            "System.Single" or "System.Double" or "System.Decimal" or
            "System.Byte" or "System.SByte" or "System.Char" or
            "Guid" or "System.Guid" or
            "DateTime" or "System.DateTime" or
            "DateTimeOffset" or "System.DateTimeOffset" or
            "DateOnly" or "System.DateOnly" or
            "TimeOnly" or "System.TimeOnly" or
            "TimeSpan" or "System.TimeSpan" or
            "void" or "object" or "System.Object" => true,
            _ => false,
        };
    }

    private static bool IsBinaryType(string typeName)
    {
        var normalized = ClientGenerationHelpers.NormalizeParameterType(typeName);
        return normalized is "byte[]" or "Byte[]" or "System.Byte[]" or
            "Memory<byte>" or "System.Memory<byte>" or "ReadOnlyMemory<byte>" or "System.ReadOnlyMemory<byte>" or
            "Memory<System.Byte>" or "System.Memory<System.Byte>" or "ReadOnlyMemory<System.Byte>" or "System.ReadOnlyMemory<System.Byte>";
    }

    private static string TypeNameToTsInterfaceName(string qualifiedName)
    {
        var clean = qualifiedName
            .Replace("global::", "", StringComparison.Ordinal)
            .TrimEnd('?');

        var lastDot = clean.LastIndexOf('.');
        if (lastDot < 0)
        {
            return clean;
        }

        var local = clean[(lastDot + 1)..];
        var parent = clean[..lastDot];
        var parentLastDot = parent.LastIndexOf('.');
        var parentLocal = parentLastDot >= 0 ? parent[(parentLastDot + 1)..] : parent;

        return string.IsNullOrEmpty(parentLocal) ? local : parentLocal + local;
    }

    private static Dictionary<string, string> CreateInterfaceNames(IEnumerable<string> typeNames)
    {
        var used = new HashSet<string>(StringComparer.Ordinal);
        var result = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var typeName in typeNames.OrderBy(static typeName => typeName, StringComparer.Ordinal))
        {
            var name = CreateUniqueInterfaceName(typeName, used);
            used.Add(name);
            result.Add(typeName, name);
        }

        return result;
    }

    private static string CreateUniqueInterfaceName(string typeName, HashSet<string> used)
    {
        var segments = NormalizeTypeName(typeName)
            .Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

        for (var count = Math.Min(2, segments.Length); count <= segments.Length; count++)
        {
            var candidate = string.Concat(segments
                .Skip(segments.Length - count)
                .Select(static segment => ClientGenerationHelpers.ToPascalIdentifier(segment, "Type")));
            if (!used.Contains(candidate))
            {
                return candidate;
            }
        }

        var fallback = TypeNameToTsInterfaceName(typeName);
        var suffix = 2;
        while (used.Contains(fallback + suffix.ToString(CultureInfo.InvariantCulture)))
        {
            suffix++;
        }

        return fallback + suffix.ToString(CultureInfo.InvariantCulture);
    }

    private static string NormalizeTypeName(string typeName)
    {
        var normalized = RouteCatalog.NormalizeWhitespace(typeName);
        return normalized.StartsWith("global::", StringComparison.Ordinal)
            ? normalized["global::".Length..]
            : normalized;
    }

    private static bool TryUnwrapNullable(string typeName, out string inner)
    {
        var normalized = NormalizeTypeName(typeName);
        if (normalized.EndsWith('?'))
        {
            inner = normalized[..^1];
            return true;
        }

        return ClientGenerationHelpers.TryUnwrapGeneric(normalized, "System.Nullable", out inner) ||
               ClientGenerationHelpers.TryUnwrapGeneric(normalized, "Nullable", out inner);
    }

    private static bool TryUnwrapCollection(string typeName, out string elementType)
    {
        var normalized = NormalizeTypeName(typeName);
        if (normalized.EndsWith("[]", StringComparison.Ordinal))
        {
            elementType = normalized[..^2];
            return true;
        }

        foreach (var wrapper in new[]
        {
            "IEnumerable",
            "System.Collections.Generic.IEnumerable",
            "IReadOnlyCollection",
            "System.Collections.Generic.IReadOnlyCollection",
            "IReadOnlyList",
            "System.Collections.Generic.IReadOnlyList",
            "ICollection",
            "System.Collections.Generic.ICollection",
            "IList",
            "System.Collections.Generic.IList",
            "List",
            "System.Collections.Generic.List",
            "HashSet",
            "System.Collections.Generic.HashSet"
        })
        {
            if (ClientGenerationHelpers.TryUnwrapGeneric(normalized, wrapper, out elementType))
            {
                return true;
            }
        }

        elementType = "";
        return false;
    }

    private static bool TryUnwrapDictionary(string typeName, out string keyType, out string valueType)
    {
        var normalized = NormalizeTypeName(typeName);
        foreach (var wrapper in new[] { "Dictionary", "System.Collections.Generic.Dictionary", "IReadOnlyDictionary", "System.Collections.Generic.IReadOnlyDictionary" })
        {
            if (!ClientGenerationHelpers.TryUnwrapGeneric(normalized, wrapper, out var argsText))
            {
                continue;
            }

            var args = SplitGenericArguments(argsText);
            if (args.Length == 2)
            {
                keyType = args[0];
                valueType = args[1];
                return true;
            }
        }

        keyType = "";
        valueType = "";
        return false;
    }

    private static string[] SplitGenericArguments(string argsText)
    {
        var result = new List<string>();
        var depth = 0;
        var start = 0;
        for (var i = 0; i < argsText.Length; i++)
        {
            switch (argsText[i])
            {
                case '<':
                    depth++;
                    break;
                case '>':
                    depth--;
                    break;
                case ',' when depth == 0:
                    result.Add(argsText[start..i].Trim());
                    start = i + 1;
                    break;
                default:
                    break;
            }
        }

        result.Add(argsText[start..].Trim());
        return [.. result];
    }

    private static string AddNullable(string tsType, bool isNullable)
        => isNullable ? $"{tsType} | null" : tsType;

    private static string ToArrayType(string elementType)
        => elementType.Contains(" | ", StringComparison.Ordinal) ? $"({elementType})[]" : $"{elementType}[]";

    private static string EscapeTemplateLiteralText(string value)
        => value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("`", "\\`", StringComparison.Ordinal)
            .Replace("${", "\\${", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal);

    private static string EscapeSingleQuotedText(string value)
        => value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("'", "\\'", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal);

    private static string LowerFirst(string value)
        => value.Length == 0 ? value : char.ToLowerInvariant(value[0]) + value[1..];

    private static string ToKebabCase(string value)
    {
        var sb = new StringBuilder();
        foreach (var ch in value)
        {
            if (char.IsUpper(ch) && sb.Length > 0)
            {
                sb.Append('-');
            }

            sb.Append(char.ToLowerInvariant(ch));
        }

        return sb.ToString();
    }
}

internal sealed record TypeSchema(string DotNetTypeName, string TsName, IReadOnlyList<(string Name, string TsType)> Properties);
