using System.Collections.Immutable;
using System.Text;

namespace SliceFx.SourceGenerator;

/// <summary>
/// Emits NativeAOT-safe ASP.NET Core registration source for feature models when
/// <c>[assembly: SliceAspNetAot]</c> is present.
/// Replaces the <see cref="RegistrationEmitter"/> typed-delegate path (which flows through
/// <c>RequestDelegateFactory</c>) with hand-crafted <c>RequestDelegate</c> handlers that
/// perform all binding, validation, and response serialization without per-request reflection.
/// </summary>
internal static class AspNetAotRegistrationEmitter
{
    public static (string Source, ImmutableArray<EquatableDiagnostic> Diagnostics) Emit(
        ImmutableArray<FeatureModel> features,
        ImmutableArray<ValidatorModel> validators,
        string assemblyName,
        ImmutableArray<ReferencedSliceModule> referencedModules,
        bool emitExtensions,
        JsonContextPlan jsonContextPlan)
    {
        var className = GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceRegistrations");
        var sb = new StringBuilder();
        var diagnostics = ImmutableArray.CreateBuilder<EquatableDiagnostic>();

        var aspNetSerializableTypes = jsonContextPlan.GetSerializableTypesSet();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        if (!features.IsEmpty || !validators.IsEmpty)
        {
            sb.AppendLine();
            sb.AppendLine($"[assembly: global::SliceFx.SliceFeatureModuleAttribute(typeof(global::SliceFx.{className}))]");
        }

        sb.AppendLine();
        sb.AppendLine("namespace SliceFx;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides generated Slice NativeAOT-safe endpoint registration infrastructure.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        // Service and extension method structure is identical to the non-AOT emitter.
        EmitAddSliceServices(sb, features, validators);
        sb.AppendLine();
        EmitMapSliceRoutes(sb, features, aspNetSerializableTypes, jsonContextPlan, diagnostics);

        if (emitExtensions)
        {
            sb.AppendLine();
            EmitAddSlice(sb, className, referencedModules);
            sb.AppendLine();
            EmitMapSlices(sb, className, referencedModules);
        }

        // JsonTypeInfo helper (mirrors WasiRegistrationEmitter.__JsonTypeInfo<T>)
        var aspNetJsonContextFqn = jsonContextPlan.ContextFqn;
        if (aspNetJsonContextFqn is not null)
        {
            sb.AppendLine();
            EmitJsonTypeInfoHelper(sb, aspNetJsonContextFqn);
        }

        // AOT handler bodies
        foreach (var f in features)
        {
            var skipDiagnostic = GetAotSkipDiagnostic(f, aspNetSerializableTypes, jsonContextPlan);
            if (skipDiagnostic is not null)
            {
                continue; // error diagnostic already added in EmitMapSliceRoutes
            }

            sb.AppendLine();
            EmitAotHandler(sb, f, validators, aspNetSerializableTypes);
        }

        // SLICE073 diagnostics for IResult returns
        foreach (var f in features)
        {
            if (GetAotSkipDiagnostic(f, aspNetSerializableTypes, jsonContextPlan) is not null)
            {
                continue;
            }

            if (f.ReturnsAspNetResult)
            {
                diagnostics.Add(EquatableDiagnostic.Create(
                    SliceDiagnostics.IResultReturnForAspNetAot,
                    f.GetDiagnosticLocationModel(),
                    f.TypeName));
            }
        }

        EmitValidationHelpers(sb, features);
        sb.AppendLine("}");

        return (sb.ToString(), diagnostics.ToImmutable());
    }

    // --- Eligibility check ---

    private static EquatableDiagnostic? GetAotSkipDiagnostic(
        FeatureModel feature,
        HashSet<string>? serializableTypes,
        JsonContextPlan plan)
    {
        // WasiResponse is not applicable to the ASP.NET path
        if (SourceGenerationHelpers.IsWasiResponseType(
                SourceGenerationHelpers.GetAwaitedReturnType(feature.ReturnTypeFqn)))
        {
            return EquatableDiagnostic.Create(
                SliceDiagnostics.UnsupportedParameterForAspNetAot,
                feature.GetDiagnosticLocationModel(),
                feature.TypeName,
                "return",
                "SliceFx.Wasi.WasiResponse",
                "WasiResponse is a WASI-only type and cannot be used in ASP.NET NativeAOT dispatch");
        }

        // Reflection-dependent DataAnnotations → error (same as WASI/Lambda but error severity)
        if (feature.RequiresReflectionValidation)
        {
            return EquatableDiagnostic.Create(
                SliceDiagnostics.UnsupportedValidationForAspNetAot,
                feature.GetDiagnosticLocationModel(),
                feature.TypeName);
        }

        // Check for multiple body params or unsupported param shapes.
        // HttpContext/HttpRequest/HttpResponse/ClaimsPrincipal ARE allowed (direct pass-through).
        var selection = SourceGenerationHelpers.SelectBodyParameter(feature, serializableTypes);
        if (selection.AmbiguousWith is not null)
        {
            return EquatableDiagnostic.Create(
                SliceDiagnostics.UnsupportedParameterForAspNetAot,
                feature.GetDiagnosticLocationModel(),
                feature.TypeName,
                selection.AmbiguousWith.Name,
                SourceGenerationHelpers.TrimGlobalAlias(selection.AmbiguousWith.TypeFqn),
                "is a second request-body candidate; a handler binds at most one request body. Annotate the intended body with [FromBody], mark injected services with [FromServices] (or use an interface/abstract type), so only one candidate remains");
        }

        foreach (var p in feature.GetParams())
        {
            if (IsAspNetDirectParam(p.TypeFqn))
            {
                continue;
            }

            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                continue;
            }

            var binding = SourceGenerationHelpers.ResolveParameterBinding(
                p, feature.Pattern, selection.Body);

            if (binding.Source == HandlerParameterBindingSource.Unsupported)
            {
                return EquatableDiagnostic.Create(
                    SliceDiagnostics.UnsupportedParameterForAspNetAot,
                    feature.GetDiagnosticLocationModel(),
                    feature.TypeName,
                    p.Name,
                    SourceGenerationHelpers.TrimGlobalAlias(p.TypeFqn),
                    binding.UnsupportedReason ?? "parameter binding is unsupported");
            }
        }

        // JSON context exclusion (SLICE071) - checked via the plan
        if (JsonContextPlanner.FindExclusion(plan, feature) is not null)
        {
            return EquatableDiagnostic.Create(
                SliceDiagnostics.MissingAspNetAotJsonContext,
                feature.GetDiagnosticLocationModel(),
                feature.TypeName,
                JsonContextPlanner.FindExclusion(plan, feature)!.Value.Reason);
        }

        return null;
    }

    /// <summary>HttpContext/HttpRequest/HttpResponse/ClaimsPrincipal are direct pass-throughs.</summary>
    private static bool IsAspNetDirectParam(string typeFqn) => typeFqn switch
    {
        "global::Microsoft.AspNetCore.Http.HttpContext" => true,
        "global::Microsoft.AspNetCore.Http.HttpRequest" => true,
        "global::Microsoft.AspNetCore.Http.HttpResponse" => true,
        "global::System.Security.Claims.ClaimsPrincipal" => true,
        _ => false,
    };

    private static string? GetDirectParamExpr(string typeFqn) => typeFqn switch
    {
        "global::Microsoft.AspNetCore.Http.HttpContext" => "__ctx",
        "global::Microsoft.AspNetCore.Http.HttpRequest" => "__ctx.Request",
        "global::Microsoft.AspNetCore.Http.HttpResponse" => "__ctx.Response",
        "global::System.Security.Claims.ClaimsPrincipal" => "__ctx.User",
        _ => null,
    };

    // --- Service/extension method structure (mirrors RegistrationEmitter exactly) ---

    private static void EmitAddSliceServices(
        StringBuilder sb, ImmutableArray<FeatureModel> features, ImmutableArray<ValidatorModel> validators)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers services required by this generated Slice endpoint module.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to add Slice services to.</param>");
        sb.AppendLine("    /// <returns>The same service collection for chaining.</returns>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSliceServices(");
        sb.AppendLine("        global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var feature in features)
        {
            foreach (var ft in feature.GetFilterFqns())
            {
                if (seen.Add(ft))
                {
                    sb.AppendLine($"        services.AddScoped<{ft}>();");
                }
            }

            foreach (var ft in feature.GetSliceFilterFqns())
            {
                if (seen.Add(ft))
                {
                    sb.AppendLine($"        services.AddScoped<{ft}>();");
                }
            }
        }

        sb.AppendLine("        AddSliceValidatorServices(services);");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSliceValidatorServices(");
        sb.AppendLine("        global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var validator in validators)
        {
            sb.AppendLine($"        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::SliceFx.ISliceValidator<{validator.RequestTypeFqn}>, {validator.ImplementationTypeFqn}>(services);");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
    }

    private static void EmitMapSliceRoutes(
        StringBuilder sb,
        ImmutableArray<FeatureModel> features,
        HashSet<string>? serializableTypes,
        JsonContextPlan plan,
        ImmutableArray<EquatableDiagnostic>.Builder diagnostics)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps this generated Slice endpoint module to the route builder.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"app\">The endpoint route builder to map Slice endpoints onto.</param>");
        sb.AppendLine("    /// <returns>The same endpoint route builder for chaining.</returns>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapSliceRoutes(");
        sb.AppendLine("        global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)");
        sb.AppendLine("    {");

        foreach (var f in features)
        {
            var skipDiag = GetAotSkipDiagnostic(f, serializableTypes, plan);
            if (skipDiag is not null)
            {
                diagnostics.Add(skipDiag.Value);
                sb.AppendLine($"        // SLICE07x: {ToSingleLineComment(f.EndpointName)} — skipped; see diagnostic.");
                continue;
            }

            sb.AppendLine($"        // {ToSingleLineComment(f.EndpointName)}");
            var handlerName = AotHandlerMethodName(f);
            sb.AppendLine($"        app.MapMethods(");
            sb.AppendLine($"            {Str(f.Pattern)},");
            sb.AppendLine($"            new[] {{ {Str(f.HttpMethod)} }},");
            sb.AppendLine($"            new global::Microsoft.AspNetCore.Http.RequestDelegate({handlerName}))");
            sb.AppendLine($"        .WithTags({Str(f.Tag)})");
            sb.AppendLine($"        .WithName({Str(f.EndpointName)})");
            if (f.Summary is not null)
            {
                sb.AppendLine($"        .WithSummary({Str(f.Summary)});");
            }
            else
            {
                sb.AppendLine($"        ;");
            }

            sb.AppendLine();
        }

        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
    }

    private static void EmitAddSlice(
        StringBuilder sb, string className, ImmutableArray<ReferencedSliceModule> referencedModules)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers services required by generated Slice endpoint registrations.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to add Slice services to.</param>");
        sb.AppendLine("    /// <returns>The same service collection for chaining.</returns>");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSlice(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        global::SliceFx.{className}.AddSliceServices(services);");
        foreach (var module in referencedModules)
        {
            if (module.HasAspNetServices)
            {
                sb.AppendLine($"        {module.RegistrationTypeFqn}.AddSliceServices(services);");
            }
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
    }

    private static void EmitMapSlices(
        StringBuilder sb, string className, ImmutableArray<ReferencedSliceModule> referencedModules)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps generated Slice endpoints to the route builder.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"app\">The endpoint route builder to map Slice endpoints onto.</param>");
        sb.AppendLine("    /// <returns>The same endpoint route builder for chaining.</returns>");
        sb.AppendLine("    public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapSlices(");
        sb.AppendLine("        this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)");
        sb.AppendLine("    {");
        sb.AppendLine($"        global::SliceFx.{className}.MapSliceRoutes(app);");
        foreach (var module in referencedModules)
        {
            if (module.HasAspNetRoutes)
            {
                sb.AppendLine($"        {module.RegistrationTypeFqn}.MapSliceRoutes(app);");
            }
        }

        sb.AppendLine("        global::SliceFx.SliceMigrationAuditEndpointRouteBuilderExtensions.RunSliceMigrationAudit(app);");
        sb.AppendLine();
        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
    }

    private static void EmitJsonTypeInfoHelper(StringBuilder sb, string contextFqn)
    {
        sb.AppendLine("    private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T> __JsonTypeInfo<T>()");
        sb.AppendLine($"        => (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T>){contextFqn}.Default.GetTypeInfo(typeof(T))!;");
    }

    // --- AOT handler method emission ---

    private static void EmitAotHandler(
        StringBuilder sb,
        FeatureModel f,
        ImmutableArray<ValidatorModel> validators,
        HashSet<string>? serializableTypes)
    {
        var @params = f.GetParams();
        var bodyParam = FindBodyParam(f, serializableTypes);
        var bodyValidation = bodyParam is null ? null : FindValidationParameter(f, @params.IndexOf(bodyParam));
        var sliceFilters = f.GetSliceFilterFqns();
        var endpointFilters = f.GetFilterFqns();
        var hasSliceFilters = !sliceFilters.IsEmpty;

        sb.AppendLine($"    private static async global::System.Threading.Tasks.Task {AotHandlerMethodName(f)}(");
        sb.AppendLine("        global::Microsoft.AspNetCore.Http.HttpContext __ctx)");
        sb.AppendLine("    {");

        // Outer indent for handler body
        const string ind = "        ";

        if (hasSliceFilters)
        {
            // Resolve neutral filter instances
            for (var i = 0; i < sliceFilters.Length; i++)
            {
                sb.AppendLine($"{ind}var __sliceFilter{i} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{sliceFilters[i]}>(__ctx.RequestServices);");
            }

            // Build filter context
            sb.AppendLine($"{ind}var __sfCtx = global::SliceFx.SliceAotFilterContextBuilder.Create(__ctx);");
            sb.AppendLine();

            // Begin handler-core delegate
            sb.AppendLine($"{ind}global::SliceFx.SliceFilterDelegate __handlerCore = async __ =>");
            sb.AppendLine($"{ind}{{");
        }

        var innerInd = hasSliceFilters ? ind + "    " : ind;

        EmitHandlerCore(sb, f, validators, @params, bodyParam, bodyValidation,
            endpointFilters, innerInd);

        if (hasSliceFilters)
        {
            sb.AppendLine($"{ind}}};");
            sb.AppendLine();

            // Unroll filter chain (outermost first)
            if (sliceFilters.Length == 1)
            {
                sb.AppendLine($"{ind}var __sfResult = await __sliceFilter0.InvokeAsync(__sfCtx, __handlerCore).ConfigureAwait(false);");
            }
            else
            {
                sb.AppendLine($"{ind}global::SliceFx.SliceFilterDelegate __sfNext{sliceFilters.Length - 1} = __handlerCore;");
                for (var i = sliceFilters.Length - 2; i >= 1; i--)
                {
                    sb.AppendLine($"{ind}global::SliceFx.SliceFilterDelegate __sfNext{i} = __sffc{i} => __sliceFilter{i + 1}.InvokeAsync(__sffc{i}, __sfNext{i + 1});");
                }

                sb.AppendLine($"{ind}var __sfResult = await __sliceFilter0.InvokeAsync(__sfCtx, __sffc0 => __sliceFilter1.InvokeAsync(__sffc0, __sfNext1)).ConfigureAwait(false);");
            }

            sb.AppendLine($"{ind}if (__sfResult.IsShortCircuit)");
            sb.AppendLine($"{ind}{{");
            sb.AppendLine($"{ind}    await __sfResult.ShortCircuitResult!.Value.ExecuteAsync(__ctx);");
            sb.AppendLine($"{ind}}}");
        }

        sb.AppendLine("    }");
    }

    private static void EmitHandlerCore(
        StringBuilder sb,
        FeatureModel f,
        ImmutableArray<ValidatorModel> validators,
        ImmutableArray<HandleParamModel> @params,
        HandleParamModel? bodyParam,
        ValidationParameterModel? bodyValidation,
        ImmutableArray<string> endpointFilters,
        string ind)
    {
        var hasEndpointFilters = !endpointFilters.IsEmpty;
        // Early-exit returns inside a SliceFilterDelegate must return SliceFilterResult.PassThrough;
        // inside a plain async Task body they are bare 'return' statements.
        var inSliceFilterDelegate = IsSliceFilterHandlerCore(f);
        var nonNullableRouteParams = new HashSet<string>();

        // 1. Body binding
        if (bodyParam is not null)
        {
            var bodyReadName = bodyParam.IsValueType && !bodyParam.IsNullable
                ? "__" + bodyParam.Name + "Body"
                : bodyParam.Name;

            sb.AppendLine($"{ind}if (!global::Microsoft.AspNetCore.Http.HttpRequestJsonExtensions.HasJsonContentType(__ctx.Request))");
            sb.AppendLine($"{ind}{{");
            sb.AppendLine($"{ind}    __ctx.Response.StatusCode = 415;");
            sb.AppendLine($"{ind}    return{(inSliceFilterDelegate ? " global::SliceFx.SliceFilterResult.PassThrough(null, 415)" : string.Empty)};");
            sb.AppendLine($"{ind}}}");
            sb.AppendLine($"{ind}{bodyParam.TypeFqn}? {bodyReadName};");
            sb.AppendLine($"{ind}try");
            sb.AppendLine($"{ind}{{");
            sb.AppendLine($"{ind}    {bodyReadName} = await global::Microsoft.AspNetCore.Http.HttpRequestJsonExtensions.ReadFromJsonAsync<{bodyParam.TypeFqn}>(");
            sb.AppendLine($"{ind}        __ctx.Request, __JsonTypeInfo<{bodyParam.TypeFqn}>(), __ctx.RequestAborted);");
            sb.AppendLine($"{ind}}}");
            sb.AppendLine($"{ind}catch (global::System.Text.Json.JsonException)");
            sb.AppendLine($"{ind}{{");
            sb.AppendLine($"{ind}    await global::SliceFx.SliceAotResults.Problem(__ctx, 400, \"Bad Request\", \"Request body contains malformed JSON.\");");
            sb.AppendLine($"{ind}    return{(inSliceFilterDelegate ? " global::SliceFx.SliceFilterResult.PassThrough(null, 400)" : string.Empty)};");
            sb.AppendLine($"{ind}}}");
            sb.AppendLine($"{ind}if ({bodyReadName} is null)");
            sb.AppendLine($"{ind}{{");
            sb.AppendLine($"{ind}    await global::SliceFx.SliceAotResults.Problem(__ctx, 400, \"Bad Request\", \"Request body is required.\");");
            sb.AppendLine($"{ind}    return{(inSliceFilterDelegate ? " global::SliceFx.SliceFilterResult.PassThrough(null, 400)" : string.Empty)};");
            sb.AppendLine($"{ind}}}");
            if (bodyReadName != bodyParam.Name)
            {
                sb.AppendLine($"{ind}var {bodyParam.Name} = {bodyReadName}.Value;");
            }

            // DataAnnotations validation
            if (bodyValidation is not null)
            {
                sb.AppendLine($"{ind}var __daErrors = {ValidationMethodName(f, bodyValidation.Value)}({bodyParam.Name});");
                sb.AppendLine($"{ind}if (__daErrors is not null)");
                sb.AppendLine($"{ind}{{");
                sb.AppendLine($"{ind}    await global::SliceFx.SliceAotResults.ValidationProblem(__ctx, __daErrors);");
                sb.AppendLine($"{ind}    return{(inSliceFilterDelegate ? " global::SliceFx.SliceFilterResult.PassThrough(null, 400)" : string.Empty)};");
                sb.AppendLine($"{ind}}}");
            }

            // ISliceValidator
            if (HasValidatorForParameter(bodyParam, validators))
            {
                sb.AppendLine($"{ind}var __validator = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<global::SliceFx.ISliceValidator<{bodyParam.TypeFqn}>>(__ctx.RequestServices);");
                sb.AppendLine($"{ind}if (__validator is not null)");
                sb.AppendLine($"{ind}{{");
                sb.AppendLine($"{ind}    var __vr = await __validator.ValidateAsync({bodyParam.Name}, __ctx.RequestAborted);");
                sb.AppendLine($"{ind}    if (!__vr.IsValid)");
                sb.AppendLine($"{ind}    {{");
                sb.AppendLine($"{ind}        await global::SliceFx.SliceAotResults.ValidationProblem(__ctx, __vr.Errors!);");
                sb.AppendLine($"{ind}        return{(inSliceFilterDelegate ? " global::SliceFx.SliceFilterResult.PassThrough(null, 400)" : string.Empty)};");
                sb.AppendLine($"{ind}    }}");
                sb.AppendLine($"{ind}}}");
            }
        }

        // 2. Route / query / header / DI bindings
        foreach (var p in @params)
        {
            if (p == bodyParam)
            {
                continue;
            }

            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                continue;
            }

            if (IsAspNetDirectParam(p.TypeFqn))
            {
                continue;
            }

            var binding = SourceGenerationHelpers.ResolveParameterBinding(
                p, f.Pattern, bodyParam);

            if (binding.Source == HandlerParameterBindingSource.Route)
            {
                sb.AppendLine($"{ind}if (!global::SliceFx.SliceAotArgumentBinder");
                sb.AppendLine($"{ind}    .TryGetFromRoute<{p.TypeFqn}>(__ctx, {Str(binding.WireName)}, out var {p.Name}))");
                sb.AppendLine($"{ind}{{");
                sb.AppendLine($"{ind}    await global::SliceFx.SliceAotResults.Problem(__ctx, 400, \"Bad Request\", {Str($"Route value '{binding.WireName}' is missing or invalid.")});");
                sb.AppendLine($"{ind}    return{(inSliceFilterDelegate ? " global::SliceFx.SliceFilterResult.PassThrough(null, 400)" : string.Empty)};");
                sb.AppendLine($"{ind}}}");
                if (!p.IsNullable)
                {
                    nonNullableRouteParams.Add(p.Name);
                }
            }
            else if (binding.Source == HandlerParameterBindingSource.Query)
            {
                var bindVar = "__" + p.Name + "Query";
                sb.AppendLine($"{ind}var {bindVar} = global::SliceFx.SliceAotArgumentBinder");
                sb.AppendLine($"{ind}    .BindFromQuery<{p.TypeFqn}>(__ctx, {Str(binding.WireName)});");
                sb.AppendLine($"{ind}if ({bindVar}.Status == global::SliceFx.SliceAotArgumentBindingStatus.Invalid)");
                sb.AppendLine($"{ind}{{");
                sb.AppendLine($"{ind}    await global::SliceFx.SliceAotResults.Problem(__ctx, 400, \"Bad Request\", {Str($"Query value '{binding.WireName}' is invalid.")});");
                sb.AppendLine($"{ind}    return{(inSliceFilterDelegate ? " global::SliceFx.SliceFilterResult.PassThrough(null, 400)" : string.Empty)};");
                sb.AppendLine($"{ind}}}");
                if (!p.IsNullable)
                {
                    sb.AppendLine($"{ind}if ({bindVar}.Status == global::SliceFx.SliceAotArgumentBindingStatus.Missing)");
                    sb.AppendLine($"{ind}{{");
                    sb.AppendLine($"{ind}    await global::SliceFx.SliceAotResults.Problem(__ctx, 400, \"Bad Request\", {Str($"Query value '{binding.WireName}' is missing.")});");
                    sb.AppendLine($"{ind}    return{(inSliceFilterDelegate ? " global::SliceFx.SliceFilterResult.PassThrough(null, 400)" : string.Empty)};");
                    sb.AppendLine($"{ind}}}");
                }

                sb.AppendLine($"{ind}var {p.Name} = {bindVar}.Value!;");
            }
            else if (binding.Source == HandlerParameterBindingSource.Header)
            {
                var bindVar = "__" + p.Name + "Header";
                sb.AppendLine($"{ind}var {bindVar} = global::SliceFx.SliceAotArgumentBinder");
                sb.AppendLine($"{ind}    .BindFromHeader<{p.TypeFqn}>(__ctx, {Str(binding.WireName)});");
                sb.AppendLine($"{ind}if ({bindVar}.Status == global::SliceFx.SliceAotArgumentBindingStatus.Invalid)");
                sb.AppendLine($"{ind}{{");
                sb.AppendLine($"{ind}    await global::SliceFx.SliceAotResults.Problem(__ctx, 400, \"Bad Request\", {Str($"Header value '{binding.WireName}' is invalid.")});");
                sb.AppendLine($"{ind}    return{(inSliceFilterDelegate ? " global::SliceFx.SliceFilterResult.PassThrough(null, 400)" : string.Empty)};");
                sb.AppendLine($"{ind}}}");
                if (!p.IsNullable)
                {
                    sb.AppendLine($"{ind}if ({bindVar}.Status == global::SliceFx.SliceAotArgumentBindingStatus.Missing)");
                    sb.AppendLine($"{ind}{{");
                    sb.AppendLine($"{ind}    await global::SliceFx.SliceAotResults.Problem(__ctx, 400, \"Bad Request\", {Str($"Header value '{binding.WireName}' is missing.")});");
                    sb.AppendLine($"{ind}    return{(inSliceFilterDelegate ? " global::SliceFx.SliceFilterResult.PassThrough(null, 400)" : string.Empty)};");
                    sb.AppendLine($"{ind}}}");
                }

                sb.AppendLine($"{ind}var {p.Name} = {bindVar}.Value!;");
            }
            else if (binding.Source == HandlerParameterBindingSource.KeyedServices && binding.KeyLiteral is not null)
            {
                sb.AppendLine($"{ind}var {p.Name} = ({p.TypeFqn})global::Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService(__ctx.RequestServices, typeof({p.TypeFqn}), {binding.KeyLiteral});");
            }
            else // DI
            {
                sb.AppendLine($"{ind}var {p.Name} = ({p.TypeFqn})global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(__ctx.RequestServices, typeof({p.TypeFqn}));");
            }
        }

        // 3. Build call args
        var argList = new List<string>(@params.Length);
        foreach (var p in @params)
        {
            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                argList.Add("__ctx.RequestAborted");
            }
            else if (GetDirectParamExpr(p.TypeFqn) is { } directExpr)
            {
                argList.Add(directExpr);
            }
            else
            {
                argList.Add(nonNullableRouteParams.Contains(p.Name) ? p.Name + "!" : p.Name);
            }
        }

        var callArgs = string.Join(", ", argList);

        if (hasEndpointFilters)
        {
            // Build endpoint filter chain
            EmitEndpointFilterChain(sb, f, endpointFilters, @params,
                nonNullableRouteParams, ind);
        }
        else
        {
            // Direct Handle call + response
            EmitHandleCallAndResponse(sb, f, callArgs, ind);
            if (!IsSliceFilterHandlerCore(f))
            {
                // Non-ISliceFilter mode: just return
            }
            else
            {
                // Inside a SliceFilterDelegate, return PassThrough
                var responseStatus = GetDefaultResponseStatus(f);
                sb.AppendLine($"{ind}return global::SliceFx.SliceFilterResult.PassThrough(null, {responseStatus});");
            }
        }
    }

    private static bool IsSliceFilterHandlerCore(FeatureModel f)
        => !f.GetSliceFilterFqns().IsEmpty;

    private static int GetDefaultResponseStatus(FeatureModel f)
    {
        var awaitedReturn = SourceGenerationHelpers.GetAwaitedReturnType(f.ReturnTypeFqn);
        if (f.ReturnTypeFqn == "void" || SourceGenerationHelpers.IsNonGenericAwaitable(f.ReturnTypeFqn))
        {
            return 200;
        }

        if (SourceGenerationHelpers.IsSliceResultNonGenericType(awaitedReturn))
        {
            return 200; // actual status set inside
        }

        return 200;
    }

    private static void EmitHandleCallAndResponse(
        StringBuilder sb, FeatureModel f, string callArgs, string ind)
    {
        var awaitedReturn = SourceGenerationHelpers.GetAwaitedReturnType(f.ReturnTypeFqn);
        var isAwaitable = SourceGenerationHelpers.IsGenericAwaitable(f.ReturnTypeFqn)
            || SourceGenerationHelpers.IsNonGenericAwaitable(f.ReturnTypeFqn);
        var awaitPrefix = isAwaitable ? "await " : "";

        if (f.ReturnTypeFqn == "void" || SourceGenerationHelpers.IsNonGenericAwaitable(f.ReturnTypeFqn))
        {
            // void/Task/ValueTask → 200 empty body (RDF parity)
            sb.AppendLine($"{ind}{awaitPrefix}{f.FullyQualifiedTypeName}.Handle({callArgs});");
            sb.AppendLine($"{ind}__ctx.Response.StatusCode = 200;");
        }
        else if (f.ReturnsAspNetResult)
        {
            // IResult → execute directly
            sb.AppendLine($"{ind}var __result = {awaitPrefix}{f.FullyQualifiedTypeName}.Handle({callArgs});");
            sb.AppendLine($"{ind}if (__result is not null)");
            sb.AppendLine($"{ind}{{");
            sb.AppendLine($"{ind}    await __result.ExecuteAsync(__ctx);");
            sb.AppendLine($"{ind}}}");
        }
        else if (SourceGenerationHelpers.IsSliceResultNonGenericType(awaitedReturn))
        {
            sb.AppendLine($"{ind}var __result = {awaitPrefix}{f.FullyQualifiedTypeName}.Handle({callArgs});");
            sb.AppendLine($"{ind}await __result.ExecuteAsync(__ctx);");
        }
        else if (SourceGenerationHelpers.IsSliceResultOfTType(awaitedReturn))
        {
            var payloadType = SourceGenerationHelpers.GetSliceResultPayloadType(awaitedReturn!);
            sb.AppendLine($"{ind}var __result = {awaitPrefix}{f.FullyQualifiedTypeName}.Handle({callArgs});");
            sb.AppendLine($"{ind}await __result.ExecuteAsync(__ctx, __JsonTypeInfo<{payloadType}>());");
        }
        else
        {
            // POCO / string / other
            if (awaitedReturn is not null && IsStringType(awaitedReturn))
            {
                sb.AppendLine($"{ind}var __result = {awaitPrefix}{f.FullyQualifiedTypeName}.Handle({callArgs});");
                sb.AppendLine($"{ind}__ctx.Response.StatusCode = 200;");
                sb.AppendLine($"{ind}__ctx.Response.ContentType = \"text/plain; charset=utf-8\";");
                sb.AppendLine($"{ind}await __ctx.Response.WriteAsync(__result, __ctx.RequestAborted);");
            }
            else
            {
                sb.AppendLine($"{ind}var __result = {awaitPrefix}{f.FullyQualifiedTypeName}.Handle({callArgs});");
                sb.AppendLine($"{ind}__ctx.Response.StatusCode = 200;");
                sb.AppendLine($"{ind}await global::Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.WriteAsJsonAsync(");
                sb.AppendLine($"{ind}    __ctx.Response, __result, __JsonTypeInfo<{awaitedReturn ?? f.ReturnTypeFqn}>(), cancellationToken: __ctx.RequestAborted);");
            }
        }
    }

    private static void EmitEndpointFilterChain(
        StringBuilder sb,
        FeatureModel f,
        ImmutableArray<string> endpointFilters,
        ImmutableArray<HandleParamModel> @params,
        HashSet<string> nonNullableRouteParams,
        string ind)
    {
        // Build argument index map (endpoint filter args exclude CT and direct params)
        var efArgs = new List<(HandleParamModel Param, int Index)>();
        var idx = 0;
        foreach (var p in @params)
        {
            if (p.TypeFqn == "global::System.Threading.CancellationToken" || IsAspNetDirectParam(p.TypeFqn))
            {
                continue;
            }

            efArgs.Add((p, idx++));
        }

        // Build invocation context (bind before filter chain so filters can mutate args)
        var ctxArgs = string.Join(", ", efArgs.Select(a =>
            nonNullableRouteParams.Contains(a.Param.Name) ? a.Param.Name + "!" : a.Param.Name));
        sb.AppendLine($"{ind}var __efCtx = new global::Microsoft.AspNetCore.Http.DefaultEndpointFilterInvocationContext(");
        sb.AppendLine($"{ind}    __ctx{(ctxArgs.Length > 0 ? ", " + ctxArgs : string.Empty)});");
        sb.AppendLine();

        // Terminal: extracts (possibly mutated) args from invocation context, calls Handle, writes response
        sb.AppendLine($"{ind}global::Microsoft.AspNetCore.Http.EndpointFilterDelegate __efTerminal = async __efInvCtx =>");
        sb.AppendLine($"{ind}{{");
        // Re-extract args in case filters mutated them
        foreach (var (p, i) in efArgs)
        {
            sb.AppendLine($"{ind}    var {p.Name} = __efInvCtx.GetArgument<{p.TypeFqn}>({i})!;");
        }

        // Rebuild callArgs for terminal (they come from __efInvCtx now)
        var terminalArgs = new List<string>(@params.Length);
        foreach (var p in @params)
        {
            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                terminalArgs.Add("__ctx.RequestAborted");
            }
            else if (GetDirectParamExpr(p.TypeFqn) is { } directExpr)
            {
                terminalArgs.Add(directExpr);
            }
            else
            {
                terminalArgs.Add(p.Name);
            }
        }

        var terminalCallArgs = string.Join(", ", terminalArgs);
        EmitHandleCallAndResponse(sb, f, terminalCallArgs, ind + "    ");
        sb.AppendLine($"{ind}    return null;");
        sb.AppendLine($"{ind}}};");
        sb.AppendLine();

        // Resolve filter instances and build chain (innermost to outermost)
        for (var i = 0; i < endpointFilters.Length; i++)
        {
            sb.AppendLine($"{ind}var __efFilter{i} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{endpointFilters[i]}>(__ctx.RequestServices);");
        }

        if (endpointFilters.Length == 1)
        {
            sb.AppendLine($"{ind}global::Microsoft.AspNetCore.Http.EndpointFilterDelegate __efChain = async efCtx => await __efFilter0.InvokeAsync(efCtx, __efTerminal);");
        }
        else
        {
            sb.AppendLine($"{ind}global::Microsoft.AspNetCore.Http.EndpointFilterDelegate __efNext{endpointFilters.Length - 1} = __efTerminal;");
            for (var i = endpointFilters.Length - 2; i >= 1; i--)
            {
                sb.AppendLine($"{ind}global::Microsoft.AspNetCore.Http.EndpointFilterDelegate __efNext{i} = async efCtx => await __efFilter{i + 1}.InvokeAsync(efCtx, __efNext{i + 1});");
            }

            sb.AppendLine($"{ind}global::Microsoft.AspNetCore.Http.EndpointFilterDelegate __efChain = async efCtx => await __efFilter0.InvokeAsync(efCtx, __efNext1);");
        }

        sb.AppendLine($"{ind}await __efChain(__efCtx);");

        if (IsSliceFilterHandlerCore(f))
        {
            sb.AppendLine($"{ind}return global::SliceFx.SliceFilterResult.PassThrough(null, 200);");
        }
    }

    // --- Validation helpers (mirrors WasiRegistrationEmitter) ---

    private static void EmitValidationHelpers(
        StringBuilder sb, ImmutableArray<FeatureModel> features)
    {
        var emittedAny = false;
        foreach (var f in features)
        {
            if (f.RequiresReflectionValidation)
            {
                continue;
            }

            foreach (var parameter in f.GetValidationParameters())
            {
                if (!emittedAny)
                {
                    emittedAny = true;
                    sb.AppendLine();
                }

                EmitValidationMethod(sb, f, parameter);
                sb.AppendLine();
            }
        }

        if (!emittedAny)
        {
            return;
        }

        DataAnnotationsValidationEmitter.EmitValidationAttributeFields(
            sb,
            features.SelectMany(static feature => feature.GetValidationParameters()));
        sb.AppendLine("    private static void __AddValidationError(ref global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>? errors, string key, string message)");
        sb.AppendLine("    {");
        sb.AppendLine("        errors ??= new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>(global::System.StringComparer.Ordinal);");
        sb.AppendLine("        if (!errors.TryGetValue(key, out var messages))");
        sb.AppendLine("        {");
        sb.AppendLine("            messages = [];");
        sb.AppendLine("            errors.Add(key, messages);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        messages.Add(message);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? __ToValidationErrors(global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>? errors)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (errors is null || errors.Count == 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var result = new global::System.Collections.Generic.Dictionary<string, string[]>(global::System.StringComparer.Ordinal);");
        sb.AppendLine("        foreach (var entry in errors)");
        sb.AppendLine("        {");
        sb.AppendLine("            result.Add(entry.Key, entry.Value.ToArray());");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private static void EmitValidationMethod(StringBuilder sb, FeatureModel f, ValidationParameterModel parameter)
    {
        sb.AppendLine($"    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? {ValidationMethodName(f, parameter)}({parameter.TypeFqn} value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>? errors = null;");

        foreach (var line in parameter.SerializedRules.Split('\n'))
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }

            DataAnnotationsValidationEmitter.EmitValidationRule(sb, line);
        }

        sb.AppendLine();
        sb.AppendLine("        return __ToValidationErrors(errors);");
        sb.AppendLine("    }");
    }

    // --- Utility methods ---

    private static string AotHandlerMethodName(FeatureModel f)
        => "__AotHandle_" + SanitizeIdentifier(f.FullyQualifiedTypeName);

    private static string ValidationMethodName(FeatureModel f, ValidationParameterModel parameter)
        => "__Validate_" + SanitizeIdentifier(f.FullyQualifiedTypeName) + "_" + parameter.Index;

    private static string SanitizeIdentifier(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        return sb.ToString();
    }

    private static HandleParamModel? FindBodyParam(FeatureModel feature, HashSet<string>? serializableTypes)
        => SourceGenerationHelpers.FindSingleBodyParameter(feature, serializableTypes);

    private static ValidationParameterModel? FindValidationParameter(FeatureModel feature, int parameterIndex)
    {
        foreach (var parameter in feature.GetValidationParameters())
        {
            if (parameter.Index == parameterIndex)
            {
                return parameter;
            }
        }

        return null;
    }

    private static bool HasValidatorForParameter(HandleParamModel parameter, ImmutableArray<ValidatorModel> validators)
        => validators.Any(v => v.RequestTypeFqn == parameter.TypeFqn);

    private static bool IsStringType(string? typeFqn)
        => typeFqn is "global::System.String" or "string";

    private static string ToSingleLineComment(string value)
        => value.Replace('\r', ' ').Replace('\n', ' ');

    private static string Str(string value) => CSharpLiteral.String(value);
}
