using System.Collections.Immutable;
using System.Globalization;
using System.Text;

namespace SliceFx.SourceGenerator;

internal static class LambdaFunctionPerFeatureEmitter
{
    public static (string Source, ImmutableArray<EquatableDiagnostic> Diagnostics) Emit(
        ImmutableArray<FeatureModel> features,
        string assemblyName,
        ImmutableArray<ValidatorModel> validators,
        ImmutableArray<ReferencedSliceModule> referencedModules,
        JsonContextPlan jsonContextPlan)
    {
        var className = GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceLambdaFunctionPerFeatureHandlers");
        var sb = new StringBuilder();
        var diagnostics = ImmutableArray.CreateBuilder<EquatableDiagnostic>();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using global::Amazon.Lambda.APIGatewayEvents;");
        sb.AppendLine("using global::Amazon.Lambda.Core;");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using global::SliceFx.Lambda.FunctionPerFeature;");
        sb.AppendLine();
        sb.AppendLine($"[assembly: global::SliceFx.Lambda.FunctionPerFeature.LambdaFunctionPerFeatureModuleAttribute({CSharpLiteral.String("global::SliceFx." + className)})]");
        sb.AppendLine();
        sb.AppendLine("namespace SliceFx;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides generated Slice Lambda function-per-feature handlers.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        sb.AppendLine("}");

        // Build the serializable-type set once; used for body/service disambiguation in all per-feature loops.
        var lambdaSerializableTypes = jsonContextPlan.GetSerializableTypesSet();

        foreach (var feature in features)
        {
            EmitFeatureHandlerClass(sb, className, feature, validators, referencedModules, jsonContextPlan, diagnostics, lambdaSerializableTypes);
        }

        return (sb.ToString(), diagnostics.ToImmutable());
    }

    private static void EmitServiceProvider(
        StringBuilder sb,
        FeatureModel feature,
        HandleParamModel? bodyParam,
        ImmutableArray<ValidatorModel> validators,
        ImmutableArray<ReferencedSliceModule> referencedModules)
    {
        sb.AppendLine("    private static readonly global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.ServiceProvider> s_services = new(");
        sb.AppendLine("        static () => global::SliceFx.Lambda.FunctionPerFeature.LambdaServiceProvider.Build(static services =>");
        sb.AppendLine("        {");
        if (feature.LambdaStartupTypeFqn is not null)
        {
            sb.AppendLine($"            new {feature.LambdaStartupTypeFqn}().ConfigureServices(services);");
        }
        if (bodyParam is not null)
        {
            foreach (var validator in validators.Where(validator => validator.RequestTypeFqn == bodyParam.TypeFqn))
            {
                sb.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::SliceFx.ISliceValidator<{validator.RequestTypeFqn}>, {validator.ImplementationTypeFqn}>(services);");
            }
            foreach (var validator in referencedModules.SelectMany(static module => module.Validators).Where(validator => NormalizeTypeFqn(validator.RequestType) == bodyParam.TypeFqn))
            {
                sb.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::SliceFx.ISliceValidator<{NormalizeTypeFqn(validator.RequestType)}>, {NormalizeTypeFqn(validator.ValidatorType)}>(services);");
            }
        }
        sb.AppendLine("        }));");
    }

    private static void EmitFeatureHandlerClass(
        StringBuilder sb,
        string moduleClassName,
        FeatureModel feature,
        ImmutableArray<ValidatorModel> validators,
        ImmutableArray<ReferencedSliceModule> referencedModules,
        JsonContextPlan jsonContextPlan,
        ImmutableArray<EquatableDiagnostic>.Builder diagnostics,
        HashSet<string>? serializableTypes = null)
    {
        var skip = GetSkipReason(feature, serializableTypes);
        var jsonExclusion = JsonContextPlanner.FindExclusion(jsonContextPlan, feature);
        if (jsonExclusion is not null)
        {
            sb.AppendLine();
            sb.AppendLine($"// SLICE032: {ToSingleLineComment(feature.EndpointName)} — {jsonExclusion.Value.Reason}; skipped.");
            return;
        }

        if (skip is not null)
        {
            ReportSkipDiagnostic(feature, skip.Value, diagnostics);
            sb.AppendLine();
            sb.AppendLine($"// {skip.Value.DiagnosticId}: {ToSingleLineComment(feature.EndpointName)} — {skip.Value.Reason}; skipped.");
            return;
        }

        var @params = feature.GetParams();
        var bodyParam = FindBodyParam(feature, serializableTypes);
        var bodyValidation = bodyParam is null ? null : FindValidationParameter(feature, @params.IndexOf(bodyParam));
        var awaitedReturnType = SourceGenerationHelpers.GetAwaitedReturnType(feature.ReturnTypeFqn);

        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Provides the generated Slice Lambda function-per-feature handler for {CSharpXmlText(feature.EndpointName)}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public static class {HandlerTypeName(moduleClassName, feature)}");
        sb.AppendLine("{");
        EmitServiceProvider(sb, feature, bodyParam, validators, referencedModules);
        EmitJsonTypeInfoHelper(sb, feature);
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Handles {CSharpXmlText(feature.HttpMethod + " " + feature.Pattern)} for {CSharpXmlText(feature.EndpointName)}.</summary>");
        sb.AppendLine($"    public static async global::System.Threading.Tasks.Task<global::Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyResponse> {HandlerMethodName(feature)}(");
        sb.AppendLine("        global::Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyRequest lambdaRequest,");
        sb.AppendLine("        global::Amazon.Lambda.Core.ILambdaContext lambdaContext)");
        sb.AppendLine("    {");
        sb.AppendLine("        using var __timeout = global::SliceFx.Lambda.FunctionPerFeature.LambdaCancellation.Create(lambdaContext);");
        sb.AppendLine("        using var __scope = s_services.Value.CreateScope();");
        sb.AppendLine("        var ctx = new global::SliceFx.Lambda.FunctionPerFeature.LambdaInvocationContext(lambdaRequest, __scope.ServiceProvider, lambdaContext, __timeout.Token);");

        if (bodyParam is not null)
        {
            var bodyTargetName = bodyParam.Name;
            var bodyReadName = bodyParam.IsValueType && !bodyParam.IsNullable ? "__" + bodyParam.Name + "Body" : bodyParam.Name;
            sb.AppendLine($"        {bodyParam.TypeFqn}? {bodyReadName};");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine($"            {bodyReadName} = await global::SliceFx.Lambda.FunctionPerFeature.LambdaJsonBodyReader.ReadAsync<{bodyParam.TypeFqn}>(ctx, __JsonTypeInfo<{bodyParam.TypeFqn}>()).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine("        catch (global::System.Exception ex) when (ex is global::System.Text.Json.JsonException or global::System.FormatException)");
            sb.AppendLine("        {");
            sb.AppendLine("            return global::SliceFx.Lambda.FunctionPerFeature.LambdaResponseFactory.Problem(400, \"Bad Request\", \"Request body contains malformed JSON.\");");
            sb.AppendLine("        }");
            sb.AppendLine($"        if ({bodyReadName} is null) return global::SliceFx.Lambda.FunctionPerFeature.LambdaResponseFactory.Problem(400, \"Bad Request\", \"Request body is required.\");");
            if (bodyReadName != bodyTargetName)
            {
                sb.AppendLine($"        var {bodyTargetName} = {bodyReadName}.Value;");
            }

            if (bodyValidation is not null)
            {
                sb.AppendLine($"        var __daErrors = {ValidationMethodName(feature, bodyValidation.Value)}({bodyParam.Name});");
                sb.AppendLine("        if (__daErrors is not null) return global::SliceFx.Lambda.FunctionPerFeature.LambdaResponseFactory.ValidationProblem(__daErrors);");
            }

            if (HasValidatorForParameter(bodyParam, validators, referencedModules))
            {
                sb.AppendLine($"        var __validator = __scope.ServiceProvider.GetService<global::SliceFx.ISliceValidator<{bodyParam.TypeFqn}>>();");
                sb.AppendLine("        if (__validator is not null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            var __vr = await __validator.ValidateAsync({bodyParam.Name}, ctx.CancellationToken).ConfigureAwait(false);");
                sb.AppendLine("            if (!__vr.IsValid) return global::SliceFx.Lambda.FunctionPerFeature.LambdaResponseFactory.ValidationProblem(__vr.Errors!);");
                sb.AppendLine("        }");
            }
        }

        foreach (var p in @params)
        {
            if (p == bodyParam || p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                continue;
            }

            var binding = SourceGenerationHelpers.ResolveParameterBinding(
                p,
                feature.Pattern,
                bodyParam);
            if (binding.Source == HandlerParameterBindingSource.Route)
            {
                sb.AppendLine($"        if (!global::SliceFx.Lambda.FunctionPerFeature.LambdaArgumentBinder.TryGetFromRoute<{p.TypeFqn}>(ctx, {Str(binding.WireName)}, out var {p.Name}))");
                sb.AppendLine($"            return global::SliceFx.Lambda.FunctionPerFeature.LambdaResponseFactory.Problem(400, \"Bad Request\", {Str($"Route value '{binding.WireName}' is missing or invalid.")});");
            }
            else if (binding.Source == HandlerParameterBindingSource.Query)
            {
                var bindingVariable = "__" + p.Name + "Query";
                sb.AppendLine($"        var {bindingVariable} = global::SliceFx.Lambda.FunctionPerFeature.LambdaArgumentBinder.BindFromQuery<{p.TypeFqn}>(ctx, {Str(binding.WireName)});");
                sb.AppendLine($"        if ({bindingVariable}.Status == global::SliceFx.Lambda.FunctionPerFeature.LambdaArgumentBindingStatus.Invalid)");
                sb.AppendLine($"            return global::SliceFx.Lambda.FunctionPerFeature.LambdaResponseFactory.Problem(400, \"Bad Request\", {Str($"Query value '{binding.WireName}' is invalid.")});");
                if (!p.IsNullable)
                {
                    sb.AppendLine($"        if ({bindingVariable}.Status == global::SliceFx.Lambda.FunctionPerFeature.LambdaArgumentBindingStatus.Missing)");
                    sb.AppendLine($"            return global::SliceFx.Lambda.FunctionPerFeature.LambdaResponseFactory.Problem(400, \"Bad Request\", {Str($"Query value '{binding.WireName}' is missing.")});");
                }
                sb.AppendLine($"        var {p.Name} = {bindingVariable}.Value!;");
            }
            else if (binding.Source == HandlerParameterBindingSource.Header)
            {
                var bindingVariable = "__" + p.Name + "Header";
                sb.AppendLine($"        var {bindingVariable} = global::SliceFx.Lambda.FunctionPerFeature.LambdaArgumentBinder.BindFromHeader<{p.TypeFqn}>(ctx, {Str(binding.WireName)});");
                sb.AppendLine($"        if ({bindingVariable}.Status == global::SliceFx.Lambda.FunctionPerFeature.LambdaArgumentBindingStatus.Invalid)");
                sb.AppendLine($"            return global::SliceFx.Lambda.FunctionPerFeature.LambdaResponseFactory.Problem(400, \"Bad Request\", {Str($"Header value '{binding.WireName}' is invalid.")});");
                if (!p.IsNullable)
                {
                    sb.AppendLine($"        if ({bindingVariable}.Status == global::SliceFx.Lambda.FunctionPerFeature.LambdaArgumentBindingStatus.Missing)");
                    sb.AppendLine($"            return global::SliceFx.Lambda.FunctionPerFeature.LambdaResponseFactory.Problem(400, \"Bad Request\", {Str($"Header value '{binding.WireName}' is missing.")});");
                }
                sb.AppendLine($"        var {p.Name} = {bindingVariable}.Value!;");
            }
            else if (binding.Source == HandlerParameterBindingSource.KeyedServices && binding.KeyLiteral is not null)
            {
                sb.AppendLine($"        var {p.Name} = __scope.ServiceProvider.GetRequiredKeyedService<{p.TypeFqn}>({binding.KeyLiteral});");
            }
            else // DI (includes KeyedServices fallback when key literal could not be re-emitted)
            {
                sb.AppendLine($"        var {p.Name} = __scope.ServiceProvider.GetRequiredService<{p.TypeFqn}>();");
            }
        }

        var argList = BuildArgList(@params);
        var callExpr = $"{feature.FullyQualifiedTypeName}.Handle({string.Join(", ", argList)})";
        if (feature.ReturnTypeFqn == "void")
        {
            sb.AppendLine($"        {callExpr};");
            sb.AppendLine("        return global::SliceFx.Lambda.FunctionPerFeature.LambdaResponseFactory.NoContent();");
        }
        else if (SourceGenerationHelpers.IsNonGenericAwaitable(feature.ReturnTypeFqn))
        {
            sb.AppendLine($"        await {callExpr}.ConfigureAwait(false);");
            sb.AppendLine("        return global::SliceFx.Lambda.FunctionPerFeature.LambdaResponseFactory.NoContent();");
        }
        else
        {
            if (SourceGenerationHelpers.IsGenericAwaitable(feature.ReturnTypeFqn))
            {
                sb.AppendLine($"        var __result = await {callExpr}.ConfigureAwait(false);");
            }
            else
            {
                sb.AppendLine($"        var __result = {callExpr};");
            }

            if (SourceGenerationHelpers.IsLambdaProxyResponseType(awaitedReturnType))
            {
                sb.AppendLine("        return __result;");
            }
            else if (SourceGenerationHelpers.IsSliceResultNonGenericType(awaitedReturnType))
            {
                // Non-generic SliceResult — translate Kind/Status/Location/Body to Lambda response.
                sb.AppendLine("        return global::SliceFx.Lambda.FunctionPerFeature.SliceResultExtensions.ToLambdaResponse(__result);");
            }
            else if (SourceGenerationHelpers.IsSliceResultOfTType(awaitedReturnType))
            {
                // Generic SliceResult<T> — translate to Lambda response using the payload's JsonTypeInfo.
                // JSON root is T (not SliceResult<T>), matching what JsonContextPlanner registered.
                var payloadType = SourceGenerationHelpers.GetSliceResultPayloadType(awaitedReturnType!);
                sb.AppendLine($"        return global::SliceFx.Lambda.FunctionPerFeature.SliceResultExtensions.ToLambdaResponse<{payloadType}>(__result, __JsonTypeInfo<{payloadType}>());");
            }
            else
            {
                sb.AppendLine($"        return global::SliceFx.Lambda.FunctionPerFeature.LambdaResponseFactory.Ok<{awaitedReturnType}>(__result, __JsonTypeInfo<{awaitedReturnType}>());");
            }
        }

        sb.AppendLine("    }");
        EmitValidationHelpers(sb, feature);
        sb.AppendLine("}");
    }

    private static LambdaSkipReason? GetSkipReason(
        FeatureModel feature,
        HashSet<string>? serializableTypes = null)
    {
        if (feature.ReturnsAspNetResult)
        {
            return new LambdaSkipReason("SLICE030", "returns ASP.NET IResult");
        }

        if (SourceGenerationHelpers.IsWasiResponseType(SourceGenerationHelpers.GetAwaitedReturnType(feature.ReturnTypeFqn)))
        {
            return new LambdaSkipReason("SLICE030", "returns SliceFx.Wasi.WasiResponse");
        }

        if (!feature.GetFilterFqns().IsEmpty)
        {
            return new LambdaSkipReason("SLICE031", "endpoint filters require the ASP.NET endpoint filter pipeline");
        }

        if (feature.RequiresReflectionValidation)
        {
            return new LambdaSkipReason("SLICE034", "DataAnnotations validation requires reflection in the Lambda function-per-feature path");
        }

        var selection = SourceGenerationHelpers.SelectBodyParameter(feature, serializableTypes);
        if (selection.AmbiguousWith is not null)
        {
            return new LambdaSkipReason(
                "SLICE033",
                "multiple body parameters are not supported",
                selection.AmbiguousWith.Name,
                SourceGenerationHelpers.TrimGlobalAlias(selection.AmbiguousWith.TypeFqn));
        }

        foreach (var p in feature.GetParams())
        {
            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                continue;
            }

            var binding = SourceGenerationHelpers.ResolveParameterBinding(
                p,
                feature.Pattern,
                selection.Body);

            if (binding.Source == HandlerParameterBindingSource.Unsupported)
            {
                return new LambdaSkipReason(
                    "SLICE033",
                    binding.UnsupportedReason ?? "parameter binding is unsupported",
                    p.Name,
                    SourceGenerationHelpers.TrimGlobalAlias(p.TypeFqn));
            }
        }

        return null;
    }

    private static void ReportSkipDiagnostic(
        FeatureModel feature,
        LambdaSkipReason skip,
        ImmutableArray<EquatableDiagnostic>.Builder diagnostics)
    {
        var descriptor = skip.DiagnosticId switch
        {
            "SLICE030" => SliceDiagnostics.UnsupportedReturnTypeForLambdaFunctionPerFeature,
            "SLICE031" => SliceDiagnostics.UnsupportedFilterForLambdaFunctionPerFeature,
            "SLICE033" => SliceDiagnostics.UnsupportedParameterForLambdaFunctionPerFeature,
            "SLICE034" => SliceDiagnostics.UnsupportedValidationForLambdaFunctionPerFeature,
            _ => SliceDiagnostics.UnsupportedReturnTypeForLambdaFunctionPerFeature,
        };

        var diagnostic = skip.DiagnosticId switch
        {
            "SLICE030" => EquatableDiagnostic.Create(descriptor, feature.GetDiagnosticLocationModel(), feature.TypeName, feature.ReturnTypeFqn),
            "SLICE033" => EquatableDiagnostic.Create(descriptor, feature.GetDiagnosticLocationModel(), feature.TypeName, skip.ParameterName ?? "", skip.ParameterType ?? ""),
            _ => EquatableDiagnostic.Create(descriptor, feature.GetDiagnosticLocationModel(), feature.TypeName),
        };
        diagnostics.Add(diagnostic);
    }

    internal static string HandlerMethodName(FeatureModel feature)
        => GeneratedIdentifier.Sanitize(feature.EndpointName) + "_" + StableIdentifierSuffix(feature.FullyQualifiedTypeName);

    internal static string HandlerTypeName(string moduleClassName, FeatureModel feature)
        => moduleClassName + "_" + GeneratedIdentifier.Sanitize(feature.EndpointName) + "_" + StableIdentifierSuffix(feature.FullyQualifiedTypeName);

    private static List<string> BuildArgList(ImmutableArray<HandleParamModel> parameters)
    {
        var args = new List<string>(parameters.Length);
        foreach (var p in parameters)
        {
            args.Add(p.TypeFqn == "global::System.Threading.CancellationToken" ? "ctx.CancellationToken" : p.Name);
        }

        return args;
    }

    private static void EmitValidationHelpers(StringBuilder sb, FeatureModel feature)
    {
        var emittedAny = false;
        if (feature.RequiresReflectionValidation)
        {
            return;
        }

        foreach (var parameter in feature.GetValidationParameters())
        {
            if (!emittedAny)
            {
                emittedAny = true;
                sb.AppendLine();
            }

            EmitValidationMethod(sb, feature, parameter);
            sb.AppendLine();
        }

        if (!emittedAny)
        {
            return;
        }

        DataAnnotationsValidationEmitter.EmitValidationAttributeFields(sb, feature.GetValidationParameters());
        sb.AppendLine("    private static void __AddValidationError(ref global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>? errors, string key, string message)");
        sb.AppendLine("    {");
        sb.AppendLine("        errors ??= new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>(global::System.StringComparer.Ordinal);");
        sb.AppendLine("        if (!errors.TryGetValue(key, out var messages))");
        sb.AppendLine("        {");
        sb.AppendLine("            messages = [];");
        sb.AppendLine("            errors.Add(key, messages);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        messages.Add(message);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? __ToValidationErrors(global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>? errors)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (errors is null || errors.Count == 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var result = new global::System.Collections.Generic.Dictionary<string, string[]>(global::System.StringComparer.Ordinal);");
        sb.AppendLine("        foreach (var entry in errors)");
        sb.AppendLine("        {");
        sb.AppendLine("            result.Add(entry.Key, entry.Value.ToArray());");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private static void EmitValidationMethod(StringBuilder sb, FeatureModel feature, ValidationParameterModel parameter)
    {
        sb.AppendLine($"    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? {ValidationMethodName(feature, parameter)}({parameter.TypeFqn} value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>? errors = null;");

        foreach (var line in parameter.SerializedRules.Split('\n'))
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }

            DataAnnotationsValidationEmitter.EmitValidationRule(sb, line);
        }

        sb.AppendLine();
        sb.AppendLine("        return __ToValidationErrors(errors);");
        sb.AppendLine("    }");
    }

    private static string ValidationMethodName(FeatureModel feature, ValidationParameterModel parameter)
        => "__Validate_" + SanitizeIdentifier(feature.FullyQualifiedTypeName) + "_" + parameter.Index;

    private static void EmitJsonTypeInfoHelper(StringBuilder sb, FeatureModel feature)
    {
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Provides route-local JSON metadata for this generated handler.</summary>");
        sb.AppendLine("    public static global::System.Func<global::System.Type, global::System.Text.Json.Serialization.Metadata.JsonTypeInfo?> JsonTypeInfoProvider { get; set; } =");
        sb.AppendLine($"        static type => throw new global::System.InvalidOperationException({Str($"Lambda function-per-feature JSON metadata provider was not configured for {feature.EndpointName}. Use slicefx package aws-lambda to generate the route-local NativeAOT wrapper.")});");
        sb.AppendLine();
        sb.AppendLine("    private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T> __JsonTypeInfo<T>()");
        sb.AppendLine("        => (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T>)(JsonTypeInfoProvider(typeof(T))");
        sb.AppendLine($"            ?? throw new global::System.InvalidOperationException({Str($"Lambda function-per-feature JSON metadata provider did not contain required metadata for {feature.EndpointName}.")}));");
    }

    private static HandleParamModel? FindBodyParam(
        FeatureModel feature,
        HashSet<string>? serializableTypes = null)
        => SourceGenerationHelpers.FindSingleBodyParameter(feature, serializableTypes);

    private static ValidationParameterModel? FindValidationParameter(FeatureModel feature, int parameterIndex)
    {
        foreach (var parameter in feature.GetValidationParameters())
        {
            if (parameter.Index == parameterIndex)
            {
                return parameter;
            }
        }

        return null;
    }

    private static bool HasValidatorForParameter(
        HandleParamModel parameter,
        ImmutableArray<ValidatorModel> validators,
        ImmutableArray<ReferencedSliceModule> referencedModules)
        => validators.Any(validator => validator.RequestTypeFqn == parameter.TypeFqn)
           || referencedModules
               .SelectMany(static module => module.Validators)
               .Any(validator => NormalizeTypeFqn(validator.RequestType) == parameter.TypeFqn);

    private static string NormalizeTypeFqn(string typeName)
        => typeName.StartsWith("global::", StringComparison.Ordinal) ? typeName : "global::" + typeName;

    private static string StableIdentifierSuffix(string value)
    {
        unchecked
        {
            var hash = 2166136261u;
            foreach (var ch in value)
            {
                hash ^= ch;
                hash *= 16777619u;
            }

            return hash.ToString("x8", CultureInfo.InvariantCulture);
        }
    }

    private static string SanitizeIdentifier(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        return sb.ToString();
    }

    private static string Str(string value) => CSharpLiteral.String(value);

    private static string ToSingleLineComment(string value)
        => value.Replace('\r', ' ').Replace('\n', ' ');

    private static string CSharpXmlText(string value)
        => value.Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");

    private readonly record struct LambdaSkipReason(
        string DiagnosticId,
        string Reason,
        string? ParameterName = null,
        string? ParameterType = null);
}
