using System.Collections.Immutable;
using System.Text;

namespace SliceFx.SourceGenerator;

internal static class RegistrationEmitter
{
    /// <summary>
    /// Emits ASP.NET Core Slice registration source for the specified feature models.
    /// </summary>
    /// <param name="features">The feature models to include in generated registrations.</param>
    /// <param name="validators">The validator models to include in generated service registrations.</param>
    /// <param name="assemblyName">The target assembly name used to form the generated class name.</param>
    /// <param name="referencedModules">The referenced Slice modules to aggregate from user-facing extension methods.</param>
    /// <param name="emitExtensions">Whether to emit user-facing extension methods for this compilation.</param>
    /// <returns>The generated C# source.</returns>
    public static string Emit(
        ImmutableArray<FeatureModel> features,
        ImmutableArray<ValidatorModel> validators,
        string assemblyName,
        ImmutableArray<ReferencedSliceModule> referencedModules,
        bool emitExtensions)
    {
        var className = GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceRegistrations");
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        if (!features.IsEmpty || !validators.IsEmpty)
        {
            sb.AppendLine();
            sb.AppendLine($"[assembly: global::SliceFx.SliceFeatureModuleAttribute(typeof(global::SliceFx.{className}))]");
        }

        sb.AppendLine();
        sb.AppendLine("namespace SliceFx;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides generated Slice endpoint registration infrastructure.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        EmitAddSliceServices(sb, features, validators);
        sb.AppendLine();
        EmitMapSliceRoutes(sb, features, validators);
        if (emitExtensions)
        {
            sb.AppendLine();
            EmitAddSlice(sb, className, referencedModules);
            sb.AppendLine();
            EmitMapSlices(sb, className, referencedModules);
        }

        EmitDataAnnotationsValidationHelpers(sb, features);
        EmitSliceValidatorHelpers(sb, features, validators);
        EmitValidationProblemErrorHelper(sb, features, validators);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitAddSliceServices(
        StringBuilder sb,
        ImmutableArray<FeatureModel> features,
        ImmutableArray<ValidatorModel> validators)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers services required by this generated Slice endpoint module.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to add Slice services to.</param>");
        sb.AppendLine("    /// <returns>The same service collection for chaining.</returns>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSliceServices(");
        sb.AppendLine("        global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        var seen = new HashSet<string>(StringComparer.Ordinal);

        foreach (var feature in features)
        {
            foreach (var ft in feature.GetFilterFqns())
            {
                if (seen.Add(ft))
                {
                    sb.AppendLine($"        services.AddScoped<{ft}>();");
                }
            }
        }

        sb.AppendLine("        AddSliceValidatorServices(services);");

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();
        EmitAddSliceValidatorServices(sb, validators);
    }

    private static void EmitAddSliceValidatorServices(StringBuilder sb, ImmutableArray<ValidatorModel> validators)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers validators required by this generated Slice endpoint module.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to add Slice validators to.</param>");
        sb.AppendLine("    /// <returns>The same service collection for chaining.</returns>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSliceValidatorServices(");
        sb.AppendLine("        global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var validator in validators)
        {
            sb.AppendLine($"        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::SliceFx.ISliceValidator<{validator.RequestTypeFqn}>, {validator.ImplementationTypeFqn}>(services);");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
    }

    private static void EmitMapSliceRoutes(
        StringBuilder sb,
        ImmutableArray<FeatureModel> features,
        ImmutableArray<ValidatorModel> validators)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps this generated Slice endpoint module to the route builder.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"app\">The endpoint route builder to map Slice endpoints onto.</param>");
        sb.AppendLine("    /// <returns>The same endpoint route builder for chaining.</returns>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapSliceRoutes(");
        sb.AppendLine("        global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)");
        sb.AppendLine("    {");

        foreach (var f in features)
        {
            sb.AppendLine($"        // {ToSingleLineComment(f.EndpointName)}");
            EmitFeatureRegistration(sb, f, validators);
            sb.AppendLine();
        }

        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
    }

    private static void EmitAddSlice(
        StringBuilder sb,
        string className,
        ImmutableArray<ReferencedSliceModule> referencedModules)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers services required by generated Slice endpoint registrations.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to add Slice services to.</param>");
        sb.AppendLine("    /// <returns>The same service collection for chaining.</returns>");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSlice(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        global::SliceFx.{className}.AddSliceServices(services);");
        foreach (var module in referencedModules)
        {
            if (module.HasAspNetServices)
            {
                sb.AppendLine($"        {module.RegistrationTypeFqn}.AddSliceServices(services);");
            }
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
    }

    private static void EmitMapSlices(
        StringBuilder sb,
        string className,
        ImmutableArray<ReferencedSliceModule> referencedModules)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps generated Slice endpoints to the route builder.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"app\">The endpoint route builder to map Slice endpoints onto.</param>");
        sb.AppendLine("    /// <returns>The same endpoint route builder for chaining.</returns>");
        sb.AppendLine("    public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapSlices(");
        sb.AppendLine("        this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)");
        sb.AppendLine("    {");
        sb.AppendLine($"        global::SliceFx.{className}.MapSliceRoutes(app);");
        foreach (var module in referencedModules)
        {
            if (module.HasAspNetRoutes)
            {
                sb.AppendLine($"        {module.RegistrationTypeFqn}.MapSliceRoutes(app);");
            }
        }

        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
    }

    private static void EmitFeatureRegistration(
        StringBuilder sb,
        FeatureModel f,
        ImmutableArray<ValidatorModel> validators)
    {
        var paramModels = f.GetParams();
        var filterFqns = f.GetFilterFqns();

        var delegateType = BuildDelegateType(paramModels, f.ReturnTypeFqn);

        sb.AppendLine($"        app.MapMethods(");
        sb.AppendLine($"            {CSharpLiteral.String(f.Pattern)},");
        sb.AppendLine($"            new[] {{ {CSharpLiteral.String(f.HttpMethod)} }},");
        sb.AppendLine($"            new {delegateType}(");
        sb.AppendLine($"                {f.FullyQualifiedTypeName}.Handle))");
        if (HasGeneratedDataAnnotationsValidation(f))
        {
            sb.AppendLine($"        .AddEndpointFilterFactory(");
            sb.AppendLine($"            {GeneratedDataAnnotationsFactoryName(f)})");
        }

        if (HasSliceValidatorCandidates(paramModels, validators))
        {
            sb.AppendLine($"        .AddEndpointFilterFactory(");
            sb.AppendLine($"            {GeneratedValidatorFactoryName(f)})");
        }

        foreach (var ft in filterFqns)
        {
            sb.AppendLine($"        .AddEndpointFilter<{ft}>()");
        }

        sb.AppendLine($"        .WithTags({CSharpLiteral.String(f.Tag)})");
        sb.AppendLine($"        .WithName({CSharpLiteral.String(f.EndpointName)})");

        if (f.Summary is not null)
        {
            sb.AppendLine($"        .WithSummary({CSharpLiteral.String(f.Summary)});");
        }
        else
        {
            sb.AppendLine($"        ;");
        }
    }

    private static bool HasSliceValidatorCandidates(
        ImmutableArray<HandleParamModel> parameters,
        ImmutableArray<ValidatorModel> validators)
        => parameters.Any(parameter => HasValidatorForParameter(parameter, validators));

    private static bool HasValidatorForParameter(
        HandleParamModel parameter,
        ImmutableArray<ValidatorModel> validators)
        => SourceGenerationHelpers.IsRequestLikeParameter(parameter)
           && validators.Any(validator => validator.RequestTypeFqn == parameter.TypeFqn);

    private static bool HasGeneratedDataAnnotationsValidation(FeatureModel feature)
        => feature.GetValidationParameters().Length > 0;

    private static void EmitDataAnnotationsValidationFactory(StringBuilder sb, FeatureModel f)
    {
        var candidates = f.GetValidationParameters();
        if (candidates.Length == 0)
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine($"    private static global::Microsoft.AspNetCore.Http.EndpointFilterDelegate {GeneratedDataAnnotationsFactoryName(f)}(");
        sb.AppendLine("        global::Microsoft.AspNetCore.Http.EndpointFilterFactoryContext context,");
        sb.AppendLine("        global::Microsoft.AspNetCore.Http.EndpointFilterDelegate next)");
        sb.AppendLine("    {");
        sb.AppendLine("        var __serviceProviderIsService = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>(context.ApplicationServices);");
        foreach (var candidate in candidates)
        {
            sb.AppendLine($"        var __validate{candidate.Index} = __ShouldValidateDataAnnotationsParameter<{candidate.TypeFqn}>(__serviceProviderIsService);");
        }

        sb.AppendLine($"        if ({string.Join(" && ", candidates.Select(static c => $"!__validate{c.Index}"))})");
        sb.AppendLine("        {");
        sb.AppendLine("            return next;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return invocationContext =>");
        sb.AppendLine("        {");
        foreach (var candidate in candidates)
        {
            sb.AppendLine($"            if (__validate{candidate.Index} && invocationContext.Arguments[{candidate.Index}] is {candidate.TypeFqn} __arg{candidate.Index})");
            sb.AppendLine("            {");
            sb.AppendLine($"                var __errors{candidate.Index} = {ValidationMethodName(f, candidate)}(__arg{candidate.Index});");
            sb.AppendLine($"                if (__errors{candidate.Index} is not null)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    return global::System.Threading.Tasks.ValueTask.FromResult<object?>(global::Microsoft.AspNetCore.Http.Results.ValidationProblem(__ToValidationProblemErrors(__errors{candidate.Index})));");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
        }

        sb.AppendLine();
        sb.AppendLine("            return next(invocationContext);");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static void EmitDataAnnotationsValidationHelpers(StringBuilder sb, ImmutableArray<FeatureModel> features)
    {
        if (!features.Any(HasGeneratedDataAnnotationsValidation))
        {
            return;
        }

        DataAnnotationsValidationEmitter.EmitValidationAttributeFields(
            sb,
            features.SelectMany(static feature => feature.GetValidationParameters()));

        foreach (var feature in features)
        {
            EmitDataAnnotationsValidationFactory(sb, feature);
            foreach (var parameter in feature.GetValidationParameters())
            {
                EmitValidationMethod(sb, feature, parameter);
                sb.AppendLine();
            }
        }

        sb.AppendLine();
        sb.AppendLine("    private static bool __ShouldValidateDataAnnotationsParameter<T>(");
        sb.AppendLine("        global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService? serviceProviderIsService)");
        sb.AppendLine("        => serviceProviderIsService?.IsService(typeof(T)) != true;");
        sb.AppendLine();
        EmitGeneratedValidationHelpers(sb);
    }

    private static void EmitValidationMethod(StringBuilder sb, FeatureModel feature, ValidationParameterModel parameter)
    {
        sb.AppendLine($"    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? {ValidationMethodName(feature, parameter)}({parameter.TypeFqn} value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>? errors = null;");

        foreach (var line in parameter.SerializedRules.Split('\n'))
        {
            DataAnnotationsValidationEmitter.EmitValidationRule(sb, line);
        }

        sb.AppendLine();
        sb.AppendLine("        return __ToValidationErrors(errors);");
        sb.AppendLine("    }");
    }

    private static void EmitSliceValidatorFactory(
        StringBuilder sb,
        FeatureModel f,
        ImmutableArray<ValidatorModel> validators)
    {
        var parameters = f.GetParams();
        var candidates = parameters
            .Select((Parameter, Index) => new { Parameter, Index })
            .Where(item => HasValidatorForParameter(item.Parameter, validators))
            .ToArray();
        if (candidates.Length == 0)
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine($"    private static global::Microsoft.AspNetCore.Http.EndpointFilterDelegate {GeneratedValidatorFactoryName(f)}(");
        sb.AppendLine("        global::Microsoft.AspNetCore.Http.EndpointFilterFactoryContext context,");
        sb.AppendLine("        global::Microsoft.AspNetCore.Http.EndpointFilterDelegate next)");
        sb.AppendLine("    {");
        sb.AppendLine("        var __serviceProviderIsService = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>(context.ApplicationServices);");
        foreach (var candidate in candidates)
        {
            sb.AppendLine($"        var __validate{candidate.Index} = __ShouldValidateSliceValidatorParameter<{candidate.Parameter.TypeFqn}>(__serviceProviderIsService);");
        }

        sb.AppendLine($"        if ({string.Join(" && ", candidates.Select(static c => $"!__validate{c.Index}"))})");
        sb.AppendLine("        {");
        sb.AppendLine("            return next;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return async invocationContext =>");
        sb.AppendLine("        {");
        foreach (var candidate in candidates)
        {
            sb.AppendLine($"            if (__validate{candidate.Index} && invocationContext.Arguments[{candidate.Index}] is {candidate.Parameter.TypeFqn} __arg{candidate.Index})");
            sb.AppendLine("            {");
            sb.AppendLine($"                var __validator{candidate.Index} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<global::SliceFx.ISliceValidator<{candidate.Parameter.TypeFqn}>>(invocationContext.HttpContext.RequestServices);");
            sb.AppendLine($"                if (__validator{candidate.Index} is not null)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var __result{candidate.Index} = await __validator{candidate.Index}.ValidateAsync(__arg{candidate.Index}, invocationContext.HttpContext.RequestAborted).ConfigureAwait(false);");
            sb.AppendLine($"                    if (!__result{candidate.Index}.IsValid)");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        return global::Microsoft.AspNetCore.Http.Results.ValidationProblem(__ToValidationProblemErrors(__result{candidate.Index}.Errors!));");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
        }

        sb.AppendLine();
        sb.AppendLine("            return await next(invocationContext).ConfigureAwait(false);");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static void EmitSliceValidatorHelpers(
        StringBuilder sb,
        ImmutableArray<FeatureModel> features,
        ImmutableArray<ValidatorModel> validators)
    {
        if (!features.Any(f => HasSliceValidatorCandidates(f.GetParams(), validators)))
        {
            return;
        }

        foreach (var feature in features)
        {
            EmitSliceValidatorFactory(sb, feature, validators);
        }

        sb.AppendLine();
        sb.AppendLine("    private static bool __ShouldValidateSliceValidatorParameter<T>(");
        sb.AppendLine("        global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService? serviceProviderIsService)");
        sb.AppendLine("        => serviceProviderIsService is null || serviceProviderIsService.IsService(typeof(global::SliceFx.ISliceValidator<T>));");
    }

    private static void EmitGeneratedValidationHelpers(StringBuilder sb)
    {
        sb.AppendLine("    private static void __AddValidationError(ref global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>? errors, string key, string message)");
        sb.AppendLine("    {");
        sb.AppendLine("        errors ??= new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>(global::System.StringComparer.Ordinal);");
        sb.AppendLine("        if (!errors.TryGetValue(key, out var messages))");
        sb.AppendLine("        {");
        sb.AppendLine("            messages = [];");
        sb.AppendLine("            errors.Add(key, messages);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        messages.Add(message);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? __ToValidationErrors(global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>? errors)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (errors is null || errors.Count == 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var result = new global::System.Collections.Generic.Dictionary<string, string[]>(global::System.StringComparer.Ordinal);");
        sb.AppendLine("        foreach (var entry in errors)");
        sb.AppendLine("        {");
        sb.AppendLine("            result.Add(entry.Key, entry.Value.ToArray());");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private static void EmitValidationProblemErrorHelper(
        StringBuilder sb,
        ImmutableArray<FeatureModel> features,
        ImmutableArray<ValidatorModel> validators)
    {
        if (!features.Any(HasGeneratedDataAnnotationsValidation)
            && !features.Any(f => HasSliceValidatorCandidates(f.GetParams(), validators)))
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine("    private static global::System.Collections.Generic.Dictionary<string, string[]> __ToValidationProblemErrors(");
        sb.AppendLine("        global::System.Collections.Generic.IReadOnlyDictionary<string, string[]> errors)");
        sb.AppendLine("    {");
        sb.AppendLine("        var result = new global::System.Collections.Generic.Dictionary<string, string[]>(errors.Count, global::System.StringComparer.Ordinal);");
        sb.AppendLine("        foreach (var error in errors)");
        sb.AppendLine("        {");
        sb.AppendLine("            result.Add(error.Key, error.Value);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private static string BuildDelegateType(ImmutableArray<HandleParamModel> parameters, string returnTypeFqn)
    {
        var args = new List<string>(parameters.Length + 1);
        foreach (var p in parameters)
        {
            args.Add(p.TypeFqn);
        }

        if (returnTypeFqn == "void")
        {
            return args.Count == 0
                ? "global::System.Action"
                : $"global::System.Action<{string.Join(", ", args)}>";
        }

        args.Add(returnTypeFqn);
        return args.Count == 1
            ? $"global::System.Func<{args[0]}>"
            : $"global::System.Func<{string.Join(", ", args)}>";
    }

    private static string ToSingleLineComment(string value)
        => value.Replace('\r', ' ').Replace('\n', ' ');

    private static string GeneratedValidatorFactoryName(FeatureModel feature)
        => "__CreateSliceValidatorFactory_" + SanitizeIdentifier(feature.FullyQualifiedTypeName);

    private static string GeneratedDataAnnotationsFactoryName(FeatureModel feature)
        => "__CreateDataAnnotationsValidationFactory_" + SanitizeIdentifier(feature.FullyQualifiedTypeName);

    private static string ValidationMethodName(FeatureModel feature, ValidationParameterModel parameter)
        => "__ValidateDataAnnotations_" + SanitizeIdentifier(feature.FullyQualifiedTypeName) + "_" + parameter.Index;

    private static string SanitizeIdentifier(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        return sb.ToString();
    }
}
