using System.Collections.Immutable;
using System.Text;

namespace SliceFx.SourceGenerator;

internal static class RegistrationEmitter
{
    /// <summary>
    /// Emits ASP.NET Core Slice registration source for the specified feature models.
    /// </summary>
    /// <param name="features">The feature models to include in generated registrations.</param>
    /// <param name="validators">The validator models to include in generated service registrations.</param>
    /// <param name="assemblyName">The target assembly name used to form the generated class name.</param>
    /// <param name="referencedModules">The referenced Slice modules to aggregate from user-facing extension methods.</param>
    /// <param name="emitExtensions">Whether to emit user-facing extension methods for this compilation.</param>
    /// <returns>The generated C# source.</returns>
    public static string Emit(
        ImmutableArray<FeatureModel> features,
        ImmutableArray<ValidatorModel> validators,
        string assemblyName,
        ImmutableArray<ReferencedSliceModule> referencedModules,
        bool emitExtensions)
    {
        var className = GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceRegistrations");
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        if (!features.IsEmpty || !validators.IsEmpty)
        {
            sb.AppendLine();
            sb.AppendLine($"[assembly: global::SliceFx.SliceFeatureModuleAttribute(typeof(global::SliceFx.{className}))]");
        }

        sb.AppendLine();
        sb.AppendLine("namespace SliceFx;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides generated Slice endpoint registration infrastructure.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        EmitAddSliceServices(sb, features, validators);
        sb.AppendLine();
        EmitMapSliceRoutes(sb, features, validators);
        if (emitExtensions)
        {
            sb.AppendLine();
            EmitAddSlice(sb, className, referencedModules);
            sb.AppendLine();
            EmitMapSlices(sb, className, referencedModules);
        }

        EmitDataAnnotationsValidationHelpers(sb, features);
        EmitSliceValidatorHelpers(sb, features, validators);
        EmitValidationProblemErrorHelper(sb, features, validators);
        EmitSliceFilterHelpers(sb, features);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitAddSliceServices(
        StringBuilder sb,
        ImmutableArray<FeatureModel> features,
        ImmutableArray<ValidatorModel> validators)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers services required by this generated Slice endpoint module.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to add Slice services to.</param>");
        sb.AppendLine("    /// <returns>The same service collection for chaining.</returns>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSliceServices(");
        sb.AppendLine("        global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        var seen = new HashSet<string>(StringComparer.Ordinal);

        foreach (var feature in features)
        {
            foreach (var ft in feature.GetFilterFqns())
            {
                if (seen.Add(ft))
                {
                    sb.AppendLine($"        services.AddScoped<{ft}>();");
                }
            }

            // Register neutral filter types (ISliceFilter) as scoped alongside ASP.NET filters.
            foreach (var ft in feature.GetSliceFilterFqns())
            {
                if (seen.Add(ft))
                {
                    sb.AppendLine($"        services.AddScoped<{ft}>();");
                }
            }
        }

        sb.AppendLine("        AddSliceValidatorServices(services);");

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();
        EmitAddSliceValidatorServices(sb, validators);
    }

    private static void EmitAddSliceValidatorServices(StringBuilder sb, ImmutableArray<ValidatorModel> validators)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers validators required by this generated Slice endpoint module.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to add Slice validators to.</param>");
        sb.AppendLine("    /// <returns>The same service collection for chaining.</returns>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSliceValidatorServices(");
        sb.AppendLine("        global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var validator in validators)
        {
            sb.AppendLine($"        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::SliceFx.ISliceValidator<{validator.RequestTypeFqn}>, {validator.ImplementationTypeFqn}>(services);");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
    }

    private static void EmitMapSliceRoutes(
        StringBuilder sb,
        ImmutableArray<FeatureModel> features,
        ImmutableArray<ValidatorModel> validators)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps this generated Slice endpoint module to the route builder.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"app\">The endpoint route builder to map Slice endpoints onto.</param>");
        sb.AppendLine("    /// <returns>The same endpoint route builder for chaining.</returns>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapSliceRoutes(");
        sb.AppendLine("        global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)");
        sb.AppendLine("    {");

        foreach (var f in features)
        {
            sb.AppendLine($"        // {ToSingleLineComment(f.EndpointName)}");
            EmitFeatureRegistration(sb, f, validators);
            sb.AppendLine();
        }

        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
    }

    private static void EmitAddSlice(
        StringBuilder sb,
        string className,
        ImmutableArray<ReferencedSliceModule> referencedModules)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers services required by generated Slice endpoint registrations.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to add Slice services to.</param>");
        sb.AppendLine("    /// <returns>The same service collection for chaining.</returns>");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSlice(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        global::SliceFx.{className}.AddSliceServices(services);");
        foreach (var module in referencedModules)
        {
            if (module.HasAspNetServices)
            {
                sb.AppendLine($"        {module.RegistrationTypeFqn}.AddSliceServices(services);");
            }
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
    }

    private static void EmitMapSlices(
        StringBuilder sb,
        string className,
        ImmutableArray<ReferencedSliceModule> referencedModules)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps generated Slice endpoints to the route builder.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"app\">The endpoint route builder to map Slice endpoints onto.</param>");
        sb.AppendLine("    /// <returns>The same endpoint route builder for chaining.</returns>");
        sb.AppendLine("    public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapSlices(");
        sb.AppendLine("        this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)");
        sb.AppendLine("    {");
        sb.AppendLine($"        global::SliceFx.{className}.MapSliceRoutes(app);");
        foreach (var module in referencedModules)
        {
            if (module.HasAspNetRoutes)
            {
                sb.AppendLine($"        {module.RegistrationTypeFqn}.MapSliceRoutes(app);");
            }
        }

        sb.AppendLine("        global::SliceFx.SliceMigrationAuditEndpointRouteBuilderExtensions.RunSliceMigrationAudit(app);");
        sb.AppendLine();
        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
    }

    private static void EmitFeatureRegistration(
        StringBuilder sb,
        FeatureModel f,
        ImmutableArray<ValidatorModel> validators)
    {
        var paramModels = f.GetParams();
        var filterFqns = f.GetFilterFqns();
        var sliceFilterFqns = f.GetSliceFilterFqns();

        sb.AppendLine($"        app.MapMethods(");
        sb.AppendLine($"            {CSharpLiteral.String(f.Pattern)},");
        sb.AppendLine($"            new[] {{ {CSharpLiteral.String(f.HttpMethod)} }},");

        var awaitedReturn = SourceGenerationHelpers.GetAwaitedReturnType(f.ReturnTypeFqn);
        if (SourceGenerationHelpers.IsSliceResultNonGenericType(awaitedReturn))
        {
            // Wrap Handle in a lambda that calls __SliceResultToIResult so Minimal API dispatches
            // the result correctly (Redirect → 301/302, RawBody → Bytes, StatusOnly → status code).
            // Without the wrapper, Minimal API JSON-serializes the SliceResult struct — incorrect.
            var lambdaParams = BuildLambdaParamList(paramModels);
            var argList = BuildCallArgList(paramModels);
            var asyncPrefix = SourceGenerationHelpers.IsGenericAwaitable(f.ReturnTypeFqn) ? "async " : "";
            var awaitPrefix = SourceGenerationHelpers.IsGenericAwaitable(f.ReturnTypeFqn) ? "await " : "";
            var lambdaBody = $"__SliceResultToIResult({awaitPrefix}{f.FullyQualifiedTypeName}.Handle({argList}))";
            sb.AppendLine($"            {asyncPrefix}({lambdaParams}) => {lambdaBody})");
        }
        else
        {
            var delegateType = BuildDelegateType(paramModels, f.ReturnTypeFqn);
            sb.AppendLine($"            new {delegateType}(");
            sb.AppendLine($"                {f.FullyQualifiedTypeName}.Handle))");
        }

        // Neutral filters run outermost (before validation) — [SliceFilter<T>] in declaration order.
        foreach (var ft in sliceFilterFqns)
        {
            sb.AppendLine($"        .AddEndpointFilter(static (c, n) => __InvokeSliceFilter<{ft}>(c, n))");
        }

        if (HasGeneratedDataAnnotationsValidation(f))
        {
            sb.AppendLine($"        .AddEndpointFilterFactory(");
            sb.AppendLine($"            {GeneratedDataAnnotationsFactoryName(f)})");
        }

        if (HasSliceValidatorCandidates(paramModels, validators))
        {
            sb.AppendLine($"        .AddEndpointFilterFactory(");
            sb.AppendLine($"            {GeneratedValidatorFactoryName(f)})");
        }

        // ASP.NET-specific filters — [Filter<T>] in declaration order (after validation).
        foreach (var ft in filterFqns)
        {
            sb.AppendLine($"        .AddEndpointFilter<{ft}>()");
        }

        sb.AppendLine($"        .WithTags({CSharpLiteral.String(f.Tag)})");
        sb.AppendLine($"        .WithName({CSharpLiteral.String(f.EndpointName)})");

        if (f.Summary is not null)
        {
            sb.AppendLine($"        .WithSummary({CSharpLiteral.String(f.Summary)});");
        }
        else
        {
            sb.AppendLine($"        ;");
        }
    }

    private static bool HasSliceValidatorCandidates(
        ImmutableArray<HandleParamModel> parameters,
        ImmutableArray<ValidatorModel> validators)
        => parameters.Any(parameter => HasValidatorForParameter(parameter, validators));

    private static bool HasValidatorForParameter(
        HandleParamModel parameter,
        ImmutableArray<ValidatorModel> validators)
        => SourceGenerationHelpers.IsRequestLikeParameter(parameter)
           && validators.Any(validator => validator.RequestTypeFqn == parameter.TypeFqn);

    private static bool HasGeneratedDataAnnotationsValidation(FeatureModel feature)
        => feature.GetValidationParameters().Length > 0;

    private static void EmitDataAnnotationsValidationFactory(StringBuilder sb, FeatureModel f)
    {
        var candidates = f.GetValidationParameters();
        if (candidates.Length == 0)
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine($"    private static global::Microsoft.AspNetCore.Http.EndpointFilterDelegate {GeneratedDataAnnotationsFactoryName(f)}(");
        sb.AppendLine("        global::Microsoft.AspNetCore.Http.EndpointFilterFactoryContext context,");
        sb.AppendLine("        global::Microsoft.AspNetCore.Http.EndpointFilterDelegate next)");
        sb.AppendLine("    {");
        sb.AppendLine("        var __serviceProviderIsService = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>(context.ApplicationServices);");
        foreach (var candidate in candidates)
        {
            sb.AppendLine($"        var __validate{candidate.Index} = __ShouldValidateDataAnnotationsParameter<{candidate.TypeFqn}>(__serviceProviderIsService);");
        }

        sb.AppendLine($"        if ({string.Join(" && ", candidates.Select(static c => $"!__validate{c.Index}"))})");
        sb.AppendLine("        {");
        sb.AppendLine("            return next;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return invocationContext =>");
        sb.AppendLine("        {");
        foreach (var candidate in candidates)
        {
            sb.AppendLine($"            if (__validate{candidate.Index} && invocationContext.Arguments[{candidate.Index}] is {candidate.TypeFqn} __arg{candidate.Index})");
            sb.AppendLine("            {");
            sb.AppendLine($"                var __errors{candidate.Index} = {ValidationMethodName(f, candidate)}(__arg{candidate.Index});");
            sb.AppendLine($"                if (__errors{candidate.Index} is not null)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    return global::System.Threading.Tasks.ValueTask.FromResult<object?>(global::Microsoft.AspNetCore.Http.Results.ValidationProblem(__ToValidationProblemErrors(__errors{candidate.Index})));");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
        }

        sb.AppendLine();
        sb.AppendLine("            return next(invocationContext);");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static void EmitDataAnnotationsValidationHelpers(StringBuilder sb, ImmutableArray<FeatureModel> features)
    {
        if (!features.Any(HasGeneratedDataAnnotationsValidation))
        {
            return;
        }

        DataAnnotationsValidationEmitter.EmitValidationAttributeFields(
            sb,
            features.SelectMany(static feature => feature.GetValidationParameters()));

        foreach (var feature in features)
        {
            EmitDataAnnotationsValidationFactory(sb, feature);
            foreach (var parameter in feature.GetValidationParameters())
            {
                EmitValidationMethod(sb, feature, parameter);
                sb.AppendLine();
            }
        }

        sb.AppendLine();
        sb.AppendLine("    private static bool __ShouldValidateDataAnnotationsParameter<T>(");
        sb.AppendLine("        global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService? serviceProviderIsService)");
        sb.AppendLine("        => serviceProviderIsService?.IsService(typeof(T)) != true;");
        sb.AppendLine();
        EmitGeneratedValidationHelpers(sb);
    }

    private static void EmitValidationMethod(StringBuilder sb, FeatureModel feature, ValidationParameterModel parameter)
    {
        sb.AppendLine($"    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? {ValidationMethodName(feature, parameter)}({parameter.TypeFqn} value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>? errors = null;");

        foreach (var line in parameter.SerializedRules.Split('\n'))
        {
            DataAnnotationsValidationEmitter.EmitValidationRule(sb, line);
        }

        sb.AppendLine();
        sb.AppendLine("        return __ToValidationErrors(errors);");
        sb.AppendLine("    }");
    }

    private static void EmitSliceValidatorFactory(
        StringBuilder sb,
        FeatureModel f,
        ImmutableArray<ValidatorModel> validators)
    {
        var parameters = f.GetParams();
        var candidates = parameters
            .Select((Parameter, Index) => new { Parameter, Index })
            .Where(item => HasValidatorForParameter(item.Parameter, validators))
            .ToArray();
        if (candidates.Length == 0)
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine($"    private static global::Microsoft.AspNetCore.Http.EndpointFilterDelegate {GeneratedValidatorFactoryName(f)}(");
        sb.AppendLine("        global::Microsoft.AspNetCore.Http.EndpointFilterFactoryContext context,");
        sb.AppendLine("        global::Microsoft.AspNetCore.Http.EndpointFilterDelegate next)");
        sb.AppendLine("    {");
        sb.AppendLine("        var __serviceProviderIsService = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>(context.ApplicationServices);");
        foreach (var candidate in candidates)
        {
            sb.AppendLine($"        var __validate{candidate.Index} = __ShouldValidateSliceValidatorParameter<{candidate.Parameter.TypeFqn}>(__serviceProviderIsService);");
        }

        sb.AppendLine($"        if ({string.Join(" && ", candidates.Select(static c => $"!__validate{c.Index}"))})");
        sb.AppendLine("        {");
        sb.AppendLine("            return next;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return async invocationContext =>");
        sb.AppendLine("        {");
        foreach (var candidate in candidates)
        {
            sb.AppendLine($"            if (__validate{candidate.Index} && invocationContext.Arguments[{candidate.Index}] is {candidate.Parameter.TypeFqn} __arg{candidate.Index})");
            sb.AppendLine("            {");
            sb.AppendLine($"                var __validator{candidate.Index} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<global::SliceFx.ISliceValidator<{candidate.Parameter.TypeFqn}>>(invocationContext.HttpContext.RequestServices);");
            sb.AppendLine($"                if (__validator{candidate.Index} is not null)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var __result{candidate.Index} = await __validator{candidate.Index}.ValidateAsync(__arg{candidate.Index}, invocationContext.HttpContext.RequestAborted).ConfigureAwait(false);");
            sb.AppendLine($"                    if (!__result{candidate.Index}.IsValid)");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        return global::Microsoft.AspNetCore.Http.Results.ValidationProblem(__ToValidationProblemErrors(__result{candidate.Index}.Errors!));");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
        }

        sb.AppendLine();
        sb.AppendLine("            return await next(invocationContext).ConfigureAwait(false);");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static void EmitSliceValidatorHelpers(
        StringBuilder sb,
        ImmutableArray<FeatureModel> features,
        ImmutableArray<ValidatorModel> validators)
    {
        if (!features.Any(f => HasSliceValidatorCandidates(f.GetParams(), validators)))
        {
            return;
        }

        foreach (var feature in features)
        {
            EmitSliceValidatorFactory(sb, feature, validators);
        }

        sb.AppendLine();
        sb.AppendLine("    private static bool __ShouldValidateSliceValidatorParameter<T>(");
        sb.AppendLine("        global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService? serviceProviderIsService)");
        sb.AppendLine("        => serviceProviderIsService is null || serviceProviderIsService.IsService(typeof(global::SliceFx.ISliceValidator<T>));");
    }

    private static void EmitGeneratedValidationHelpers(StringBuilder sb)
    {
        sb.AppendLine("    private static void __AddValidationError(ref global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>? errors, string key, string message)");
        sb.AppendLine("    {");
        sb.AppendLine("        errors ??= new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>(global::System.StringComparer.Ordinal);");
        sb.AppendLine("        if (!errors.TryGetValue(key, out var messages))");
        sb.AppendLine("        {");
        sb.AppendLine("            messages = [];");
        sb.AppendLine("            errors.Add(key, messages);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        messages.Add(message);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? __ToValidationErrors(global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>? errors)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (errors is null || errors.Count == 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var result = new global::System.Collections.Generic.Dictionary<string, string[]>(global::System.StringComparer.Ordinal);");
        sb.AppendLine("        foreach (var entry in errors)");
        sb.AppendLine("        {");
        sb.AppendLine("            result.Add(entry.Key, entry.Value.ToArray());");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private static void EmitValidationProblemErrorHelper(
        StringBuilder sb,
        ImmutableArray<FeatureModel> features,
        ImmutableArray<ValidatorModel> validators)
    {
        if (!features.Any(HasGeneratedDataAnnotationsValidation)
            && !features.Any(f => HasSliceValidatorCandidates(f.GetParams(), validators)))
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine("    private static global::System.Collections.Generic.Dictionary<string, string[]> __ToValidationProblemErrors(");
        sb.AppendLine("        global::System.Collections.Generic.IReadOnlyDictionary<string, string[]> errors)");
        sb.AppendLine("    {");
        sb.AppendLine("        var result = new global::System.Collections.Generic.Dictionary<string, string[]>(errors.Count, global::System.StringComparer.Ordinal);");
        sb.AppendLine("        foreach (var error in errors)");
        sb.AppendLine("        {");
        sb.AppendLine("            result.Add(error.Key, error.Value);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private static void EmitSliceFilterHelpers(StringBuilder sb, ImmutableArray<FeatureModel> features)
    {
        var hasFilterFeatures = features.Any(static f => !f.GetSliceFilterFqns().IsEmpty);
        var hasNonGenericSliceResultFeatures = features.Any(static f =>
            SourceGenerationHelpers.IsSliceResultNonGenericType(
                SourceGenerationHelpers.GetAwaitedReturnType(f.ReturnTypeFqn)));

        if (!hasFilterFeatures && !hasNonGenericSliceResultFeatures)
        {
            return;
        }

        if (hasFilterFeatures)
        {
            sb.AppendLine();
            // Generic bridge: resolves TFilter from DI, builds SliceFilterContext, adapts the ASP.NET
            // EndpointFilterDelegate to SliceFilterDelegate, invokes the neutral filter, and maps the
            // result back to the object? that MapMethods / AddEndpointFilter expects.
            sb.AppendLine("    private static async global::System.Threading.Tasks.ValueTask<object?> __InvokeSliceFilter<TFilter>(");
            sb.AppendLine("        global::Microsoft.AspNetCore.Http.EndpointFilterInvocationContext ctx,");
            sb.AppendLine("        global::Microsoft.AspNetCore.Http.EndpointFilterDelegate next)");
            sb.AppendLine("        where TFilter : class, global::SliceFx.ISliceFilter");
            sb.AppendLine("    {");
            sb.AppendLine("        var __filter = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<TFilter>(ctx.HttpContext.RequestServices);");
            sb.AppendLine("        var __filterCtx = __BuildSliceFilterContext(ctx);");
            sb.AppendLine("        global::SliceFx.SliceFilterDelegate __next = async __ =>");
            sb.AppendLine("        {");
            sb.AppendLine("            var __r = await next(ctx).ConfigureAwait(false);");
            sb.AppendLine("            // Best-effort status: exact for IStatusCodeHttpResult, null for POCO/unknown results.");
            sb.AppendLine("            int? __s = __r is global::Microsoft.AspNetCore.Http.IStatusCodeHttpResult __sc ? __sc.StatusCode : null;");
            sb.AppendLine("            return global::SliceFx.SliceFilterResult.PassThrough(__r, __s);");
            sb.AppendLine("        };");
            sb.AppendLine("        var __result = await __filter.InvokeAsync(__filterCtx, __next).ConfigureAwait(false);");
            sb.AppendLine("        if (__result.IsShortCircuit)");
            sb.AppendLine("            return __SliceResultToIResult(__result.ShortCircuitResult!.Value);");
            sb.AppendLine("        return __result.HostResponse;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    private static global::SliceFx.SliceFilterContext __BuildSliceFilterContext(");
            sb.AppendLine("        global::Microsoft.AspNetCore.Http.EndpointFilterInvocationContext ctx)");
            sb.AppendLine("    {");
            sb.AppendLine("        var __headers = new global::System.Collections.Generic.Dictionary<string, string>(global::System.StringComparer.OrdinalIgnoreCase);");
            sb.AppendLine("        foreach (var __h in ctx.HttpContext.Request.Headers)");
            sb.AppendLine("        {");
            sb.AppendLine("            __headers[__h.Key] = __h.Value.ToString();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        var __routeValues = new global::System.Collections.Generic.Dictionary<string, string>(global::System.StringComparer.OrdinalIgnoreCase);");
            sb.AppendLine("        foreach (var __rv in ctx.HttpContext.Request.RouteValues)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (__rv.Value is not null)");
            sb.AppendLine("                __routeValues[__rv.Key] = __rv.Value.ToString() ?? string.Empty;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        return new global::SliceFx.SliceFilterContext(");
            sb.AppendLine("            ctx.HttpContext.Request.Method,");
            sb.AppendLine("            ctx.HttpContext.Request.Path,");
            sb.AppendLine("            __headers,");
            sb.AppendLine("            __routeValues,");
            sb.AppendLine("            ctx.HttpContext.RequestServices,");
            sb.AppendLine("            ctx.HttpContext.RequestAborted);");
            sb.AppendLine("    }");
        }

        sb.AppendLine();
        sb.AppendLine("    private static global::Microsoft.AspNetCore.Http.IResult __SliceResultToIResult(");
        sb.AppendLine("        global::SliceFx.SliceResult result)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!result.IsSuccess)");
        sb.AppendLine("            return global::Microsoft.AspNetCore.Http.Results.Problem(");
        sb.AppendLine("                detail: result.ProblemDetail,");
        sb.AppendLine("                statusCode: result.Status,");
        sb.AppendLine("                title: result.ProblemTitle);");
        sb.AppendLine("        if (result.Kind == global::SliceFx.SliceResultKind.Redirect)");
        sb.AppendLine("            return global::Microsoft.AspNetCore.Http.Results.Redirect(");
        sb.AppendLine("                result.Location!,");
        sb.AppendLine("                permanent: result.Status == 301);");
        sb.AppendLine("        if (result.Kind == global::SliceFx.SliceResultKind.RawBody)");
        sb.AppendLine("            return new __RawBytesResult(result.Body!, result.ContentType!, result.Status);");
        // StatusOnly: 201 Created with Location, or bare status code (200 OK / 204 No Content / etc.)
        sb.AppendLine("        if (result.Location is not null)");
        // Results.Created(string? uri, object? value) — no body (null value) with Location header.
        sb.AppendLine("            return global::Microsoft.AspNetCore.Http.Results.Created(result.Location, value: null);");
        sb.AppendLine("        return global::Microsoft.AspNetCore.Http.Results.StatusCode(result.Status);");
        sb.AppendLine("    }");
        sb.AppendLine();
        // __RawBytesResult: IResult implementation for RawBody (binary or text) with arbitrary status.
        // Results.Bytes() is a file-download helper that always returns 200 and does not accept
        // a statusCode parameter; we emit our own minimal IResult instead.
        sb.AppendLine("    private sealed class __RawBytesResult : global::Microsoft.AspNetCore.Http.IResult");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly byte[] _body;");
        sb.AppendLine("        private readonly string _contentType;");
        sb.AppendLine("        private readonly int _statusCode;");
        sb.AppendLine("        internal __RawBytesResult(byte[] body, string contentType, int statusCode)");
        sb.AppendLine("        {");
        sb.AppendLine("            _body = body;");
        sb.AppendLine("            _contentType = contentType;");
        sb.AppendLine("            _statusCode = statusCode;");
        sb.AppendLine("        }");
        sb.AppendLine("        public global::System.Threading.Tasks.Task ExecuteAsync(");
        sb.AppendLine("            global::Microsoft.AspNetCore.Http.HttpContext httpContext)");
        sb.AppendLine("        {");
        sb.AppendLine("            httpContext.Response.StatusCode = _statusCode;");
        sb.AppendLine("            httpContext.Response.ContentType = _contentType;");
        sb.AppendLine("            return httpContext.Response.Body.WriteAsync(_body, 0, _body.Length);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// Builds the lambda parameter list for a non-generic SliceResult wrapper delegate, including
    /// explicit binding attributes for parameters that need them (e.g. <c>[FromHeader]</c>).
    /// </summary>
    private static string BuildLambdaParamList(ImmutableArray<HandleParamModel> parameters)
    {
        if (parameters.IsEmpty)
        {
            return "";
        }

        var parts = new List<string>(parameters.Length);
        foreach (var p in parameters)
        {
            var attr = "";
            if (p.BindingSource == "header" && p.BindingName is not null)
            {
                attr = $"[global::Microsoft.AspNetCore.Mvc.FromHeaderAttribute(Name = {CSharpLiteral.String(p.BindingName)})] ";
            }
            else if (p.BindingSource == "query" && p.BindingName is not null && p.BindingName != p.Name)
            {
                attr = $"[global::Microsoft.AspNetCore.Mvc.FromQueryAttribute(Name = {CSharpLiteral.String(p.BindingName)})] ";
            }
            else if (p.BindingSource == "route" && p.BindingName is not null && p.BindingName != p.Name)
            {
                attr = $"[global::Microsoft.AspNetCore.Mvc.FromRouteAttribute(Name = {CSharpLiteral.String(p.BindingName)})] ";
            }
            else if (p.BindingSource == "keyedServices" && p.BindingKeyLiteral is not null)
            {
                attr = $"[global::Microsoft.Extensions.DependencyInjection.FromKeyedServicesAttribute({p.BindingKeyLiteral})] ";
            }

            parts.Add($"{attr}{p.TypeFqn} {p.Name}");
        }

        return string.Join(", ", parts);
    }

    /// <summary>
    /// Builds the call argument list for a non-generic SliceResult wrapper lambda.
    /// All parameters are forwarded by name.
    /// </summary>
    private static string BuildCallArgList(ImmutableArray<HandleParamModel> parameters)
    {
        if (parameters.IsEmpty)
        {
            return "";
        }

        var parts = new List<string>(parameters.Length);
        foreach (var p in parameters)
        {
            parts.Add(p.Name);
        }

        return string.Join(", ", parts);
    }

    private static string BuildDelegateType(ImmutableArray<HandleParamModel> parameters, string returnTypeFqn)
    {
        var args = new List<string>(parameters.Length + 1);
        foreach (var p in parameters)
        {
            args.Add(p.TypeFqn);
        }

        if (returnTypeFqn == "void")
        {
            return args.Count == 0
                ? "global::System.Action"
                : $"global::System.Action<{string.Join(", ", args)}>";
        }

        args.Add(returnTypeFqn);
        return args.Count == 1
            ? $"global::System.Func<{args[0]}>"
            : $"global::System.Func<{string.Join(", ", args)}>";
    }

    private static string ToSingleLineComment(string value)
        => value.Replace('\r', ' ').Replace('\n', ' ');

    private static string GeneratedValidatorFactoryName(FeatureModel feature)
        => "__CreateSliceValidatorFactory_" + SanitizeIdentifier(feature.FullyQualifiedTypeName);

    private static string GeneratedDataAnnotationsFactoryName(FeatureModel feature)
        => "__CreateDataAnnotationsValidationFactory_" + SanitizeIdentifier(feature.FullyQualifiedTypeName);

    private static string ValidationMethodName(FeatureModel feature, ValidationParameterModel parameter)
        => "__ValidateDataAnnotations_" + SanitizeIdentifier(feature.FullyQualifiedTypeName) + "_" + parameter.Index;

    private static string SanitizeIdentifier(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        return sb.ToString();
    }
}
