using System.Collections.Immutable;
using System.Text;

namespace SliceFx.SourceGenerator;

internal static class RouteManifestEmitter
{
    public static string Emit(
        ImmutableArray<FeatureModel> features,
        ImmutableArray<ValidatorModel> validators,
        string assemblyName,
        ImmutableArray<ReferencedSliceModule> referencedModules,
        bool emitLambdaFunctionPerFeatureHandlers,
        JsonContextPlan wasiJsonContextPlan,
        JsonContextPlan lambdaJsonContextPlan)
    {
        var className = GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceRouteManifest");

        // Union of all registered serializable types across WASI and Lambda JSON contexts.
        // Used as the compile-time body/service discriminator for manifest RequestType computation,
        // so that concrete DI services (not in either JSON context) are not misclassified as body params.
        var unionSerializableTypes = BuildUnionSerializableTypes(wasiJsonContextPlan, lambdaJsonContextPlan);

        var routes = BuildRouteManifestEntries(
            features,
            assemblyName,
            emitLambdaFunctionPerFeatureHandlers,
            wasiJsonContextPlan,
            lambdaJsonContextPlan,
            unionSerializableTypes);
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        EmitAggregatedAssemblyAttributes(sb, referencedModules);
        EmitRouteAttributes(sb, routes, unionSerializableTypes);
        EmitValidatorAttributes(sb, validators);
        sb.AppendLine();
        sb.AppendLine("namespace SliceFx;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides generated Slice route metadata for tooling and deployment adapters.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        EmitDescriptor(sb);
        sb.AppendLine();
        EmitRoutesField(sb, routes, unionSerializableTypes);
        sb.AppendLine();
        EmitAccessor(sb);
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitAggregatedAssemblyAttributes(
        StringBuilder sb,
        ImmutableArray<ReferencedSliceModule> referencedModules)
    {
        if (referencedModules.IsEmpty)
        {
            return;
        }

        sb.AppendLine();
        foreach (var assemblyName in referencedModules
                     .Select(static module => module.AssemblyName)
                     .Distinct(StringComparer.Ordinal)
                     .OrderBy(static assemblyName => assemblyName, StringComparer.Ordinal))
        {
            sb.AppendLine(
                $"[assembly: global::SliceFx.SliceAggregatedFeatureAssemblyAttribute({CSharpLiteral.String(assemblyName)})]");
        }
    }

    private static void EmitRouteAttributes(
        StringBuilder sb,
        ImmutableArray<RouteManifestEntry> routes,
        HashSet<string>? serializableTypes = null)
    {
        if (routes.IsEmpty)
        {
            return;
        }

        sb.AppendLine();
        foreach (var route in routes)
        {
            var feature = route.Feature;

            sb.AppendLine(
                $"[assembly: global::SliceFx.SliceFeatureRouteAttribute({CSharpLiteral.String(feature.EndpointName)}, {CSharpLiteral.String(SourceGenerationHelpers.TrimGlobalAlias(feature.FullyQualifiedTypeName))}, {CSharpLiteral.String(feature.HttpMethod)}, {CSharpLiteral.String(feature.Pattern)}, {CSharpLiteral.String(feature.Tag)}, {CSharpNullableStringLiteral(feature.Summary)}, {CSharpNullableStringLiteral(FindRequestType(feature, serializableTypes))}, {CSharpLiteral.String(SourceGenerationHelpers.TrimGlobalAlias(feature.ReturnTypeFqn))}, {CSharpLiteral.String(route.Portability)}, {CSharpNullableStringLiteral(route.PortabilityReason)}, {CSharpNullableStringLiteral(SerializeFilterTypes(feature))}, {CSharpNullableStringLiteral(SerializeParameters(feature))}, {CSharpNullableStringLiteral(route.LambdaStatus)}, {CSharpNullableStringLiteral(route.LambdaReason)}, {CSharpNullableStringLiteral(route.LambdaHandlerAssembly)}, {CSharpNullableStringLiteral(route.LambdaHandlerType)}, {CSharpNullableStringLiteral(route.LambdaHandlerMethod)}, {CSharpLiteral.String(SourceGenerationHelpers.ManifestSchemaVersion)}, {CSharpNullableStringLiteral(route.WasiStatus)}, {CSharpNullableStringLiteral(route.WasiReason)}, {CSharpNullableStringLiteral(route.LambdaArtifactId)}, {CSharpNullableStringLiteral(route.LambdaArtifactLayout)}, {CSharpNullableStringLiteral(route.LambdaArtifactCodeUri)}, {CSharpNullableStringLiteral(route.LambdaBootstrapMode)}, {CSharpNullableStringLiteral(route.LambdaRuntimeIdentifier)}, {CSharpNullableStringLiteral(SerializeSliceFilterTypes(feature))})]");
        }
    }

    private static void EmitValidatorAttributes(
        StringBuilder sb,
        ImmutableArray<ValidatorModel> validators)
    {
        if (validators.IsEmpty)
        {
            return;
        }

        sb.AppendLine();
        foreach (var validator in validators)
        {
            sb.AppendLine(
                $"[assembly: global::SliceFx.SliceFeatureValidatorAttribute({CSharpLiteral.String(validator.RequestTypeFqn)}, {CSharpLiteral.String(validator.ImplementationTypeFqn)})]");
        }
    }

    private static void EmitDescriptor(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Describes one generated Slice route.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed record SliceRouteDescriptor(");
        sb.AppendLine("        string Method,");
        sb.AppendLine("        string Pattern,");
        sb.AppendLine("        string FeatureType,");
        sb.AppendLine("        string Tag,");
        sb.AppendLine("        string EndpointName,");
        sb.AppendLine("        string? Summary,");
        sb.AppendLine("        string? RequestType,");
        sb.AppendLine("        string ReturnType,");
        sb.AppendLine("        string ManifestSchemaVersion,");
        sb.AppendLine("        bool IsWasiCompatible,");
        sb.AppendLine("        string Portability,");
        sb.AppendLine("        string? PortabilityReason,");
        sb.AppendLine("        string? WasiDispatchStatus,");
        sb.AppendLine("        string? WasiDispatchReason,");
        sb.AppendLine("        string? LambdaFunctionPerFeatureStatus,");
        sb.AppendLine("        string? LambdaFunctionPerFeatureReason,");
        sb.AppendLine("        string? LambdaFunctionPerFeatureHandlerAssembly,");
        sb.AppendLine("        string? LambdaFunctionPerFeatureHandlerType,");
        sb.AppendLine("        string? LambdaFunctionPerFeatureHandlerMethod,");
        sb.AppendLine("        string? LambdaFunctionPerFeatureArtifactId,");
        sb.AppendLine("        string? LambdaFunctionPerFeatureArtifactLayout,");
        sb.AppendLine("        string? LambdaFunctionPerFeatureArtifactCodeUri,");
        sb.AppendLine("        string? LambdaFunctionPerFeatureBootstrapMode,");
        sb.AppendLine("        string? LambdaFunctionPerFeatureRuntimeIdentifier,");
        sb.AppendLine("        global::System.Collections.Generic.IReadOnlyList<string> FilterTypes);");
    }

    private static void EmitRoutesField(
        StringBuilder sb,
        ImmutableArray<RouteManifestEntry> routes,
        HashSet<string>? serializableTypes = null)
    {
        sb.AppendLine("    private static readonly SliceRouteDescriptor[] s_routes =");
        sb.AppendLine("    [");
        foreach (var route in routes)
        {
            var feature = route.Feature;

            sb.AppendLine("        new SliceRouteDescriptor(");
            sb.AppendLine($"            {CSharpLiteral.String(feature.HttpMethod)},");
            sb.AppendLine($"            {CSharpLiteral.String(feature.Pattern)},");
            sb.AppendLine($"            {CSharpLiteral.String(SourceGenerationHelpers.TrimGlobalAlias(feature.FullyQualifiedTypeName))},");
            sb.AppendLine($"            {CSharpLiteral.String(feature.Tag)},");
            sb.AppendLine($"            {CSharpLiteral.String(feature.EndpointName)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(feature.Summary)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(FindRequestType(feature, serializableTypes))},");
            sb.AppendLine($"            {CSharpLiteral.String(SourceGenerationHelpers.TrimGlobalAlias(feature.ReturnTypeFqn))},");
            sb.AppendLine($"            {CSharpLiteral.String(SourceGenerationHelpers.ManifestSchemaVersion)},");
            sb.AppendLine($"            {BoolLiteral(route.WasiStatus == SourceGenerationHelpers.ManifestEligible)},");
            sb.AppendLine($"            {CSharpLiteral.String(route.Portability)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.PortabilityReason)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.WasiStatus)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.WasiReason)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.LambdaStatus)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.LambdaReason)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.LambdaHandlerAssembly)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.LambdaHandlerType)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.LambdaHandlerMethod)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.LambdaArtifactId)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.LambdaArtifactLayout)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.LambdaArtifactCodeUri)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.LambdaBootstrapMode)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.LambdaRuntimeIdentifier)},");
            sb.AppendLine($"            {FilterTypesLiteral(feature)}),");
        }
        sb.AppendLine("    ];");
    }

    private static ImmutableArray<RouteManifestEntry> BuildRouteManifestEntries(
        ImmutableArray<FeatureModel> features,
        string assemblyName,
        bool emitLambdaFunctionPerFeatureHandlers,
        JsonContextPlan wasiJsonContextPlan,
        JsonContextPlan lambdaJsonContextPlan,
        HashSet<string>? serializableTypes = null)
    {
        var routes = ImmutableArray.CreateBuilder<RouteManifestEntry>(features.Length);
        foreach (var feature in features)
        {
            var (portability, portabilityReason) = ClassifyPortability(feature, serializableTypes);
            var wasiStatus = JsonContextPlanner.StatusForWasi(feature, wasiJsonContextPlan);
            var wasiReason = JsonContextPlanner.ReasonForWasi(feature, wasiJsonContextPlan);
            var lambda =
                GetEmittedLambdaMetadata(feature, assemblyName, emitLambdaFunctionPerFeatureHandlers, lambdaJsonContextPlan);
            routes.Add(new RouteManifestEntry(
                feature,
                portability,
                portabilityReason,
                wasiStatus,
                wasiReason,
                lambda.Status,
                lambda.Reason,
                lambda.HandlerAssembly,
                lambda.HandlerType,
                lambda.HandlerMethod,
                lambda.ArtifactId,
                lambda.ArtifactLayout,
                lambda.ArtifactCodeUri,
                lambda.BootstrapMode,
                lambda.RuntimeIdentifier));
        }

        return routes.ToImmutable();
    }

    private static void EmitAccessor(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the generated Slice route descriptors for this assembly.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::System.ReadOnlySpan<SliceRouteDescriptor> GetSliceRoutesGenerated()");
        sb.AppendLine("        => s_routes;");
    }

    private static string? FindRequestType(
        FeatureModel feature,
        HashSet<string>? serializableTypes = null)
    {
        var bodyParameter = SourceGenerationHelpers.FindSingleBodyParameter(feature, serializableTypes);
        return bodyParameter is null
            ? null
            : SourceGenerationHelpers.TrimGlobalAlias(bodyParameter.TypeFqn);
    }

    private static (string Status, string? Reason) ClassifyPortability(
        FeatureModel feature,
        HashSet<string>? serializableTypes = null)
    {
        if (feature.ReturnsAspNetResult)
        {
            return (SourceGenerationHelpers.PortabilityAspNetOnly, "returns ASP.NET IResult");
        }

        if (feature.RequiresReflectionValidation)
        {
            return (SourceGenerationHelpers.PortabilityPartial, "DataAnnotations validation requires reflection in the WASI path");
        }

        // ASP.NET-only endpoint filters ([Filter<T>]) do not run on the WASI path.
        if (!feature.GetFilterFqns().IsEmpty)
        {
            return (SourceGenerationHelpers.PortabilityPartial, "endpoint filters do not run in the WASI path");
        }

        // Neutral filters ([SliceFilter<T>]) run on both paths, but only if the feature is not
        // already excluded from the WASI route table for other structural reasons.
        // WasiRegistrationEmitter.GetSkipReason covers IResult returns (already handled above),
        // reflection validation (already handled), and unsupported parameter shapes (SLICE023).
        // We mirror that check here so portability is accurate when filters are the only difference.
        if (!feature.GetSliceFilterFqns().IsEmpty)
        {
            // If the feature would be excluded from the WASI table for structural reasons
            // unrelated to filters (e.g., unsupported parameter binding — SLICE023), it is
            // still partial rather than portable, because the filter would never actually run.
            var skipReason = GetWasiStructuralSkipReason(feature, serializableTypes);
            if (skipReason is not null)
            {
                return (SourceGenerationHelpers.PortabilityPartial, skipReason);
            }
        }

        return (SourceGenerationHelpers.PortabilityPortable, null);
    }

    /// <summary>
    /// Returns the structural skip reason for a feature on the WASI path, excluding reasons
    /// already captured by <see cref="FeatureModel.ReturnsAspNetResult"/> and
    /// <see cref="FeatureModel.RequiresReflectionValidation"/> (handled above in the caller).
    /// Mirrors the relevant subset of <c>WasiRegistrationEmitter.GetSkipReason</c>.
    /// </summary>
    private static string? GetWasiStructuralSkipReason(
        FeatureModel feature,
        HashSet<string>? serializableTypes = null)
    {
        var selection = SourceGenerationHelpers.SelectBodyParameter(feature, serializableTypes);
        if (selection.AmbiguousWith is not null)
        {
            return "feature has multiple body parameters (SLICE023)";
        }

        foreach (var p in feature.GetParams())
        {
            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                continue;
            }

            var binding = SourceGenerationHelpers.ResolveParameterBinding(
                p,
                feature.Pattern,
                selection.Body);
            if (binding.Source == HandlerParameterBindingSource.Unsupported)
            {
                return binding.UnsupportedReason ?? "parameter binding is unsupported (SLICE023)";
            }
        }

        return null;
    }

    private static LambdaFunctionPerFeatureEligibility GetEmittedLambdaMetadata(
        FeatureModel feature,
        string assemblyName,
        bool emitLambdaFunctionPerFeatureHandlers,
        JsonContextPlan lambdaJsonContextPlan)
    {
        if (!emitLambdaFunctionPerFeatureHandlers)
        {
            return LambdaFunctionPerFeatureEligibility.NotEmitted;
        }

        return ClassifyLambdaFunctionPerFeature(
            feature,
            assemblyName,
            emitLambdaFunctionPerFeatureHandlers,
            lambdaJsonContextPlan,
            lambdaJsonContextPlan.GetSerializableTypesSet());
    }

    internal static LambdaFunctionPerFeatureEligibility ClassifyLambdaFunctionPerFeature(
        FeatureModel feature,
        string assemblyName,
        bool emitLambdaFunctionPerFeatureHandlers,
        JsonContextPlan lambdaJsonContextPlan,
        HashSet<string>? serializableTypes = null)
    {
        var reason = JsonContextPlanner.GetLambdaStructuralSkipReason(feature, serializableTypes)
            ?? JsonContextPlanner.FindExclusion(lambdaJsonContextPlan, feature)?.Reason;
        if (reason is not null)
        {
            return LambdaFunctionPerFeatureEligibility.Ineligible(reason);
        }

        if (!emitLambdaFunctionPerFeatureHandlers)
        {
            return new LambdaFunctionPerFeatureEligibility(SourceGenerationHelpers.ManifestEligible, null, null, null, null, null, null, null, null, null);
        }

        return new LambdaFunctionPerFeatureEligibility(
            SourceGenerationHelpers.ManifestEligible,
            null,
            assemblyName,
            $"SliceFx.{LambdaFunctionPerFeatureEmitter.HandlerTypeName(GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceLambdaFunctionPerFeatureHandlers"), feature)}",
            LambdaFunctionPerFeatureEmitter.HandlerMethodName(feature),
            SourceGenerationHelpers.ToLambdaArtifactId(feature.EndpointName),
            "per-feature",
            "artifacts/" + SourceGenerationHelpers.ToLambdaArtifactId(feature.EndpointName),
            "native-aot-bootstrap",
            null);
    }

    private static string FilterTypesLiteral(FeatureModel feature)
    {
        var filters = feature.GetFilterFqns();
        if (filters.IsEmpty)
        {
            return "global::System.Array.Empty<string>()";
        }

        var values = filters
            .Select(static f => CSharpLiteral.String(SourceGenerationHelpers.TrimGlobalAlias(f)));
        return $"new[] {{ {string.Join(", ", values)} }}";
    }

    private static string? SerializeFilterTypes(FeatureModel feature)
    {
        var filters = feature.GetFilterFqns();
        return filters.IsEmpty
            ? null
            : string.Join("\n", filters.Select(static f => SourceGenerationHelpers.TrimGlobalAlias(f)));
    }

    private static string? SerializeSliceFilterTypes(FeatureModel feature)
    {
        var filters = feature.GetSliceFilterFqns();
        return filters.IsEmpty
            ? null
            : string.Join("\n", filters.Select(static f => SourceGenerationHelpers.TrimGlobalAlias(f)));
    }

    private static string? SerializeParameters(FeatureModel feature)
    {
        var parameters = feature.GetParams();
        return parameters.IsEmpty
            ? null
            : string.Join("\n", parameters.Select(static p =>
                $"{EncodeManifestField(SourceGenerationHelpers.TrimGlobalAlias(p.TypeFqn))}|{EncodeManifestField(p.Name)}|{(p.IsNullable ? "N" : "-")}|{EncodeManifestField(p.BindingSource ?? "")}|{EncodeManifestField(p.BindingName ?? "")}|{EncodeManifestField(p.BindingKeyLiteral ?? "")}"));
    }

    /// <summary>
    /// Builds a union of all serializable types from both the WASI and Lambda JSON context plans.
    /// Used as the compile-time body/service discriminator for manifest RequestType computation:
    /// if a type is registered in *either* context it qualifies as a body param in the manifest.
    /// Returns null when both plans have empty sets (avoids allocating an empty HashSet).
    /// </summary>
    private static HashSet<string>? BuildUnionSerializableTypes(
        JsonContextPlan wasiPlan,
        JsonContextPlan lambdaPlan)
    {
        var wasiTypes = wasiPlan.GetSerializableTypesSet();
        var lambdaTypes = lambdaPlan.GetSerializableTypesSet();
        if (wasiTypes.Count == 0 && lambdaTypes.Count == 0)
        {
            return null;
        }

        var union = new HashSet<string>(wasiTypes, StringComparer.Ordinal);
        union.UnionWith(lambdaTypes);
        return union;
    }

    private static string EncodeManifestField(string value)
        => Convert.ToBase64String(Encoding.UTF8.GetBytes(value));

    private static string BoolLiteral(bool value) => value ? "true" : "false";

    private static string CSharpNullableStringLiteral(string? value)
        => value is null ? "null" : CSharpLiteral.String(value);
}

internal readonly record struct RouteManifestEntry(
    FeatureModel Feature,
    string Portability,
    string? PortabilityReason,
    string WasiStatus,
    string? WasiReason,
    string? LambdaStatus,
    string? LambdaReason,
    string? LambdaHandlerAssembly,
    string? LambdaHandlerType,
    string? LambdaHandlerMethod,
    string? LambdaArtifactId,
    string? LambdaArtifactLayout,
    string? LambdaArtifactCodeUri,
    string? LambdaBootstrapMode,
    string? LambdaRuntimeIdentifier);

internal readonly record struct LambdaFunctionPerFeatureEligibility(
    string? Status,
    string? Reason,
    string? HandlerAssembly,
    string? HandlerType,
    string? HandlerMethod,
    string? ArtifactId,
    string? ArtifactLayout,
    string? ArtifactCodeUri,
    string? BootstrapMode,
    string? RuntimeIdentifier)
{
    internal static LambdaFunctionPerFeatureEligibility NotEmitted { get; } = new(null, null, null, null, null, null, null, null, null, null);

    internal static LambdaFunctionPerFeatureEligibility Ineligible(string reason)
        => new(SourceGenerationHelpers.ManifestIneligible, reason, null, null, null, null, null, null, null, null);
}
