using System.Collections.Immutable;
using System.Text;

namespace SliceFx.SourceGenerator;

internal static class WasiRegistrationEmitter
{
    /// <summary>
    /// Emits Slice WASI registration source for the specified feature models.
    /// </summary>
    /// <param name="features">The feature models to include in generated registrations.</param>
    /// <param name="validators">The validator models to include in generated service registrations.</param>
    /// <param name="assemblyName">The target assembly name used to form the generated class name.</param>
    /// <param name="jsonContextPlan">The JSON source-generation context plan for WASI dispatch.</param>
    /// <param name="referencedModules">The referenced Slice modules to aggregate from user-facing extension methods.</param>
    /// <param name="emitExtensions">Whether to emit the user-facing WASI extension method for this compilation.</param>
    /// <returns>The generated C# source and any diagnostics produced while emitting it.</returns>
    public static (string Source, ImmutableArray<EquatableDiagnostic> Diagnostics) Emit(
        ImmutableArray<FeatureModel> features,
        ImmutableArray<ValidatorModel> validators,
        string assemblyName,
        JsonContextPlan jsonContextPlan,
        ImmutableArray<ReferencedSliceModule> referencedModules,
        bool emitExtensions)
    {
        var className = GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceWasiRegistrations");
        var sb = new StringBuilder();
        var diagnostics = ImmutableArray.CreateBuilder<EquatableDiagnostic>();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using global::SliceFx.Wasi;");
        sb.AppendLine("using global::SliceFx.Wasi.Binding;");
        sb.AppendLine("using global::SliceFx.Wasi.Routing;");
        sb.AppendLine("using global::SliceFx.Wasi.Validation;");
        if (!features.IsEmpty || !validators.IsEmpty)
        {
            sb.AppendLine();
            sb.AppendLine($"[assembly: global::SliceFx.SliceFeatureModuleAttribute(typeof(global::SliceFx.{className}))]");
        }

        sb.AppendLine();
        sb.AppendLine("namespace SliceFx;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides generated Slice WASI route registration infrastructure.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers this generated Slice WASI route module with the host builder.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"builder\">The WASI host builder to configure.</param>");
        sb.AppendLine("    /// <returns>The same WASI host builder for chaining.</returns>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::SliceFx.Wasi.WasiHostBuilder AddSliceWasiRoutes(");
        sb.AppendLine("        global::SliceFx.Wasi.WasiHostBuilder builder)");
        sb.AppendLine("    {");
        EmitWasiServiceRegistrations(sb, validators);
        sb.AppendLine("        builder.AddRoutes(RegisterWasiRoutes);");
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();

        if (emitExtensions)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Registers generated Slice WASI routes with the host builder.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    /// <param name=\"builder\">The WASI host builder to configure.</param>");
            sb.AppendLine("    /// <returns>The same WASI host builder for chaining.</returns>");
            sb.AppendLine("    public static global::SliceFx.Wasi.WasiHostBuilder AddSlice(");
            sb.AppendLine("        this global::SliceFx.Wasi.WasiHostBuilder builder)");
            sb.AppendLine("    {");
            sb.AppendLine($"        global::SliceFx.{className}.AddSliceWasiRoutes(builder);");
            foreach (var module in referencedModules)
            {
                if (module.HasWasiRoutes)
                {
                    sb.AppendLine($"        {module.RegistrationTypeFqn}.AddSliceWasiRoutes(builder);");
                }
            }

            sb.AppendLine("        return builder;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        var wasiJsonContextFqn = jsonContextPlan.ContextFqn;
        if (wasiJsonContextFqn is not null)
        {
            EmitJsonTypeInfoHelper(sb, wasiJsonContextFqn);
            sb.AppendLine();
        }

        // RegisterWasiRoutes
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers generated Slice WASI routes in the route table.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"table\">The WASI route table to populate.</param>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static void RegisterWasiRoutes(global::SliceFx.Wasi.Routing.WasiRouteTable table)");
        sb.AppendLine("    {");

        foreach (var f in features)
        {
            var jsonExclusion = JsonContextPlanner.FindExclusion(jsonContextPlan, f);
            var skipReason = GetSkipReason(f);
            var skipMessage = skipReason?.Reason ?? jsonExclusion?.Reason;
            if (skipMessage is not null)
            {
                if (f.ReturnsAspNetResult)
                {
                    diagnostics.Add(EquatableDiagnostic.Create(
                        SliceDiagnostics.UnsupportedReturnTypeForWasi,
                        DiagnosticLocationModel.None,
                        f.TypeName,
                        f.ReturnTypeFqn));
                    sb.AppendLine($"        // SLICE008: {ToSingleLineComment(f.EndpointName)} — return type '{f.ReturnTypeFqn}' not supported in WASI; skipped.");
                }
                else if (jsonExclusion is not null)
                {
                    sb.AppendLine($"        // SLICE009: {ToSingleLineComment(f.EndpointName)} — {skipMessage}; skipped.");
                }
                else if (skipReason?.DiagnosticId == "SLICE023")
                {
                    diagnostics.Add(EquatableDiagnostic.Create(
                        SliceDiagnostics.UnsupportedParameterForWasi,
                        f.GetDiagnosticLocationModel(),
                        f.TypeName,
                        skipReason.Value.ParameterName ?? "",
                        skipReason.Value.ParameterType ?? ""));
                    sb.AppendLine($"        // SLICE023: {ToSingleLineComment(f.EndpointName)} — {skipMessage}; skipped.");
                }
                else
                {
                    diagnostics.Add(EquatableDiagnostic.Create(
                        SliceDiagnostics.UnsupportedValidationForWasi,
                        f.GetDiagnosticLocationModel(),
                        f.TypeName));
                    sb.AppendLine($"        // SLICE011: {ToSingleLineComment(f.EndpointName)} — {skipMessage}; skipped.");
                }

                continue;
            }

            sb.AppendLine($"        // {ToSingleLineComment(f.EndpointName)}");
            EmitTableAdd(sb, f, validators, wasiJsonContextFqn);
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        EmitValidationHelpers(sb, features);
        sb.AppendLine("}");

        return (sb.ToString(), diagnostics.ToImmutable());
    }

    private static WasiSkipReason? GetSkipReason(FeatureModel feature)
    {
        if (feature.ReturnsAspNetResult)
        {
            return new WasiSkipReason("SLICE008", "IResult is ASP.NET-specific");
        }

        if (feature.RequiresReflectionValidation)
        {
            return new WasiSkipReason("SLICE011", "DataAnnotations validation requires reflection");
        }

        var bodyCount = 0;
        foreach (var p in feature.GetParams())
        {
            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                continue;
            }

            var binding = SourceGenerationHelpers.ResolveParameterBinding(p, feature.Pattern, feature.FullyQualifiedTypeName);
            if (binding.Source == HandlerParameterBindingSource.Body)
            {
                bodyCount++;
                if (bodyCount > 1)
                {
                    return new WasiSkipReason(
                        "SLICE023",
                        "multiple body parameters are not supported",
                        p.Name,
                        SourceGenerationHelpers.TrimGlobalAlias(p.TypeFqn));
                }
            }

            if (binding.Source == HandlerParameterBindingSource.Unsupported)
            {
                return new WasiSkipReason(
                    "SLICE023",
                    binding.UnsupportedReason ?? "parameter binding is unsupported",
                    p.Name,
                    SourceGenerationHelpers.TrimGlobalAlias(p.TypeFqn));
            }
        }

        return null;
    }

    private static void EmitWasiServiceRegistrations(StringBuilder sb, ImmutableArray<ValidatorModel> validators)
    {
        foreach (var validator in validators)
        {
            sb.AppendLine($"        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::SliceFx.ISliceValidator<{validator.RequestTypeFqn}>, {validator.ImplementationTypeFqn}>(builder.Services);");
        }
    }

    private static void EmitTableAdd(
        StringBuilder sb,
        FeatureModel f,
        ImmutableArray<ValidatorModel> validators,
        string? wasiJsonContextFqn)
    {
        var @params = f.GetParams();

        var bodyParam = FindBodyParam(f, @params);

        sb.AppendLine($"        table.Add(");
        sb.AppendLine($"            {Str(f.HttpMethod)},");
        sb.AppendLine($"            {Str(f.Pattern)},");
        sb.AppendLine($"            static sp =>");
        sb.AppendLine($"            {{");
        sb.AppendLine($"                return async ctx =>");
        sb.AppendLine($"                {{");

        // 1. Body binding + null check + DataAnnotations
        if (bodyParam is not null)
        {
            sb.AppendLine($"                    {bodyParam.TypeFqn}? {bodyParam.Name};");
            sb.AppendLine("                    try");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        {bodyParam.Name} = await global::SliceFx.Wasi.Binding.JsonBodyReader");
            sb.AppendLine($"                            .ReadAsync<{bodyParam.TypeFqn}>(ctx, __JsonTypeInfo<{bodyParam.TypeFqn}>());");
            sb.AppendLine("                    }");
            sb.AppendLine("                    catch (global::System.Text.Json.JsonException)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        return global::SliceFx.Wasi.SliceResult.Problem(400, \"Bad Request\", \"Request body contains malformed JSON.\");");
            sb.AppendLine("                    }");
            sb.AppendLine($"                    if ({bodyParam.Name} is null) return global::SliceFx.Wasi.SliceResult.Problem(400, \"Bad Request\", \"Request body is required.\");");

            if (ShouldUseGeneratedValidation(f))
            {
                sb.AppendLine($"                    var __daErrors = {ValidationMethodName(f)}({bodyParam.Name});");
                sb.AppendLine($"                    if (__daErrors is not null) return global::SliceFx.Wasi.SliceResult.ValidationProblem(__daErrors);");
            }

            if (HasValidatorForParameter(bodyParam, validators))
            {
                sb.AppendLine($"                    var __validator = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<global::SliceFx.ISliceValidator<{bodyParam.TypeFqn}>>(ctx.Services);");
                sb.AppendLine("                    if (__validator is not null)");
                sb.AppendLine("                    {");
                sb.AppendLine($"                        var __vr = await __validator.ValidateAsync({bodyParam.Name}, ctx.CancellationToken);");
                sb.AppendLine($"                        if (!__vr.IsValid) return global::SliceFx.Wasi.SliceResult.ValidationProblem(__vr.Errors!);");
                sb.AppendLine("                    }");
            }
        }

        // 2. Route / query / DI param bindings
        foreach (var p in @params)
        {
            if (p == bodyParam)
            {
                continue;
            }

            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                continue;
            }

            var binding = SourceGenerationHelpers.ResolveParameterBinding(p, f.Pattern, f.FullyQualifiedTypeName);
            if (binding.Source == HandlerParameterBindingSource.Route)
            {
                sb.AppendLine($"                    if (!global::SliceFx.Wasi.Binding.WasiArgumentBinder");
                sb.AppendLine($"                        .TryGetFromRoute<{p.TypeFqn}>(ctx, {Str(binding.WireName)}, out var {p.Name}))");
                sb.AppendLine($"                        return global::SliceFx.Wasi.SliceResult.Problem(400, \"Bad Request\", {Str($"Route value '{binding.WireName}' is missing or invalid.")});");
            }
            else if (binding.Source == HandlerParameterBindingSource.Query)
            {
                var bindingVariable = "__" + p.Name + "Query";
                sb.AppendLine($"                    var {bindingVariable} = global::SliceFx.Wasi.Binding.WasiArgumentBinder");
                sb.AppendLine($"                        .BindFromQuery<{p.TypeFqn}>(ctx, {Str(binding.WireName)});");
                sb.AppendLine($"                    if ({bindingVariable}.Status == global::SliceFx.Wasi.Binding.WasiArgumentBindingStatus.Invalid)");
                sb.AppendLine($"                        return global::SliceFx.Wasi.SliceResult.Problem(400, \"Bad Request\", {Str($"Query value '{binding.WireName}' is invalid.")});");
                if (!p.IsNullable)
                {
                    sb.AppendLine($"                    if ({bindingVariable}.Status == global::SliceFx.Wasi.Binding.WasiArgumentBindingStatus.Missing)");
                    sb.AppendLine($"                        return global::SliceFx.Wasi.SliceResult.Problem(400, \"Bad Request\", {Str($"Query value '{binding.WireName}' is missing.")});");
                }
                sb.AppendLine($"                    var {p.Name} = {bindingVariable}.Value!;");
            }
            else if (binding.Source == HandlerParameterBindingSource.Header)
            {
                var bindingVariable = "__" + p.Name + "Header";
                sb.AppendLine($"                    var {bindingVariable} = global::SliceFx.Wasi.Binding.WasiArgumentBinder");
                sb.AppendLine($"                        .BindFromHeader<{p.TypeFqn}>(ctx, {Str(binding.WireName)});");
                sb.AppendLine($"                    if ({bindingVariable}.Status == global::SliceFx.Wasi.Binding.WasiArgumentBindingStatus.Invalid)");
                sb.AppendLine($"                        return global::SliceFx.Wasi.SliceResult.Problem(400, \"Bad Request\", {Str($"Header value '{binding.WireName}' is invalid.")});");
                if (!p.IsNullable)
                {
                    sb.AppendLine($"                    if ({bindingVariable}.Status == global::SliceFx.Wasi.Binding.WasiArgumentBindingStatus.Missing)");
                    sb.AppendLine($"                        return global::SliceFx.Wasi.SliceResult.Problem(400, \"Bad Request\", {Str($"Header value '{binding.WireName}' is missing.")});");
                }
                sb.AppendLine($"                    var {p.Name} = {bindingVariable}.Value!;");
            }
            else // DI
            {
                sb.AppendLine($"                    var {p.Name} = ({p.TypeFqn})ctx.Services.GetRequiredService(typeof({p.TypeFqn}));");
            }
        }

        // 3. Build call args
        var argList = new List<string>(@params.Length);
        foreach (var p in @params)
        {
            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                argList.Add("ctx.CancellationToken");
            }
            else
            {
                argList.Add(p.Name);
            }
        }

        var callExpr = $"{f.FullyQualifiedTypeName}.Handle({string.Join(", ", argList)})";
        if (f.ReturnTypeFqn == "void")
        {
            sb.AppendLine($"                    {callExpr};");
            sb.AppendLine($"                    return global::SliceFx.Wasi.SliceResult.NoContent();");
        }
        else if (SourceGenerationHelpers.IsNonGenericAwaitable(f.ReturnTypeFqn))
        {
            sb.AppendLine($"                    await {callExpr};");
            sb.AppendLine($"                    return global::SliceFx.Wasi.SliceResult.NoContent();");
        }
        else
        {
            if (SourceGenerationHelpers.IsGenericAwaitable(f.ReturnTypeFqn))
            {
                sb.AppendLine($"                    var __result = await {callExpr};");
            }
            else
            {
                sb.AppendLine($"                    var __result = {callExpr};");
            }

            if (IsWasiResponseType(SourceGenerationHelpers.GetAwaitedReturnType(f.ReturnTypeFqn)))
            {
                sb.AppendLine($"                    return __result;");
            }
            else
            {
                var resultType = SourceGenerationHelpers.GetAwaitedReturnType(f.ReturnTypeFqn);
                if (wasiJsonContextFqn is not null)
                {
                    sb.AppendLine($"                    return global::SliceFx.Wasi.SliceResult.Ok<{resultType}>(__result, __JsonTypeInfo<{resultType}>());");
                }
                else
                {
                    sb.AppendLine($"                    return global::SliceFx.Wasi.SliceResult.Ok(__result);");
                }
            }
        }

        sb.AppendLine($"                }};");
        sb.AppendLine($"            }});");
    }

    private static bool ShouldUseGeneratedValidation(FeatureModel f)
        => !f.RequiresReflectionValidation && !string.IsNullOrEmpty(f.SerializedValidationRules);

    private static void EmitValidationMethod(StringBuilder sb, FeatureModel f)
    {
        var requestType = f.FullyQualifiedTypeName + ".Request";
        sb.AppendLine($"    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? {ValidationMethodName(f)}({requestType} value)");
        sb.AppendLine("    {");
        sb.AppendLine("        var errors = new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>(global::System.StringComparer.Ordinal);");

        foreach (var line in f.SerializedValidationRules.Split('\n'))
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }

            var parts = line.Split('|');
            if (parts.Length < 2)
            {
                continue;
            }

            var propertyName = parts[0];
            var propertyAccess = $"value.{propertyName}";
            var localName = "__" + SanitizeIdentifier(propertyName);
            if (parts[1] == "Required")
            {
                var allowEmptyStrings = parts.Length > 2 && parts[2] == "true";
                var message = DecodeValidationMessage(parts, 3, $"The {propertyName} field is required.");
                if (allowEmptyStrings)
                {
                    sb.AppendLine($"        if ({propertyAccess} is null)");
                }
                else
                {
                    sb.AppendLine($"        if ({propertyAccess} is null || ({propertyAccess} is string {localName}Required && {localName}Required.Length == 0))");
                }
                sb.AppendLine("        {");
                sb.AppendLine($"            __AddValidationError(errors, {Str(propertyName)}, {Str(message)});");
                sb.AppendLine("        }");
            }
            else if (parts[1] == "StringLength" && parts.Length > 3)
            {
                var message = DecodeValidationMessage(parts, 4, $"The field {propertyName} must be a string with a minimum length of {parts[2]} and a maximum length of {parts[3]}.");
                sb.AppendLine($"        if ({propertyAccess} is string {localName}StringLength && ({localName}StringLength.Length < {parts[2]} || {localName}StringLength.Length > {parts[3]}))");
                sb.AppendLine("        {");
                sb.AppendLine($"            __AddValidationError(errors, {Str(propertyName)}, {Str(message)});");
                sb.AppendLine("        }");
            }
            else if (parts[1] == "MinLength" && parts.Length > 2)
            {
                var lengthMember = parts.Length > 3 ? parts[3] : "Length";
                var message = DecodeValidationMessage(parts, 4, $"The field {propertyName} must be a string or array type with a minimum length of '{parts[2]}'.");
                sb.AppendLine($"        if ({propertyAccess} is not null && {propertyAccess}.{lengthMember} < {parts[2]})");
                sb.AppendLine("        {");
                sb.AppendLine($"            __AddValidationError(errors, {Str(propertyName)}, {Str(message)});");
                sb.AppendLine("        }");
            }
        }

        sb.AppendLine();
        sb.AppendLine("        return __ToValidationErrors(errors);");
        sb.AppendLine("    }");
    }

    private static void EmitValidationHelpers(StringBuilder sb, ImmutableArray<FeatureModel> features)
    {
        var emittedAny = false;
        foreach (var f in features)
        {
            if (!ShouldUseGeneratedValidation(f))
            {
                continue;
            }

            if (!emittedAny)
            {
                emittedAny = true;
                sb.AppendLine();
            }

            EmitValidationMethod(sb, f);
            sb.AppendLine();
        }

        if (!emittedAny)
        {
            return;
        }

        sb.AppendLine("    private static void __AddValidationError(global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>> errors, string key, string message)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!errors.TryGetValue(key, out var messages))");
        sb.AppendLine("        {");
        sb.AppendLine("            messages = [];");
        sb.AppendLine("            errors.Add(key, messages);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        messages.Add(message);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? __ToValidationErrors(global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>> errors)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (errors.Count == 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var result = new global::System.Collections.Generic.Dictionary<string, string[]>(global::System.StringComparer.Ordinal);");
        sb.AppendLine("        foreach (var entry in errors)");
        sb.AppendLine("        {");
        sb.AppendLine("            result.Add(entry.Key, entry.Value.ToArray());");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private static string ValidationMethodName(FeatureModel f)
        => "__Validate_" + SanitizeIdentifier(f.FullyQualifiedTypeName);

    private static string DecodeValidationMessage(string[] parts, int index, string fallback)
    {
        if (parts.Length <= index)
        {
            return fallback;
        }

        return Encoding.UTF8.GetString(Convert.FromBase64String(parts[index]));
    }

    private static string SanitizeIdentifier(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        return sb.ToString();
    }

    private static void EmitJsonTypeInfoHelper(StringBuilder sb, string wasiJsonContextFqn)
    {
        sb.AppendLine("    private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T> __JsonTypeInfo<T>()");
        sb.AppendLine($"        => (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T>){wasiJsonContextFqn}.Default.GetTypeInfo(typeof(T))!;");
    }

    private static HandleParamModel? FindBodyParam(FeatureModel feature, ImmutableArray<HandleParamModel> @params)
    {
        foreach (var p in @params)
        {
            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                continue;
            }

            var binding = SourceGenerationHelpers.ResolveParameterBinding(p, feature.Pattern, feature.FullyQualifiedTypeName);
            if (binding.Source == HandlerParameterBindingSource.Body)
            {
                return p;
            }
        }
        return null;
    }

    private static bool HasValidatorForParameter(
        HandleParamModel parameter,
        ImmutableArray<ValidatorModel> validators)
        => validators.Any(validator => validator.RequestTypeFqn == parameter.TypeFqn);

    private static bool IsWasiResponseType(string? typeFqn)
        => SourceGenerationHelpers.IsWasiResponseType(typeFqn);

    private static string Str(string value) => CSharpLiteral.String(value);

    private static string ToSingleLineComment(string value)
        => value.Replace('\r', ' ').Replace('\n', ' ');

    private readonly record struct WasiSkipReason(
        string DiagnosticId,
        string Reason,
        string? ParameterName = null,
        string? ParameterType = null);
}
