using System.Collections.Immutable;
using System.Text;

namespace SliceFx.SourceGenerator;

internal static class WasiRegistrationEmitter
{
    /// <summary>
    /// Emits Slice WASI registration source for the specified feature models.
    /// </summary>
    /// <param name="features">The feature models to include in generated registrations.</param>
    /// <param name="validators">The validator models to include in generated service registrations.</param>
    /// <param name="assemblyName">The target assembly name used to form the generated class name.</param>
    /// <param name="jsonContextPlan">The JSON source-generation context plan for WASI dispatch.</param>
    /// <param name="referencedModules">The referenced Slice modules to aggregate from user-facing extension methods.</param>
    /// <param name="emitExtensions">Whether to emit the user-facing WASI extension method for this compilation.</param>
    /// <returns>The generated C# source and any diagnostics produced while emitting it.</returns>
    public static (string Source, ImmutableArray<EquatableDiagnostic> Diagnostics) Emit(
        ImmutableArray<FeatureModel> features,
        ImmutableArray<ValidatorModel> validators,
        string assemblyName,
        JsonContextPlan jsonContextPlan,
        ImmutableArray<ReferencedSliceModule> referencedModules,
        bool emitExtensions)
    {
        var className = GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceWasiRegistrations");
        var sb = new StringBuilder();
        var diagnostics = ImmutableArray.CreateBuilder<EquatableDiagnostic>();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using global::SliceFx.Wasi;");
        sb.AppendLine("using global::SliceFx.Wasi.Binding;");
        sb.AppendLine("using global::SliceFx.Wasi.Routing;");
        if (!features.IsEmpty || !validators.IsEmpty)
        {
            sb.AppendLine();
            sb.AppendLine($"[assembly: global::SliceFx.SliceFeatureModuleAttribute(typeof(global::SliceFx.{className}))]");
        }

        sb.AppendLine();
        sb.AppendLine("namespace SliceFx;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides generated Slice WASI route registration infrastructure.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers this generated Slice WASI route module with the host builder.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"builder\">The WASI host builder to configure.</param>");
        sb.AppendLine("    /// <returns>The same WASI host builder for chaining.</returns>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::SliceFx.Wasi.WasiHostBuilder AddSliceWasiRoutes(");
        sb.AppendLine("        global::SliceFx.Wasi.WasiHostBuilder builder)");
        sb.AppendLine("    {");
        EmitWasiServiceRegistrations(sb, validators, features);
        sb.AppendLine("        builder.AddRoutes(RegisterWasiRoutes);");
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();

        if (emitExtensions)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Registers generated Slice WASI routes with the host builder.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    /// <param name=\"builder\">The WASI host builder to configure.</param>");
            sb.AppendLine("    /// <returns>The same WASI host builder for chaining.</returns>");
            sb.AppendLine("    public static global::SliceFx.Wasi.WasiHostBuilder AddSlice(");
            sb.AppendLine("        this global::SliceFx.Wasi.WasiHostBuilder builder)");
            sb.AppendLine("    {");
            sb.AppendLine($"        global::SliceFx.{className}.AddSliceWasiRoutes(builder);");
            foreach (var module in referencedModules)
            {
                if (module.HasWasiRoutes)
                {
                    sb.AppendLine($"        {module.RegistrationTypeFqn}.AddSliceWasiRoutes(builder);");
                }
            }

            sb.AppendLine("        return builder;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        var wasiJsonContextFqn = jsonContextPlan.ContextFqn;
        if (wasiJsonContextFqn is not null)
        {
            EmitJsonTypeInfoHelper(sb, wasiJsonContextFqn);
            sb.AppendLine();
        }

        // RegisterWasiRoutes
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers generated Slice WASI routes in the route table.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"table\">The WASI route table to populate.</param>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static void RegisterWasiRoutes(global::SliceFx.Wasi.Routing.WasiRouteTable table)");
        sb.AppendLine("    {");

        // Build the serializable-type set once; used for body/service disambiguation in all per-feature loops.
        var wasiSerializableTypes = jsonContextPlan.GetSerializableTypesSet();

        foreach (var f in features)
        {
            var jsonExclusion = JsonContextPlanner.FindExclusion(jsonContextPlan, f);
            var skipReason = GetSkipReason(f, wasiSerializableTypes);
            var skipMessage = skipReason?.Reason ?? jsonExclusion?.Reason;
            if (skipMessage is not null)
            {
                if (f.ReturnsAspNetResult)
                {
                    diagnostics.Add(EquatableDiagnostic.Create(
                        SliceDiagnostics.UnsupportedReturnTypeForWasi,
                        DiagnosticLocationModel.None,
                        f.TypeName,
                        f.ReturnTypeFqn));
                    sb.AppendLine($"        // SLICE020: {ToSingleLineComment(f.EndpointName)} — return type '{f.ReturnTypeFqn}' not supported in WASI; skipped.");
                }
                else if (jsonExclusion is not null)
                {
                    sb.AppendLine($"        // SLICE021: {ToSingleLineComment(f.EndpointName)} — {skipMessage}; skipped.");
                }
                else if (skipReason?.DiagnosticId == "SLICE023")
                {
                    diagnostics.Add(EquatableDiagnostic.Create(
                        SliceDiagnostics.UnsupportedParameterForWasi,
                        f.GetDiagnosticLocationModel(),
                        f.TypeName,
                        skipReason.Value.ParameterName ?? "",
                        skipReason.Value.ParameterType ?? ""));
                    sb.AppendLine($"        // SLICE023: {ToSingleLineComment(f.EndpointName)} — {skipMessage}; skipped.");
                }
                else
                {
                    diagnostics.Add(EquatableDiagnostic.Create(
                        SliceDiagnostics.UnsupportedValidationForWasi,
                        f.GetDiagnosticLocationModel(),
                        f.TypeName));
                    sb.AppendLine($"        // SLICE022: {ToSingleLineComment(f.EndpointName)} — {skipMessage}; skipped.");
                }

                continue;
            }

            sb.AppendLine($"        // {ToSingleLineComment(f.EndpointName)}");
            EmitTableAdd(sb, f, validators, wasiSerializableTypes);
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        EmitValidationHelpers(sb, features);
        sb.AppendLine("}");

        return (sb.ToString(), diagnostics.ToImmutable());
    }

    private static WasiSkipReason? GetSkipReason(
        FeatureModel feature,
        HashSet<string>? serializableTypes = null)
    {
        if (feature.ReturnsAspNetResult)
        {
            return new WasiSkipReason("SLICE020", "IResult is ASP.NET-specific");
        }

        if (feature.RequiresReflectionValidation)
        {
            return new WasiSkipReason("SLICE022", "DataAnnotations validation requires reflection");
        }

        var bodyCount = 0;
        foreach (var p in feature.GetParams())
        {
            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                continue;
            }

            var binding = SourceGenerationHelpers.ResolveParameterBinding(
                p,
                feature.HttpMethod,
                feature.Pattern,
                serializableTypes);
            if (binding.Source == HandlerParameterBindingSource.Body)
            {
                bodyCount++;
                if (bodyCount > 1)
                {
                    return new WasiSkipReason(
                        "SLICE023",
                        "multiple body parameters are not supported",
                        p.Name,
                        SourceGenerationHelpers.TrimGlobalAlias(p.TypeFqn));
                }
            }

            if (binding.Source == HandlerParameterBindingSource.Unsupported)
            {
                return new WasiSkipReason(
                    "SLICE023",
                    binding.UnsupportedReason ?? "parameter binding is unsupported",
                    p.Name,
                    SourceGenerationHelpers.TrimGlobalAlias(p.TypeFqn));
            }
        }

        return null;
    }

    private static void EmitWasiServiceRegistrations(
        StringBuilder sb,
        ImmutableArray<ValidatorModel> validators,
        ImmutableArray<FeatureModel> features)
    {
        foreach (var validator in validators)
        {
            sb.AppendLine($"        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::SliceFx.ISliceValidator<{validator.RequestTypeFqn}>, {validator.ImplementationTypeFqn}>(builder.Services);");
        }

        // Register neutral filter types (ISliceFilter) as scoped — must be done on the WASI path
        // because the WASI invoker resolves them via ctx.Services.GetRequiredService<T>().
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var feature in features)
        {
            foreach (var ft in feature.GetSliceFilterFqns())
            {
                if (seen.Add(ft))
                {
                    sb.AppendLine($"        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<{ft}>(builder.Services);");
                }
            }
        }
    }

    private static void EmitTableAdd(
        StringBuilder sb,
        FeatureModel f,
        ImmutableArray<ValidatorModel> validators,
        HashSet<string>? serializableTypes = null)
    {
        var @params = f.GetParams();
        var bodyParam = FindBodyParam(f, serializableTypes);
        var bodyValidation = bodyParam is null ? null : FindValidationParameter(f, @params.IndexOf(bodyParam));
        var sliceFilters = f.GetSliceFilterFqns();

        // When neutral filters are present the handler body is wrapped in a SliceFilterDelegate
        // local variable (__handlerCore) so the filter chain can intercept it. When no neutral
        // filters are present we emit the same code as before — zero overhead, no branching at runtime.
        var hasFilters = !sliceFilters.IsEmpty;
        // Suffix appended to every WasiResponse return inside the handler core when filters are present.
        var wrap = hasFilters ? ".ToSliceFilterResult()" : "";
        // Body indent: 20 spaces for no-filter case (inside return async ctx =>),
        //              24 spaces for filter case (inside __handlerCore = async __ => { ... }).
        var ind = hasFilters ? "                        " : "                    ";

        sb.AppendLine($"        table.Add(");
        sb.AppendLine($"            {Str(f.HttpMethod)},");
        sb.AppendLine($"            {Str(f.Pattern)},");
        sb.AppendLine($"            static sp =>");
        sb.AppendLine($"            {{");
        sb.AppendLine($"                return async ctx =>");
        sb.AppendLine($"                {{");

        if (hasFilters)
        {
            // Resolve neutral filter instances (scoped, per-request via ctx.Services).
            for (var i = 0; i < sliceFilters.Length; i++)
            {
                sb.AppendLine($"                    var __sliceFilter{i} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{sliceFilters[i]}>(ctx.Services);");
            }

            // Build neutral filter context from the WASI invoker context.
            sb.AppendLine("                    var __sliceFilterCtx = new global::SliceFx.SliceFilterContext(");
            sb.AppendLine("                        ctx.Request.Method,");
            sb.AppendLine("                        ctx.Request.Path,");
            sb.AppendLine("                        ctx.Request.Headers,");
            sb.AppendLine("                        ctx.RouteValues,");
            sb.AppendLine("                        ctx.Services,");
            sb.AppendLine("                        ctx.CancellationToken);");
            sb.AppendLine();

            // Begin handler-core delegate. It captures the outer `ctx` for body binding;
            // the SliceFilterContext parameter (__) is unused inside the WASI handler.
            sb.AppendLine("                    global::SliceFx.SliceFilterDelegate __handlerCore = async __ =>");
            sb.AppendLine("                    {");
        }

        // 1. Body binding + null check + DataAnnotations
        if (bodyParam is not null)
        {
            var bodyTargetName = bodyParam.Name;
            var bodyReadName = bodyParam.IsValueType && !bodyParam.IsNullable ? "__" + bodyParam.Name + "Body" : bodyParam.Name;
            sb.AppendLine($"{ind}{bodyParam.TypeFqn}? {bodyReadName};");
            sb.AppendLine($"{ind}try");
            sb.AppendLine($"{ind}{{");
            sb.AppendLine($"{ind}    {bodyReadName} = await global::SliceFx.Wasi.Binding.JsonBodyReader");
            sb.AppendLine($"{ind}        .ReadAsync<{bodyParam.TypeFqn}>(ctx, __JsonTypeInfo<{bodyParam.TypeFqn}>());");
            sb.AppendLine($"{ind}}}");
            sb.AppendLine($"{ind}catch (global::System.Text.Json.JsonException)");
            sb.AppendLine($"{ind}{{");
            sb.AppendLine($"{ind}    return global::SliceFx.Wasi.WasiResults.Problem(400, \"Bad Request\", \"Request body contains malformed JSON.\"){wrap};");
            sb.AppendLine($"{ind}}}");
            sb.AppendLine($"{ind}if ({bodyReadName} is null) return global::SliceFx.Wasi.WasiResults.Problem(400, \"Bad Request\", \"Request body is required.\"){wrap};");
            if (bodyReadName != bodyTargetName)
            {
                sb.AppendLine($"{ind}var {bodyTargetName} = {bodyReadName}.Value;");
            }

            if (bodyValidation is not null)
            {
                sb.AppendLine($"{ind}var __daErrors = {ValidationMethodName(f, bodyValidation.Value)}({bodyParam.Name});");
                sb.AppendLine($"{ind}if (__daErrors is not null) return global::SliceFx.Wasi.WasiResults.ValidationProblem(__daErrors){wrap};");
            }

            if (HasValidatorForParameter(bodyParam, validators))
            {
                sb.AppendLine($"{ind}var __validator = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<global::SliceFx.ISliceValidator<{bodyParam.TypeFqn}>>(ctx.Services);");
                sb.AppendLine($"{ind}if (__validator is not null)");
                sb.AppendLine($"{ind}{{");
                sb.AppendLine($"{ind}    var __vr = await __validator.ValidateAsync({bodyParam.Name}, ctx.CancellationToken);");
                sb.AppendLine($"{ind}    if (!__vr.IsValid) return global::SliceFx.Wasi.WasiResults.ValidationProblem(__vr.Errors!){wrap};");
                sb.AppendLine($"{ind}}}");
            }
        }

        // 2. Route / query / DI param bindings
        // Track non-nullable route params whose out var has type T? — needs ! in the call site (step 3).
        var nonNullableRouteParams = new HashSet<string>();
        foreach (var p in @params)
        {
            if (p == bodyParam)
            {
                continue;
            }

            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                continue;
            }

            var binding = SourceGenerationHelpers.ResolveParameterBinding(
                p,
                f.HttpMethod,
                f.Pattern,
                serializableTypes);
            if (binding.Source == HandlerParameterBindingSource.Route)
            {
                sb.AppendLine($"{ind}if (!global::SliceFx.Wasi.Binding.WasiArgumentBinder");
                sb.AppendLine($"{ind}    .TryGetFromRoute<{p.TypeFqn}>(ctx, {Str(binding.WireName)}, out var {p.Name}))");
                sb.AppendLine($"{ind}    return global::SliceFx.Wasi.WasiResults.Problem(400, \"Bad Request\", {Str($"Route value '{binding.WireName}' is missing or invalid.")}){wrap};");
                if (!p.IsNullable)
                {
                    nonNullableRouteParams.Add(p.Name);
                }
            }
            else if (binding.Source == HandlerParameterBindingSource.Query)
            {
                var bindingVariable = "__" + p.Name + "Query";
                sb.AppendLine($"{ind}var {bindingVariable} = global::SliceFx.Wasi.Binding.WasiArgumentBinder");
                sb.AppendLine($"{ind}    .BindFromQuery<{p.TypeFqn}>(ctx, {Str(binding.WireName)});");
                sb.AppendLine($"{ind}if ({bindingVariable}.Status == global::SliceFx.Wasi.Binding.WasiArgumentBindingStatus.Invalid)");
                sb.AppendLine($"{ind}    return global::SliceFx.Wasi.WasiResults.Problem(400, \"Bad Request\", {Str($"Query value '{binding.WireName}' is invalid.")}){wrap};");
                if (!p.IsNullable)
                {
                    sb.AppendLine($"{ind}if ({bindingVariable}.Status == global::SliceFx.Wasi.Binding.WasiArgumentBindingStatus.Missing)");
                    sb.AppendLine($"{ind}    return global::SliceFx.Wasi.WasiResults.Problem(400, \"Bad Request\", {Str($"Query value '{binding.WireName}' is missing.")}){wrap};");
                }
                sb.AppendLine($"{ind}var {p.Name} = {bindingVariable}.Value!;");
            }
            else if (binding.Source == HandlerParameterBindingSource.Header)
            {
                var bindingVariable = "__" + p.Name + "Header";
                sb.AppendLine($"{ind}var {bindingVariable} = global::SliceFx.Wasi.Binding.WasiArgumentBinder");
                sb.AppendLine($"{ind}    .BindFromHeader<{p.TypeFqn}>(ctx, {Str(binding.WireName)});");
                sb.AppendLine($"{ind}if ({bindingVariable}.Status == global::SliceFx.Wasi.Binding.WasiArgumentBindingStatus.Invalid)");
                sb.AppendLine($"{ind}    return global::SliceFx.Wasi.WasiResults.Problem(400, \"Bad Request\", {Str($"Header value '{binding.WireName}' is invalid.")}){wrap};");
                if (!p.IsNullable)
                {
                    sb.AppendLine($"{ind}if ({bindingVariable}.Status == global::SliceFx.Wasi.Binding.WasiArgumentBindingStatus.Missing)");
                    sb.AppendLine($"{ind}    return global::SliceFx.Wasi.WasiResults.Problem(400, \"Bad Request\", {Str($"Header value '{binding.WireName}' is missing.")}){wrap};");
                }
                sb.AppendLine($"{ind}var {p.Name} = {bindingVariable}.Value!;");
            }
            else if (binding.Source == HandlerParameterBindingSource.KeyedServices && binding.KeyLiteral is not null)
            {
                sb.AppendLine($"{ind}var {p.Name} = ({p.TypeFqn})global::Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService(ctx.Services, typeof({p.TypeFqn}), {binding.KeyLiteral});");
            }
            else // DI (includes KeyedServices fallback when key literal could not be re-emitted)
            {
                sb.AppendLine($"{ind}var {p.Name} = ({p.TypeFqn})ctx.Services.GetRequiredService(typeof({p.TypeFqn}));");
            }
        }

        // 3. Build call args
        // Non-nullable route params carry type T? from TryGetFromRoute — add ! to suppress CS8604.
        var argList = new List<string>(@params.Length);
        foreach (var p in @params)
        {
            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                argList.Add("ctx.CancellationToken");
            }
            else
            {
                argList.Add(nonNullableRouteParams.Contains(p.Name) ? p.Name + "!" : p.Name);
            }
        }

        var callExpr = $"{f.FullyQualifiedTypeName}.Handle({string.Join(", ", argList)})";
        if (f.ReturnTypeFqn == "void")
        {
            sb.AppendLine($"{ind}{callExpr};");
            sb.AppendLine($"{ind}return global::SliceFx.Wasi.WasiResults.NoContent(){wrap};");
        }
        else if (SourceGenerationHelpers.IsNonGenericAwaitable(f.ReturnTypeFqn))
        {
            sb.AppendLine($"{ind}await {callExpr};");
            sb.AppendLine($"{ind}return global::SliceFx.Wasi.WasiResults.NoContent(){wrap};");
        }
        else
        {
            if (SourceGenerationHelpers.IsGenericAwaitable(f.ReturnTypeFqn))
            {
                sb.AppendLine($"{ind}var __result = await {callExpr};");
            }
            else
            {
                sb.AppendLine($"{ind}var __result = {callExpr};");
            }

            var awaitedType = SourceGenerationHelpers.GetAwaitedReturnType(f.ReturnTypeFqn);
            if (IsWasiResponseType(awaitedType))
            {
                // WasiResponse pass-through (raw escape hatch)
                sb.AppendLine($"{ind}return __result{wrap};");
            }
            else if (SourceGenerationHelpers.IsSliceResultNonGenericType(awaitedType))
            {
                // Non-generic SliceResult (status-only, no body) — no JsonTypeInfo needed
                sb.AppendLine($"{ind}return __result.ToWasiResponse(){wrap};");
            }
            else if (SourceGenerationHelpers.IsSliceResultOfTType(awaitedType))
            {
                // Generic SliceResult<T> (typed body + variable status) — requires context.
                // awaitedType is non-null here: IsSliceResultOfTType checks for null first.
                var payloadType = SourceGenerationHelpers.GetSliceResultPayloadType(awaitedType!);
                // INVARIANT: SliceResult<T> features without a WasiJsonContext are excluded by
                // SLICE021 in JsonContextPlanner.CreatePlan before EmitTableAdd is ever called,
                // so wasiJsonContextFqn is guaranteed non-null here. If the planner ever breaks
                // this invariant, the __JsonTypeInfo<T>() reference below (emitted only when
                // wasiJsonContextFqn is not null) will produce a CS0103 compile error — a
                // deliberately loud failure rather than a silent regression to reflection.
                sb.AppendLine($"{ind}return __result.ToWasiResponse(__JsonTypeInfo<{payloadType}>()){wrap};");
            }
            else
            {
                var resultType = awaitedType;
                // INVARIANT: POCO-returning features without a WasiJsonContext are excluded by
                // SLICE021 in JsonContextPlanner.CreatePlan before EmitTableAdd is ever called,
                // so wasiJsonContextFqn is guaranteed non-null here. Same CS0103 loud-failure
                // guarantee as the SliceResult<T> branch above.
                sb.AppendLine($"{ind}return global::SliceFx.Wasi.WasiResults.Ok<{resultType}>(__result, __JsonTypeInfo<{resultType}>()){wrap};");
            }
        }

        if (hasFilters)
        {
            // Close __handlerCore delegate.
            sb.AppendLine("                    };");
            sb.AppendLine();

            // Build filter chain (statically unrolled, outermost = sliceFilters[0]).
            // For N filters we need N-1 intermediate SliceFilterDelegate variables.
            // The innermost next is always __handlerCore.
            if (sliceFilters.Length == 1)
            {
                // Simple case: single filter, no intermediate delegates needed.
                sb.AppendLine("                    var __filterResult = await __sliceFilter0.InvokeAsync(__sliceFilterCtx, __handlerCore).ConfigureAwait(false);");
            }
            else
            {
                // N>1: build delegates from innermost (index N-1) to index 1, then invoke index 0.
                sb.AppendLine($"                    global::SliceFx.SliceFilterDelegate __sliceNext{sliceFilters.Length - 1} = __handlerCore;");
                for (var i = sliceFilters.Length - 2; i >= 1; i--)
                {
                    sb.AppendLine($"                    global::SliceFx.SliceFilterDelegate __sliceNext{i} = __fc{i} => __sliceFilter{i + 1}.InvokeAsync(__fc{i}, __sliceNext{i + 1});");
                }
                sb.AppendLine($"                    var __filterResult = await __sliceFilter0.InvokeAsync(__sliceFilterCtx, __fc0 => __sliceFilter1.InvokeAsync(__fc0, __sliceNext1)).ConfigureAwait(false);");
            }

            // Decode result: short-circuit → ToWasiResponse; pass-through → unbox WasiResponse.
            sb.AppendLine("                    if (__filterResult.IsShortCircuit)");
            sb.AppendLine("                        return __filterResult.ShortCircuitResult!.Value.ToWasiResponse();");
            sb.AppendLine("                    return (global::SliceFx.Wasi.WasiResponse)__filterResult.HostResponse!;");
        }

        sb.AppendLine($"                }};");
        sb.AppendLine($"            }});");
    }

    private static void EmitValidationMethod(StringBuilder sb, FeatureModel f, ValidationParameterModel parameter)
    {
        sb.AppendLine($"    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? {ValidationMethodName(f, parameter)}({parameter.TypeFqn} value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>? errors = null;");

        foreach (var line in parameter.SerializedRules.Split('\n'))
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }

            DataAnnotationsValidationEmitter.EmitValidationRule(sb, line);
        }

        sb.AppendLine();
        sb.AppendLine("        return __ToValidationErrors(errors);");
        sb.AppendLine("    }");
    }

    private static void EmitValidationHelpers(StringBuilder sb, ImmutableArray<FeatureModel> features)
    {
        var emittedAny = false;
        foreach (var f in features)
        {
            if (f.RequiresReflectionValidation)
            {
                continue;
            }

            foreach (var parameter in f.GetValidationParameters())
            {
                if (!emittedAny)
                {
                    emittedAny = true;
                    sb.AppendLine();
                }

                EmitValidationMethod(sb, f, parameter);
                sb.AppendLine();
            }
        }

        if (!emittedAny)
        {
            return;
        }

        DataAnnotationsValidationEmitter.EmitValidationAttributeFields(
            sb,
            features.SelectMany(static feature => feature.GetValidationParameters()));
        sb.AppendLine("    private static void __AddValidationError(ref global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>? errors, string key, string message)");
        sb.AppendLine("    {");
        sb.AppendLine("        errors ??= new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>(global::System.StringComparer.Ordinal);");
        sb.AppendLine("        if (!errors.TryGetValue(key, out var messages))");
        sb.AppendLine("        {");
        sb.AppendLine("            messages = [];");
        sb.AppendLine("            errors.Add(key, messages);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        messages.Add(message);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? __ToValidationErrors(global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>? errors)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (errors is null || errors.Count == 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var result = new global::System.Collections.Generic.Dictionary<string, string[]>(global::System.StringComparer.Ordinal);");
        sb.AppendLine("        foreach (var entry in errors)");
        sb.AppendLine("        {");
        sb.AppendLine("            result.Add(entry.Key, entry.Value.ToArray());");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private static string ValidationMethodName(FeatureModel f, ValidationParameterModel parameter)
        => "__Validate_" + SanitizeIdentifier(f.FullyQualifiedTypeName) + "_" + parameter.Index;

    private static string SanitizeIdentifier(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        return sb.ToString();
    }

    private static void EmitJsonTypeInfoHelper(StringBuilder sb, string wasiJsonContextFqn)
    {
        sb.AppendLine("    private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T> __JsonTypeInfo<T>()");
        sb.AppendLine($"        => (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T>){wasiJsonContextFqn}.Default.GetTypeInfo(typeof(T))!;");
    }

    private static HandleParamModel? FindBodyParam(
        FeatureModel feature,
        HashSet<string>? serializableTypes = null)
        => SourceGenerationHelpers.FindSingleBodyParameter(feature, serializableTypes);

    private static ValidationParameterModel? FindValidationParameter(FeatureModel feature, int parameterIndex)
    {
        foreach (var parameter in feature.GetValidationParameters())
        {
            if (parameter.Index == parameterIndex)
            {
                return parameter;
            }
        }

        return null;
    }

    private static bool HasValidatorForParameter(
        HandleParamModel parameter,
        ImmutableArray<ValidatorModel> validators)
        => validators.Any(validator => validator.RequestTypeFqn == parameter.TypeFqn);

    private static bool IsWasiResponseType(string? typeFqn)
        => SourceGenerationHelpers.IsWasiResponseType(typeFqn);

    private static string Str(string value) => CSharpLiteral.String(value);

    private static string ToSingleLineComment(string value)
        => value.Replace('\r', ' ').Replace('\n', ' ');

    private readonly record struct WasiSkipReason(
        string DiagnosticId,
        string Reason,
        string? ParameterName = null,
        string? ParameterType = null);
}
