using System.Collections.Immutable;
using System.Text;

namespace Slice.SourceGenerator;

internal static class LambdaFunctionPerFeatureEmitter
{
    public static (string Source, ImmutableArray<EquatableDiagnostic> Diagnostics) Emit(
        ImmutableArray<FeatureModel> features,
        string assemblyName,
        ImmutableArray<ValidatorModel> validators,
        ImmutableArray<ReferencedSliceModule> referencedModules,
        JsonContextPlan jsonContextPlan,
        string? startupTypeFqn)
    {
        var className = GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceLambdaFunctionPerFeatureHandlers");
        var sb = new StringBuilder();
        var diagnostics = ImmutableArray.CreateBuilder<EquatableDiagnostic>();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using global::Amazon.Lambda.APIGatewayEvents;");
        sb.AppendLine("using global::Amazon.Lambda.Core;");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using global::Slice.Lambda.FunctionPerFeature;");
        sb.AppendLine();
        sb.AppendLine($"[assembly: global::Slice.Lambda.FunctionPerFeature.LambdaFunctionPerFeatureModuleAttribute({CSharpLiteral.String("global::Slice." + className)})]");
        sb.AppendLine();
        sb.AppendLine("namespace Slice;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides generated Slice Lambda function-per-feature handlers.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        EmitServiceProvider(sb, assemblyName, referencedModules, startupTypeFqn);
        var lambdaJsonContextFqn = jsonContextPlan.ContextFqn;
        if (lambdaJsonContextFqn is not null)
        {
            sb.AppendLine();
            EmitJsonTypeInfoHelper(sb, lambdaJsonContextFqn);
        }

        foreach (var feature in features)
        {
            EmitFeatureHandler(sb, feature, validators, jsonContextPlan, diagnostics);
        }

        EmitValidationHelpers(sb, features);
        sb.AppendLine("}");

        return (sb.ToString(), diagnostics.ToImmutable());
    }

    private static void EmitServiceProvider(
        StringBuilder sb,
        string assemblyName,
        ImmutableArray<ReferencedSliceModule> referencedModules,
        string? startupTypeFqn)
    {
        var registrationClassName = GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceRegistrations");
        sb.AppendLine("    private static readonly global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.ServiceProvider> s_services = new(");
        sb.AppendLine("        static () => global::Slice.Lambda.FunctionPerFeature.LambdaServiceProvider.Build(static services =>");
        sb.AppendLine("        {");
        if (startupTypeFqn is not null)
        {
            sb.AppendLine($"            new {startupTypeFqn}().ConfigureServices(services);");
        }
        sb.AppendLine($"            global::Slice.{registrationClassName}.AddSliceValidatorServices(services);");
        foreach (var module in referencedModules)
        {
            if (module.HasValidatorServices)
            {
                sb.AppendLine($"            {module.RegistrationTypeFqn}.AddSliceValidatorServices(services);");
            }
        }
        sb.AppendLine("        }));");
    }

    private static void EmitFeatureHandler(
        StringBuilder sb,
        FeatureModel feature,
        ImmutableArray<ValidatorModel> validators,
        JsonContextPlan jsonContextPlan,
        ImmutableArray<EquatableDiagnostic>.Builder diagnostics)
    {
        var skip = GetSkipReason(feature);
        var jsonExclusion = JsonContextPlanner.FindExclusion(jsonContextPlan, feature);
        if (jsonExclusion is not null)
        {
            sb.AppendLine();
            sb.AppendLine($"    // SLICE014: {ToSingleLineComment(feature.EndpointName)} — {jsonExclusion.Value.Reason}; skipped.");
            return;
        }

        if (skip is not null)
        {
            ReportSkipDiagnostic(feature, skip.Value, diagnostics);
            sb.AppendLine();
            sb.AppendLine($"    // {skip.Value.DiagnosticId}: {ToSingleLineComment(feature.EndpointName)} — {skip.Value.Reason}; skipped.");
            return;
        }

        var @params = feature.GetParams();
        var bodyParam = FindBodyParam(feature, @params);
        var awaitedReturnType = SourceGenerationHelpers.GetAwaitedReturnType(feature.ReturnTypeFqn);

        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Handles {CSharpXmlText(feature.HttpMethod + " " + feature.Pattern)} for {CSharpXmlText(feature.EndpointName)}.</summary>");
        sb.AppendLine($"    public static async global::System.Threading.Tasks.Task<global::Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyResponse> {HandlerMethodName(feature)}(");
        sb.AppendLine("        global::Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyRequest request,");
        sb.AppendLine("        global::Amazon.Lambda.Core.ILambdaContext lambdaContext)");
        sb.AppendLine("    {");
        sb.AppendLine("        using var __timeout = global::Slice.Lambda.FunctionPerFeature.LambdaCancellation.Create(lambdaContext);");
        sb.AppendLine("        using var __scope = s_services.Value.CreateScope();");
        sb.AppendLine("        var ctx = new global::Slice.Lambda.FunctionPerFeature.LambdaInvocationContext(request, __scope.ServiceProvider, lambdaContext, __timeout.Token);");

        if (bodyParam is not null)
        {
            sb.AppendLine($"        {bodyParam.TypeFqn}? {bodyParam.Name};");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine($"            {bodyParam.Name} = await global::Slice.Lambda.FunctionPerFeature.LambdaJsonBodyReader.ReadAsync<{bodyParam.TypeFqn}>(ctx, __JsonTypeInfo<{bodyParam.TypeFqn}>()).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine("        catch (global::System.Exception ex) when (ex is global::System.Text.Json.JsonException or global::System.FormatException)");
            sb.AppendLine("        {");
            sb.AppendLine("            return global::Slice.Lambda.FunctionPerFeature.LambdaResponseFactory.Problem(400, \"Bad Request\", \"Request body contains malformed JSON.\");");
            sb.AppendLine("        }");
            sb.AppendLine($"        if ({bodyParam.Name} is null) return global::Slice.Lambda.FunctionPerFeature.LambdaResponseFactory.Problem(400, \"Bad Request\", \"Request body is required.\");");

            if (ShouldUseGeneratedValidation(feature))
            {
                sb.AppendLine($"        var __daErrors = {ValidationMethodName(feature)}({bodyParam.Name});");
                sb.AppendLine("        if (__daErrors is not null) return global::Slice.Lambda.FunctionPerFeature.LambdaResponseFactory.ValidationProblem(__daErrors);");
            }

            if (HasValidatorForParameter(bodyParam, validators))
            {
                sb.AppendLine($"        var __validator = __scope.ServiceProvider.GetService<global::Slice.ISliceValidator<{bodyParam.TypeFqn}>>();");
                sb.AppendLine("        if (__validator is not null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            var __vr = await __validator.ValidateAsync({bodyParam.Name}, ctx.CancellationToken).ConfigureAwait(false);");
                sb.AppendLine("            if (!__vr.IsValid) return global::Slice.Lambda.FunctionPerFeature.LambdaResponseFactory.ValidationProblem(__vr.Errors!);");
                sb.AppendLine("        }");
            }
        }

        foreach (var p in @params)
        {
            if (p == bodyParam || p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                continue;
            }

            var binding = SourceGenerationHelpers.ResolveParameterBinding(p, feature.Pattern, feature.FullyQualifiedTypeName);
            if (binding.Source == HandlerParameterBindingSource.Route)
            {
                sb.AppendLine($"        if (!global::Slice.Lambda.FunctionPerFeature.LambdaArgumentBinder.TryGetFromRoute<{p.TypeFqn}>(ctx, {Str(binding.WireName)}, out var {p.Name}))");
                sb.AppendLine($"            return global::Slice.Lambda.FunctionPerFeature.LambdaResponseFactory.Problem(400, \"Bad Request\", {Str($"Route value '{binding.WireName}' is missing or invalid.")});");
            }
            else if (binding.Source == HandlerParameterBindingSource.Query)
            {
                var bindingVariable = "__" + p.Name + "Query";
                sb.AppendLine($"        var {bindingVariable} = global::Slice.Lambda.FunctionPerFeature.LambdaArgumentBinder.BindFromQuery<{p.TypeFqn}>(ctx, {Str(binding.WireName)});");
                sb.AppendLine($"        if ({bindingVariable}.Status == global::Slice.Lambda.FunctionPerFeature.LambdaArgumentBindingStatus.Invalid)");
                sb.AppendLine($"            return global::Slice.Lambda.FunctionPerFeature.LambdaResponseFactory.Problem(400, \"Bad Request\", {Str($"Query value '{binding.WireName}' is invalid.")});");
                if (!p.IsNullable)
                {
                    sb.AppendLine($"        if ({bindingVariable}.Status == global::Slice.Lambda.FunctionPerFeature.LambdaArgumentBindingStatus.Missing)");
                    sb.AppendLine($"            return global::Slice.Lambda.FunctionPerFeature.LambdaResponseFactory.Problem(400, \"Bad Request\", {Str($"Query value '{binding.WireName}' is missing.")});");
                }
                sb.AppendLine($"        var {p.Name} = {bindingVariable}.Value!;");
            }
            else if (binding.Source == HandlerParameterBindingSource.Header)
            {
                var bindingVariable = "__" + p.Name + "Header";
                sb.AppendLine($"        var {bindingVariable} = global::Slice.Lambda.FunctionPerFeature.LambdaArgumentBinder.BindFromHeader<{p.TypeFqn}>(ctx, {Str(binding.WireName)});");
                sb.AppendLine($"        if ({bindingVariable}.Status == global::Slice.Lambda.FunctionPerFeature.LambdaArgumentBindingStatus.Invalid)");
                sb.AppendLine($"            return global::Slice.Lambda.FunctionPerFeature.LambdaResponseFactory.Problem(400, \"Bad Request\", {Str($"Header value '{binding.WireName}' is invalid.")});");
                if (!p.IsNullable)
                {
                    sb.AppendLine($"        if ({bindingVariable}.Status == global::Slice.Lambda.FunctionPerFeature.LambdaArgumentBindingStatus.Missing)");
                    sb.AppendLine($"            return global::Slice.Lambda.FunctionPerFeature.LambdaResponseFactory.Problem(400, \"Bad Request\", {Str($"Header value '{binding.WireName}' is missing.")});");
                }
                sb.AppendLine($"        var {p.Name} = {bindingVariable}.Value!;");
            }
            else
            {
                sb.AppendLine($"        var {p.Name} = __scope.ServiceProvider.GetRequiredService<{p.TypeFqn}>();");
            }
        }

        var argList = BuildArgList(@params);
        var callExpr = $"{feature.FullyQualifiedTypeName}.Handle({string.Join(", ", argList)})";
        if (feature.ReturnTypeFqn == "void")
        {
            sb.AppendLine($"        {callExpr};");
            sb.AppendLine("        return global::Slice.Lambda.FunctionPerFeature.LambdaResponseFactory.NoContent();");
        }
        else if (SourceGenerationHelpers.IsNonGenericAwaitable(feature.ReturnTypeFqn))
        {
            sb.AppendLine($"        await {callExpr}.ConfigureAwait(false);");
            sb.AppendLine("        return global::Slice.Lambda.FunctionPerFeature.LambdaResponseFactory.NoContent();");
        }
        else
        {
            if (SourceGenerationHelpers.IsGenericAwaitable(feature.ReturnTypeFqn))
            {
                sb.AppendLine($"        var __result = await {callExpr}.ConfigureAwait(false);");
            }
            else
            {
                sb.AppendLine($"        var __result = {callExpr};");
            }

            if (SourceGenerationHelpers.IsLambdaProxyResponseType(awaitedReturnType))
            {
                sb.AppendLine("        return __result;");
            }
            else
            {
                sb.AppendLine($"        return global::Slice.Lambda.FunctionPerFeature.LambdaResponseFactory.Ok<{awaitedReturnType}>(__result, __JsonTypeInfo<{awaitedReturnType}>());");
            }
        }

        sb.AppendLine("    }");
    }

    private static LambdaSkipReason? GetSkipReason(FeatureModel feature)
    {
        if (feature.ReturnsAspNetResult)
        {
            return new LambdaSkipReason("SLICE012", "returns ASP.NET IResult");
        }

        if (SourceGenerationHelpers.IsWasiResponseType(SourceGenerationHelpers.GetAwaitedReturnType(feature.ReturnTypeFqn)))
        {
            return new LambdaSkipReason("SLICE012", "returns Slice.Wasi.WasiResponse");
        }

        if (!feature.GetFilterFqns().IsEmpty)
        {
            return new LambdaSkipReason("SLICE013", "endpoint filters require the ASP.NET endpoint filter pipeline");
        }

        if (feature.RequiresReflectionValidation)
        {
            return new LambdaSkipReason("SLICE016", "DataAnnotations validation requires reflection in the Lambda function-per-feature path");
        }

        var bodyCount = 0;
        foreach (var p in feature.GetParams())
        {
            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                continue;
            }

            var binding = SourceGenerationHelpers.ResolveParameterBinding(p, feature.Pattern, feature.FullyQualifiedTypeName);
            if (binding.Source == HandlerParameterBindingSource.Body)
            {
                bodyCount++;
                if (bodyCount > 1)
                {
                    return new LambdaSkipReason(
                        "SLICE015",
                        "multiple body parameters are not supported",
                        p.Name,
                        SourceGenerationHelpers.TrimGlobalAlias(p.TypeFqn));
                }
            }

            if (binding.Source == HandlerParameterBindingSource.Unsupported)
            {
                return new LambdaSkipReason(
                    "SLICE015",
                    binding.UnsupportedReason ?? "parameter binding is unsupported",
                    p.Name,
                    SourceGenerationHelpers.TrimGlobalAlias(p.TypeFqn));
            }
        }

        return null;
    }

    private static void ReportSkipDiagnostic(
        FeatureModel feature,
        LambdaSkipReason skip,
        ImmutableArray<EquatableDiagnostic>.Builder diagnostics)
    {
        var descriptor = skip.DiagnosticId switch
        {
            "SLICE012" => SliceDiagnostics.UnsupportedReturnTypeForLambdaFunctionPerFeature,
            "SLICE013" => SliceDiagnostics.UnsupportedFilterForLambdaFunctionPerFeature,
            "SLICE015" => SliceDiagnostics.UnsupportedParameterForLambdaFunctionPerFeature,
            "SLICE016" => SliceDiagnostics.UnsupportedValidationForLambdaFunctionPerFeature,
            _ => SliceDiagnostics.UnsupportedReturnTypeForLambdaFunctionPerFeature,
        };

        var diagnostic = skip.DiagnosticId switch
        {
            "SLICE012" => EquatableDiagnostic.Create(descriptor, feature.GetDiagnosticLocationModel(), feature.TypeName, feature.ReturnTypeFqn),
            "SLICE015" => EquatableDiagnostic.Create(descriptor, feature.GetDiagnosticLocationModel(), feature.TypeName, skip.ParameterName ?? "", skip.ParameterType ?? ""),
            _ => EquatableDiagnostic.Create(descriptor, feature.GetDiagnosticLocationModel(), feature.TypeName),
        };
        diagnostics.Add(diagnostic);
    }

    private static string HandlerMethodName(FeatureModel feature)
        => SanitizeIdentifier(feature.EndpointName);

    private static List<string> BuildArgList(ImmutableArray<HandleParamModel> parameters)
    {
        var args = new List<string>(parameters.Length);
        foreach (var p in parameters)
        {
            args.Add(p.TypeFqn == "global::System.Threading.CancellationToken" ? "ctx.CancellationToken" : p.Name);
        }

        return args;
    }

    private static bool ShouldUseGeneratedValidation(FeatureModel feature)
        => !feature.RequiresReflectionValidation && !string.IsNullOrEmpty(feature.SerializedValidationRules);

    private static void EmitValidationHelpers(StringBuilder sb, ImmutableArray<FeatureModel> features)
    {
        var emittedAny = false;
        foreach (var feature in features)
        {
            if (!ShouldUseGeneratedValidation(feature))
            {
                continue;
            }

            if (!emittedAny)
            {
                emittedAny = true;
                sb.AppendLine();
            }

            EmitValidationMethod(sb, feature);
            sb.AppendLine();
        }

        if (!emittedAny)
        {
            return;
        }

        sb.AppendLine("    private static void __AddValidationError(global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>> errors, string key, string message)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!errors.TryGetValue(key, out var messages))");
        sb.AppendLine("        {");
        sb.AppendLine("            messages = [];");
        sb.AppendLine("            errors.Add(key, messages);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        messages.Add(message);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? __ToValidationErrors(global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>> errors)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (errors.Count == 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var result = new global::System.Collections.Generic.Dictionary<string, string[]>(global::System.StringComparer.Ordinal);");
        sb.AppendLine("        foreach (var entry in errors)");
        sb.AppendLine("        {");
        sb.AppendLine("            result.Add(entry.Key, entry.Value.ToArray());");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private static void EmitValidationMethod(StringBuilder sb, FeatureModel feature)
    {
        var requestType = feature.FullyQualifiedTypeName + ".Request";
        sb.AppendLine($"    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? {ValidationMethodName(feature)}({requestType} value)");
        sb.AppendLine("    {");
        sb.AppendLine("        var errors = new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>(global::System.StringComparer.Ordinal);");

        foreach (var line in feature.SerializedValidationRules.Split('\n'))
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }

            var parts = line.Split('|');
            if (parts.Length < 2)
            {
                continue;
            }

            var propertyName = parts[0];
            var propertyAccess = $"value.{propertyName}";
            var localName = "__" + SanitizeIdentifier(propertyName);
            if (parts[1] == "Required")
            {
                var allowEmptyStrings = parts.Length > 2 && parts[2] == "true";
                var message = DecodeValidationMessage(parts, 3, $"The {propertyName} field is required.");
                sb.AppendLine(allowEmptyStrings
                    ? $"        if ({propertyAccess} is null)"
                    : $"        if ({propertyAccess} is null || ({propertyAccess} is string {localName}Required && {localName}Required.Length == 0))");
                sb.AppendLine("        {");
                sb.AppendLine($"            __AddValidationError(errors, {Str(propertyName)}, {Str(message)});");
                sb.AppendLine("        }");
            }
            else if (parts[1] == "StringLength" && parts.Length > 3)
            {
                var message = DecodeValidationMessage(parts, 4, $"The field {propertyName} must be a string with a minimum length of {parts[2]} and a maximum length of {parts[3]}.");
                sb.AppendLine($"        if ({propertyAccess} is string {localName}StringLength && ({localName}StringLength.Length < {parts[2]} || {localName}StringLength.Length > {parts[3]}))");
                sb.AppendLine("        {");
                sb.AppendLine($"            __AddValidationError(errors, {Str(propertyName)}, {Str(message)});");
                sb.AppendLine("        }");
            }
            else if (parts[1] == "MinLength" && parts.Length > 2)
            {
                var lengthMember = parts.Length > 3 ? parts[3] : "Length";
                var message = DecodeValidationMessage(parts, 4, $"The field {propertyName} must be a string or array type with a minimum length of '{parts[2]}'.");
                sb.AppendLine($"        if ({propertyAccess} is not null && {propertyAccess}.{lengthMember} < {parts[2]})");
                sb.AppendLine("        {");
                sb.AppendLine($"            __AddValidationError(errors, {Str(propertyName)}, {Str(message)});");
                sb.AppendLine("        }");
            }
        }

        sb.AppendLine();
        sb.AppendLine("        return __ToValidationErrors(errors);");
        sb.AppendLine("    }");
    }

    private static string DecodeValidationMessage(string[] parts, int index, string fallback)
        => parts.Length <= index ? fallback : Encoding.UTF8.GetString(Convert.FromBase64String(parts[index]));

    private static string ValidationMethodName(FeatureModel feature)
        => "__Validate_" + SanitizeIdentifier(feature.FullyQualifiedTypeName);

    private static void EmitJsonTypeInfoHelper(StringBuilder sb, string lambdaJsonContextFqn)
    {
        sb.AppendLine("    private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T> __JsonTypeInfo<T>()");
        sb.AppendLine($"        => (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T>){lambdaJsonContextFqn}.Default.GetTypeInfo(typeof(T))!;");
    }

    private static HandleParamModel? FindBodyParam(FeatureModel feature, ImmutableArray<HandleParamModel> parameters)
    {
        foreach (var p in parameters)
        {
            var binding = SourceGenerationHelpers.ResolveParameterBinding(p, feature.Pattern, feature.FullyQualifiedTypeName);
            if (binding.Source == HandlerParameterBindingSource.Body)
            {
                return p;
            }
        }

        return null;
    }

    private static bool HasValidatorForParameter(
        HandleParamModel parameter,
        ImmutableArray<ValidatorModel> validators)
        => validators.Any(validator => validator.RequestTypeFqn == parameter.TypeFqn);

    private static string SanitizeIdentifier(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        return sb.ToString();
    }

    private static string Str(string value) => CSharpLiteral.String(value);

    private static string ToSingleLineComment(string value)
        => value.Replace('\r', ' ').Replace('\n', ' ');

    private static string CSharpXmlText(string value)
        => value.Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");

    private readonly record struct LambdaSkipReason(
        string DiagnosticId,
        string Reason,
        string? ParameterName = null,
        string? ParameterType = null);
}
