using System.Collections.Immutable;
using System.Text;

namespace Slice.SourceGenerator;

internal static class LambdaPerFunctionEmitter
{
    public static (string Source, ImmutableArray<EquatableDiagnostic> Diagnostics) Emit(
        ImmutableArray<FeatureModel> features,
        string assemblyName,
        JsonContextPlan jsonContextPlan,
        string? startupTypeFqn)
    {
        var className = GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceLambdaPerFunctionHandlers");
        var sb = new StringBuilder();
        var diagnostics = ImmutableArray.CreateBuilder<EquatableDiagnostic>();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using global::Amazon.Lambda.APIGatewayEvents;");
        sb.AppendLine("using global::Amazon.Lambda.Core;");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using global::Slice.Lambda.PerFunction;");
        sb.AppendLine();
        sb.AppendLine($"[assembly: global::Slice.Lambda.PerFunction.LambdaPerFunctionModuleAttribute({CSharpLiteral.String("global::Slice." + className)})]");
        sb.AppendLine();
        sb.AppendLine("namespace Slice;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides generated Slice Lambda per-feature handlers.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        EmitServiceProvider(sb, startupTypeFqn);
        var lambdaJsonContextFqn = jsonContextPlan.ContextFqn;
        if (lambdaJsonContextFqn is not null)
        {
            sb.AppendLine();
            EmitJsonTypeInfoHelper(sb, lambdaJsonContextFqn);
        }

        foreach (var feature in features)
        {
            EmitFeatureHandler(sb, feature, jsonContextPlan, diagnostics);
        }

        EmitValidationHelpers(sb, features);
        sb.AppendLine("}");

        return (sb.ToString(), diagnostics.ToImmutable());
    }

    private static void EmitServiceProvider(StringBuilder sb, string? startupTypeFqn)
    {
        sb.AppendLine("    private static readonly global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.ServiceProvider> s_services = new(");
        sb.AppendLine("        static () => global::Slice.Lambda.PerFunction.LambdaServiceProvider.Build(static services =>");
        sb.AppendLine("        {");
        if (startupTypeFqn is not null)
        {
            sb.AppendLine($"            new {startupTypeFqn}().ConfigureServices(services);");
        }
        sb.AppendLine("        }));");
    }

    private static void EmitFeatureHandler(
        StringBuilder sb,
        FeatureModel feature,
        JsonContextPlan jsonContextPlan,
        ImmutableArray<EquatableDiagnostic>.Builder diagnostics)
    {
        var skip = GetSkipReason(feature);
        var jsonExclusion = JsonContextPlanner.FindExclusion(jsonContextPlan, feature);
        if (jsonExclusion is not null)
        {
            sb.AppendLine();
            sb.AppendLine($"    // SLICE014: {ToSingleLineComment(feature.EndpointName)} — {jsonExclusion.Value.Reason}; skipped.");
            return;
        }

        if (skip is not null)
        {
            ReportSkipDiagnostic(feature, skip.Value, diagnostics);
            sb.AppendLine();
            sb.AppendLine($"    // {skip.Value.DiagnosticId}: {ToSingleLineComment(feature.EndpointName)} — {skip.Value.Reason}; skipped.");
            return;
        }

        var @params = feature.GetParams();
        var bodyParam = FindBodyParam(feature, @params);
        var awaitedReturnType = SourceGenerationHelpers.GetAwaitedReturnType(feature.ReturnTypeFqn);

        var filterFqns = feature.GetFilterFqns();
        var validatorTypeFqn = FindSliceValidatorType(filterFqns, bodyParam?.TypeFqn);
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Handles {CSharpXmlText(feature.HttpMethod + " " + feature.Pattern)} for {CSharpXmlText(feature.EndpointName)}.</summary>");
        sb.AppendLine($"    public static async global::System.Threading.Tasks.Task<global::Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyResponse> {HandlerMethodName(feature)}(");
        sb.AppendLine("        global::Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyRequest request,");
        sb.AppendLine("        global::Amazon.Lambda.Core.ILambdaContext lambdaContext)");
        sb.AppendLine("    {");
        sb.AppendLine("        using var __timeout = global::Slice.Lambda.PerFunction.LambdaCancellation.Create(lambdaContext);");
        sb.AppendLine("        using var __scope = s_services.Value.CreateScope();");
        sb.AppendLine("        var ctx = new global::Slice.Lambda.PerFunction.LambdaInvocationContext(request, __scope.ServiceProvider, lambdaContext, __timeout.Token);");

        if (bodyParam is not null)
        {
            sb.AppendLine($"        {bodyParam.TypeFqn}? {bodyParam.Name};");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine($"            {bodyParam.Name} = await global::Slice.Lambda.PerFunction.LambdaJsonBodyReader.ReadAsync<{bodyParam.TypeFqn}>(ctx, __JsonTypeInfo<{bodyParam.TypeFqn}>()).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine("        catch (global::System.Exception ex) when (ex is global::System.Text.Json.JsonException or global::System.FormatException)");
            sb.AppendLine("        {");
            sb.AppendLine("            return global::Slice.Lambda.PerFunction.LambdaResponseFactory.Problem(400, \"Bad Request\", \"Request body contains malformed JSON.\");");
            sb.AppendLine("        }");
            sb.AppendLine($"        if ({bodyParam.Name} is null) return global::Slice.Lambda.PerFunction.LambdaResponseFactory.Problem(400, \"Bad Request\", \"Request body is required.\");");

            if (ShouldUseGeneratedValidation(feature))
            {
                sb.AppendLine($"        var __daErrors = {ValidationMethodName(feature)}({bodyParam.Name});");
                sb.AppendLine("        if (__daErrors is not null) return global::Slice.Lambda.PerFunction.LambdaResponseFactory.ValidationProblem(__daErrors);");
            }

            if (validatorTypeFqn is not null)
            {
                sb.AppendLine($"        var __validator = __scope.ServiceProvider.GetRequiredService<global::Slice.ISliceValidator<{bodyParam.TypeFqn}>>();");
                sb.AppendLine($"        var __vr = await __validator.ValidateAsync({bodyParam.Name}, ctx.CancellationToken).ConfigureAwait(false);");
                sb.AppendLine("        if (!__vr.IsValid) return global::Slice.Lambda.PerFunction.LambdaResponseFactory.ValidationProblem(__vr.Errors!);");
            }
        }

        foreach (var p in @params)
        {
            if (p == bodyParam || p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                continue;
            }

            var source = ClassifyNonBodyParam(p, feature.Pattern);
            if (source == ParamSource.Route)
            {
                sb.AppendLine($"        if (!global::Slice.Lambda.PerFunction.LambdaArgumentBinder.TryGetFromRoute<{p.TypeFqn}>(ctx, {Str(p.Name)}, out var {p.Name}))");
                sb.AppendLine($"            return global::Slice.Lambda.PerFunction.LambdaResponseFactory.Problem(400, \"Bad Request\", {Str($"Route value '{p.Name}' is missing or invalid.")});");
            }
            else if (source == ParamSource.Query)
            {
                sb.AppendLine($"        if (!global::Slice.Lambda.PerFunction.LambdaArgumentBinder.TryGetFromQuery<{p.TypeFqn}>(ctx, {Str(p.Name)}, out var {p.Name}))");
                sb.AppendLine($"            return global::Slice.Lambda.PerFunction.LambdaResponseFactory.Problem(400, \"Bad Request\", {Str($"Query value '{p.Name}' is invalid.")});");
            }
            else
            {
                sb.AppendLine($"        var {p.Name} = __scope.ServiceProvider.GetRequiredService<{p.TypeFqn}>();");
            }
        }

        var argList = BuildArgList(@params);
        var callExpr = $"{feature.FullyQualifiedTypeName}.Handle({string.Join(", ", argList)})";
        if (feature.ReturnTypeFqn == "void")
        {
            sb.AppendLine($"        {callExpr};");
            sb.AppendLine("        return global::Slice.Lambda.PerFunction.LambdaResponseFactory.NoContent();");
        }
        else if (SourceGenerationHelpers.IsNonGenericAwaitable(feature.ReturnTypeFqn))
        {
            sb.AppendLine($"        await {callExpr}.ConfigureAwait(false);");
            sb.AppendLine("        return global::Slice.Lambda.PerFunction.LambdaResponseFactory.NoContent();");
        }
        else
        {
            if (SourceGenerationHelpers.IsGenericAwaitable(feature.ReturnTypeFqn))
            {
                sb.AppendLine($"        var __result = await {callExpr}.ConfigureAwait(false);");
            }
            else
            {
                sb.AppendLine($"        var __result = {callExpr};");
            }

            sb.AppendLine($"        return global::Slice.Lambda.PerFunction.LambdaResponseFactory.Ok<{awaitedReturnType}>(__result, __JsonTypeInfo<{awaitedReturnType}>());");
        }

        sb.AppendLine("    }");
    }

    private static LambdaSkipReason? GetSkipReason(FeatureModel feature)
    {
        if (feature.ReturnsAspNetResult)
        {
            return new LambdaSkipReason("SLICE012", "returns ASP.NET IResult");
        }

        foreach (var filter in feature.GetFilterFqns())
        {
            if (!IsSliceValidatorFilter(filter))
            {
                return new LambdaSkipReason("SLICE013", "non-validator endpoint filters require the ASP.NET endpoint filter pipeline");
            }
        }

        if (feature.RequiresReflectionValidation)
        {
            return new LambdaSkipReason("SLICE016", "DataAnnotations validation requires reflection in the Lambda per-feature path");
        }

        foreach (var p in feature.GetParams())
        {
            if (p.TypeFqn == "global::System.Threading.CancellationToken"
                || p.IsInterfaceOrAbstract
                || p.TypeFqn == feature.FullyQualifiedTypeName + ".Request")
            {
                continue;
            }

            if (SourceGenerationHelpers.IsRouteParam(p.Name, feature.Pattern) && !SourceGenerationHelpers.IsSimpleType(p.TypeFqn))
            {
                return new LambdaSkipReason("SLICE015", $"route parameter '{p.Name}' has unsupported type '{SourceGenerationHelpers.TrimGlobalAlias(p.TypeFqn)}'");
            }
        }

        return null;
    }

    private static void ReportSkipDiagnostic(
        FeatureModel feature,
        LambdaSkipReason skip,
        ImmutableArray<EquatableDiagnostic>.Builder diagnostics)
    {
        var descriptor = skip.DiagnosticId switch
        {
            "SLICE012" => SliceDiagnostics.UnsupportedReturnTypeForLambdaPerFeature,
            "SLICE013" => SliceDiagnostics.UnsupportedFilterForLambdaPerFeature,
            "SLICE015" => SliceDiagnostics.UnsupportedParameterForLambdaPerFeature,
            "SLICE016" => SliceDiagnostics.UnsupportedValidationForLambdaPerFeature,
            _ => SliceDiagnostics.UnsupportedReturnTypeForLambdaPerFeature,
        };

        var diagnostic = skip.DiagnosticId switch
        {
            "SLICE012" => EquatableDiagnostic.Create(descriptor, feature.GetDiagnosticLocationModel(), feature.TypeName, feature.ReturnTypeFqn),
            "SLICE015" => EquatableDiagnostic.Create(descriptor, feature.GetDiagnosticLocationModel(), feature.TypeName, ExtractParameterName(skip.Reason), ExtractParameterType(skip.Reason)),
            _ => EquatableDiagnostic.Create(descriptor, feature.GetDiagnosticLocationModel(), feature.TypeName),
        };
        diagnostics.Add(diagnostic);
    }

    private static string ExtractParameterName(string reason)
    {
        const string prefix = "route parameter '";
        var start = reason.IndexOf(prefix, StringComparison.Ordinal);
        if (start < 0)
        {
            return "";
        }

        start += prefix.Length;
        var end = reason.IndexOf('\'', start);
        return end < 0 ? "" : reason.Substring(start, end - start);
    }

    private static string ExtractParameterType(string reason)
    {
        const string prefix = "unsupported type '";
        var start = reason.IndexOf(prefix, StringComparison.Ordinal);
        if (start < 0)
        {
            return "";
        }

        start += prefix.Length;
        var end = reason.IndexOf('\'', start);
        return end < 0 ? "" : reason.Substring(start, end - start);
    }

    private static string HandlerMethodName(FeatureModel feature)
        => SanitizeIdentifier(feature.EndpointName);

    private static List<string> BuildArgList(ImmutableArray<HandleParamModel> parameters)
    {
        var args = new List<string>(parameters.Length);
        foreach (var p in parameters)
        {
            args.Add(p.TypeFqn == "global::System.Threading.CancellationToken" ? "ctx.CancellationToken" : p.Name);
        }

        return args;
    }

    private static bool ShouldUseGeneratedValidation(FeatureModel feature)
        => !feature.RequiresReflectionValidation && !string.IsNullOrEmpty(feature.SerializedValidationRules);

    private static void EmitValidationHelpers(StringBuilder sb, ImmutableArray<FeatureModel> features)
    {
        var emittedAny = false;
        foreach (var feature in features)
        {
            if (!ShouldUseGeneratedValidation(feature))
            {
                continue;
            }

            if (!emittedAny)
            {
                emittedAny = true;
                sb.AppendLine();
            }

            EmitValidationMethod(sb, feature);
            sb.AppendLine();
        }

        if (!emittedAny)
        {
            return;
        }

        sb.AppendLine("    private static void __AddValidationError(global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>> errors, string key, string message)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!errors.TryGetValue(key, out var messages))");
        sb.AppendLine("        {");
        sb.AppendLine("            messages = [];");
        sb.AppendLine("            errors.Add(key, messages);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        messages.Add(message);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? __ToValidationErrors(global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>> errors)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (errors.Count == 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var result = new global::System.Collections.Generic.Dictionary<string, string[]>(global::System.StringComparer.Ordinal);");
        sb.AppendLine("        foreach (var entry in errors)");
        sb.AppendLine("        {");
        sb.AppendLine("            result.Add(entry.Key, entry.Value.ToArray());");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private static void EmitValidationMethod(StringBuilder sb, FeatureModel feature)
    {
        var requestType = feature.FullyQualifiedTypeName + ".Request";
        sb.AppendLine($"    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? {ValidationMethodName(feature)}({requestType} value)");
        sb.AppendLine("    {");
        sb.AppendLine("        var errors = new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>(global::System.StringComparer.Ordinal);");

        foreach (var line in feature.SerializedValidationRules.Split('\n'))
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }

            var parts = line.Split('|');
            if (parts.Length < 2)
            {
                continue;
            }

            var propertyName = parts[0];
            var propertyAccess = $"value.{propertyName}";
            var localName = "__" + SanitizeIdentifier(propertyName);
            if (parts[1] == "Required")
            {
                var allowEmptyStrings = parts.Length > 2 && parts[2] == "true";
                var message = DecodeValidationMessage(parts, 3, $"The {propertyName} field is required.");
                sb.AppendLine(allowEmptyStrings
                    ? $"        if ({propertyAccess} is null)"
                    : $"        if ({propertyAccess} is null || ({propertyAccess} is string {localName}Required && {localName}Required.Length == 0))");
                sb.AppendLine("        {");
                sb.AppendLine($"            __AddValidationError(errors, {Str(propertyName)}, {Str(message)});");
                sb.AppendLine("        }");
            }
            else if (parts[1] == "StringLength" && parts.Length > 3)
            {
                var message = DecodeValidationMessage(parts, 4, $"The field {propertyName} must be a string with a minimum length of {parts[2]} and a maximum length of {parts[3]}.");
                sb.AppendLine($"        if ({propertyAccess} is string {localName}StringLength && ({localName}StringLength.Length < {parts[2]} || {localName}StringLength.Length > {parts[3]}))");
                sb.AppendLine("        {");
                sb.AppendLine($"            __AddValidationError(errors, {Str(propertyName)}, {Str(message)});");
                sb.AppendLine("        }");
            }
            else if (parts[1] == "MinLength" && parts.Length > 2)
            {
                var lengthMember = parts.Length > 3 ? parts[3] : "Length";
                var message = DecodeValidationMessage(parts, 4, $"The field {propertyName} must be a string or array type with a minimum length of '{parts[2]}'.");
                sb.AppendLine($"        if ({propertyAccess} is not null && {propertyAccess}.{lengthMember} < {parts[2]})");
                sb.AppendLine("        {");
                sb.AppendLine($"            __AddValidationError(errors, {Str(propertyName)}, {Str(message)});");
                sb.AppendLine("        }");
            }
        }

        sb.AppendLine();
        sb.AppendLine("        return __ToValidationErrors(errors);");
        sb.AppendLine("    }");
    }

    private static string DecodeValidationMessage(string[] parts, int index, string fallback)
        => parts.Length <= index ? fallback : Encoding.UTF8.GetString(Convert.FromBase64String(parts[index]));

    private static string ValidationMethodName(FeatureModel feature)
        => "__Validate_" + SanitizeIdentifier(feature.FullyQualifiedTypeName);

    private static void EmitJsonTypeInfoHelper(StringBuilder sb, string lambdaJsonContextFqn)
    {
        sb.AppendLine("    private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T> __JsonTypeInfo<T>()");
        sb.AppendLine($"        => (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T>){lambdaJsonContextFqn}.Default.GetTypeInfo(typeof(T))!;");
    }

    private static HandleParamModel? FindBodyParam(FeatureModel feature, ImmutableArray<HandleParamModel> parameters)
    {
        var nestedRequestType = feature.FullyQualifiedTypeName + ".Request";
        foreach (var p in parameters)
        {
            if (p.TypeFqn == nestedRequestType)
            {
                return p;
            }
        }

        return null;
    }

    private static string? FindSliceValidatorType(ImmutableArray<string> filterFqns, string? bodyTypeFqn)
    {
        if (bodyTypeFqn is null)
        {
            return null;
        }

        foreach (var fqn in filterFqns)
        {
            if (fqn.StartsWith(SourceGenerationHelpers.SliceValidatorFilterPrefix, StringComparison.Ordinal))
            {
                return fqn;
            }
        }

        return null;
    }

    private static bool IsSliceValidatorFilter(string filter)
        => filter.StartsWith(SourceGenerationHelpers.SliceValidatorFilterPrefix, StringComparison.Ordinal)
           || filter.StartsWith("Slice.SliceValidatorFilter<", StringComparison.Ordinal)
           || filter.StartsWith("SliceValidatorFilter<", StringComparison.Ordinal);

    private enum ParamSource { Route, Query, DI }

    private static ParamSource ClassifyNonBodyParam(HandleParamModel p, string pattern)
    {
        return !SourceGenerationHelpers.IsSimpleType(p.TypeFqn)
            ? ParamSource.DI
            : SourceGenerationHelpers.IsRouteParam(p.Name, pattern) ? ParamSource.Route : ParamSource.Query;
    }

    private static string SanitizeIdentifier(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        return sb.ToString();
    }

    private static string Str(string value) => CSharpLiteral.String(value);

    private static string ToSingleLineComment(string value)
        => value.Replace('\r', ' ').Replace('\n', ' ');

    private static string CSharpXmlText(string value)
        => value.Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");

    private readonly record struct LambdaSkipReason(string DiagnosticId, string Reason);
}
