using System.Collections.Immutable;
using System.Text;

namespace Slice.SourceGenerator;

internal static class RegistrationEmitter
{
    /// <summary>
    /// Emits ASP.NET Core Slice registration source for the specified feature models.
    /// </summary>
    /// <param name="features">The feature models to include in generated registrations.</param>
    /// <param name="assemblyName">The target assembly name used to form the generated class name.</param>
    /// <returns>The generated C# source.</returns>
    public static string Emit(ImmutableArray<FeatureModel> features, string assemblyName)
    {
        var className = GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceRegistrations");
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Slice.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides generated Slice endpoint registrations.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        EmitAddSliceGenerated(sb, features);
        sb.AppendLine();
        EmitMapSlicesGenerated(sb, features);
        sb.AppendLine();
        EmitMarker(sb);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitAddSliceGenerated(StringBuilder sb, ImmutableArray<FeatureModel> features)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers services required by generated Slice endpoint registrations.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to add Slice services to.</param>");
        sb.AppendLine("    /// <returns>The same service collection for chaining.</returns>");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSliceGenerated(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var feature in features)
        {
            foreach (var ft in feature.GetFilterFqns())
            {
                if (seen.Add(ft))
                {
                    sb.AppendLine($"        services.AddScoped<{ft}>();");
                }
            }
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
    }

    private static void EmitMapSlicesGenerated(StringBuilder sb, ImmutableArray<FeatureModel> features)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps generated Slice endpoints to the route builder.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"app\">The endpoint route builder to map Slice endpoints onto.</param>");
        sb.AppendLine("    /// <returns>The same endpoint route builder for chaining.</returns>");
        sb.AppendLine("    public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapSlicesGenerated(");
        sb.AppendLine("        this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)");
        sb.AppendLine("    {");

        foreach (var f in features)
        {
            sb.AppendLine($"        // {ToSingleLineComment(f.EndpointName)}");
            EmitFeatureRegistration(sb, f);
            sb.AppendLine();
        }

        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
    }

    private static void EmitFeatureRegistration(StringBuilder sb, FeatureModel f)
    {
        var paramModels = f.GetParams();
        var filterFqns = f.GetFilterFqns();

        var delegateType = BuildDelegateType(paramModels, f.ReturnTypeFqn);

        sb.AppendLine($"        app.MapMethods(");
        sb.AppendLine($"            {CSharpStringLiteral(f.Pattern)},");
        sb.AppendLine($"            new[] {{ {CSharpStringLiteral(f.HttpMethod)} }},");
        sb.AppendLine($"            new {delegateType}(");
        sb.AppendLine($"                {f.FullyQualifiedTypeName}.Handle))");
        sb.AppendLine($"        .AddEndpointFilterFactory(");
        sb.AppendLine($"            global::Slice.DataAnnotationsValidationFilter.CreateFilterFactory)");

        foreach (var ft in filterFqns)
        {
            sb.AppendLine($"        .AddEndpointFilter<{ft}>()");
        }

        sb.AppendLine($"        .WithTags({CSharpStringLiteral(f.Tag)})");
        sb.AppendLine($"        .WithName({CSharpStringLiteral(f.EndpointName)})");

        if (f.Summary is not null)
        {
            sb.AppendLine($"        .WithSummary({CSharpStringLiteral(f.Summary)});");
        }
        else
        {
            sb.AppendLine($"        ;");
        }
    }

    private static void EmitMarker(StringBuilder sb)
    {
        sb.AppendLine("    internal static class __SliceAssemblyMarker");
        sb.AppendLine("    {");
        sb.AppendLine("        internal const bool Generated = true;");
        sb.AppendLine("    }");
    }

    private static string BuildDelegateType(ImmutableArray<HandleParamModel> parameters, string returnTypeFqn)
    {
        var args = new List<string>(parameters.Length + 1);
        foreach (var p in parameters)
        {
            args.Add(p.TypeFqn);
        }

        if (returnTypeFqn == "void")
        {
            return args.Count == 0
                ? "global::System.Action"
                : $"global::System.Action<{string.Join(", ", args)}>";
        }

        args.Add(returnTypeFqn);
        return args.Count == 1
            ? $"global::System.Func<{args[0]}>"
            : $"global::System.Func<{string.Join(", ", args)}>";
    }

    private static string CSharpStringLiteral(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');

        foreach (var ch in value)
        {
            switch (ch)
            {
                case '\\':
                    sb.Append(@"\\");
                    break;
                case '"':
                    sb.Append("\\\"");
                    break;
                case '\0':
                    sb.Append(@"\0");
                    break;
                case '\a':
                    sb.Append(@"\a");
                    break;
                case '\b':
                    sb.Append(@"\b");
                    break;
                case '\f':
                    sb.Append(@"\f");
                    break;
                case '\n':
                    sb.Append(@"\n");
                    break;
                case '\r':
                    sb.Append(@"\r");
                    break;
                case '\t':
                    sb.Append(@"\t");
                    break;
                case '\v':
                    sb.Append(@"\v");
                    break;
                default:
                    if (char.IsControl(ch))
                    {
                        sb.Append(@"\u").Append(((int)ch).ToString("x4", System.Globalization.CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        sb.Append(ch);
                    }

                    break;
            }
        }

        sb.Append('"');
        return sb.ToString();
    }

    private static string ToSingleLineComment(string value)
        => value.Replace('\r', ' ').Replace('\n', ' ');
}
