using System.Collections.Immutable;
using System.Text;

namespace Slice.SourceGenerator;

internal static class RegistrationEmitter
{
    /// <summary>
    /// Emits ASP.NET Core Slice registration source for the specified feature models.
    /// </summary>
    /// <param name="features">The feature models to include in generated registrations.</param>
    /// <param name="assemblyName">The target assembly name used to form the generated class name.</param>
    /// <param name="referencedModules">The referenced Slice modules to aggregate from user-facing extension methods.</param>
    /// <param name="emitExtensions">Whether to emit user-facing extension methods for this compilation.</param>
    /// <returns>The generated C# source.</returns>
    public static string Emit(
        ImmutableArray<FeatureModel> features,
        string assemblyName,
        ImmutableArray<ReferencedSliceModule> referencedModules,
        bool emitExtensions)
    {
        var className = GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceRegistrations");
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        if (!features.IsEmpty)
        {
            sb.AppendLine();
            sb.AppendLine($"[assembly: global::Slice.SliceFeatureModuleAttribute(typeof(global::Slice.{className}))]");
        }

        sb.AppendLine();
        sb.AppendLine("namespace Slice;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides generated Slice endpoint registration infrastructure.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        EmitAddSliceServices(sb, features);
        sb.AppendLine();
        EmitMapSliceRoutes(sb, features);
        if (emitExtensions)
        {
            sb.AppendLine();
            EmitAddSlice(sb, className, referencedModules);
            sb.AppendLine();
            EmitMapSlices(sb, className, referencedModules);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitAddSliceServices(StringBuilder sb, ImmutableArray<FeatureModel> features)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers services required by this generated Slice endpoint module.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to add Slice services to.</param>");
        sb.AppendLine("    /// <returns>The same service collection for chaining.</returns>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSliceServices(");
        sb.AppendLine("        global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var feature in features)
        {
            foreach (var ft in feature.GetFilterFqns())
            {
                if (seen.Add(ft))
                {
                    sb.AppendLine($"        services.AddScoped<{ft}>();");
                }
            }
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
    }

    private static void EmitMapSliceRoutes(StringBuilder sb, ImmutableArray<FeatureModel> features)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps this generated Slice endpoint module to the route builder.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"app\">The endpoint route builder to map Slice endpoints onto.</param>");
        sb.AppendLine("    /// <returns>The same endpoint route builder for chaining.</returns>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapSliceRoutes(");
        sb.AppendLine("        global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)");
        sb.AppendLine("    {");

        foreach (var f in features)
        {
            sb.AppendLine($"        // {ToSingleLineComment(f.EndpointName)}");
            EmitFeatureRegistration(sb, f);
            sb.AppendLine();
        }

        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
    }

    private static void EmitAddSlice(
        StringBuilder sb,
        string className,
        ImmutableArray<ReferencedSliceModule> referencedModules)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers services required by generated Slice endpoint registrations.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to add Slice services to.</param>");
        sb.AppendLine("    /// <returns>The same service collection for chaining.</returns>");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSlice(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        global::Slice.{className}.AddSliceServices(services);");
        foreach (var module in referencedModules)
        {
            if (module.HasAspNetServices)
            {
                sb.AppendLine($"        {module.RegistrationTypeFqn}.AddSliceServices(services);");
            }
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
    }

    private static void EmitMapSlices(
        StringBuilder sb,
        string className,
        ImmutableArray<ReferencedSliceModule> referencedModules)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps generated Slice endpoints to the route builder.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"app\">The endpoint route builder to map Slice endpoints onto.</param>");
        sb.AppendLine("    /// <returns>The same endpoint route builder for chaining.</returns>");
        sb.AppendLine("    public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapSlices(");
        sb.AppendLine("        this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)");
        sb.AppendLine("    {");
        sb.AppendLine($"        global::Slice.{className}.MapSliceRoutes(app);");
        foreach (var module in referencedModules)
        {
            if (module.HasAspNetRoutes)
            {
                sb.AppendLine($"        {module.RegistrationTypeFqn}.MapSliceRoutes(app);");
            }
        }

        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
    }

    private static void EmitFeatureRegistration(StringBuilder sb, FeatureModel f)
    {
        var paramModels = f.GetParams();
        var filterFqns = f.GetFilterFqns();

        var delegateType = BuildDelegateType(paramModels, f.ReturnTypeFqn);

        sb.AppendLine($"        app.MapMethods(");
        sb.AppendLine($"            {CSharpLiteral.String(f.Pattern)},");
        sb.AppendLine($"            new[] {{ {CSharpLiteral.String(f.HttpMethod)} }},");
        sb.AppendLine($"            new {delegateType}(");
        sb.AppendLine($"                {f.FullyQualifiedTypeName}.Handle))");
        sb.AppendLine($"        .AddEndpointFilterFactory(");
        sb.AppendLine($"            global::Slice.DataAnnotationsValidationFilter.CreateFilterFactory)");

        foreach (var ft in filterFqns)
        {
            sb.AppendLine($"        .AddEndpointFilter<{ft}>()");
        }

        sb.AppendLine($"        .WithTags({CSharpLiteral.String(f.Tag)})");
        sb.AppendLine($"        .WithName({CSharpLiteral.String(f.EndpointName)})");

        if (f.Summary is not null)
        {
            sb.AppendLine($"        .WithSummary({CSharpLiteral.String(f.Summary)});");
        }
        else
        {
            sb.AppendLine($"        ;");
        }
    }

    private static string BuildDelegateType(ImmutableArray<HandleParamModel> parameters, string returnTypeFqn)
    {
        var args = new List<string>(parameters.Length + 1);
        foreach (var p in parameters)
        {
            args.Add(p.TypeFqn);
        }

        if (returnTypeFqn == "void")
        {
            return args.Count == 0
                ? "global::System.Action"
                : $"global::System.Action<{string.Join(", ", args)}>";
        }

        args.Add(returnTypeFqn);
        return args.Count == 1
            ? $"global::System.Func<{args[0]}>"
            : $"global::System.Func<{string.Join(", ", args)}>";
    }

    private static string ToSingleLineComment(string value)
        => value.Replace('\r', ' ').Replace('\n', ' ');
}
