using System.Collections.Immutable;
using System.Text;

namespace Slice.SourceGenerator;

internal static class RouteManifestEmitter
{
    public static string Emit(ImmutableArray<FeatureModel> features, string assemblyName)
    {
        var className = GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceRouteManifest");
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        EmitRouteAttributes(sb, features);
        sb.AppendLine();
        sb.AppendLine("namespace Slice;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides generated Slice route metadata for tooling and deployment adapters.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        EmitDescriptor(sb);
        sb.AppendLine();
        EmitRoutesField(sb, features);
        sb.AppendLine();
        EmitAccessor(sb);
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitRouteAttributes(StringBuilder sb, ImmutableArray<FeatureModel> features)
    {
        if (features.IsEmpty)
        {
            return;
        }

        sb.AppendLine();
        foreach (var feature in features)
        {
            var (portability, portabilityReason) = ClassifyPortability(feature);
            sb.AppendLine(
                $"[assembly: global::Slice.SliceFeatureRouteAttribute({CSharpLiteral.String(feature.EndpointName)}, {CSharpLiteral.String(TrimGlobalPrefix(feature.FullyQualifiedTypeName))}, {CSharpLiteral.String(feature.HttpMethod)}, {CSharpLiteral.String(feature.Pattern)}, {CSharpLiteral.String(feature.Tag)}, {CSharpNullableStringLiteral(feature.Summary)}, {CSharpNullableStringLiteral(FindRequestType(feature))}, {CSharpLiteral.String(TrimGlobalPrefix(feature.ReturnTypeFqn))}, {CSharpLiteral.String(portability)}, {CSharpNullableStringLiteral(portabilityReason)}, {CSharpNullableStringLiteral(SerializeFilterTypes(feature))}, {CSharpNullableStringLiteral(SerializeParameters(feature))})]");
        }
    }

    private static void EmitDescriptor(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Describes one generated Slice route.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed record SliceRouteDescriptor(");
        sb.AppendLine("        string Method,");
        sb.AppendLine("        string Pattern,");
        sb.AppendLine("        string FeatureType,");
        sb.AppendLine("        string Tag,");
        sb.AppendLine("        string EndpointName,");
        sb.AppendLine("        string? Summary,");
        sb.AppendLine("        string? RequestType,");
        sb.AppendLine("        string ReturnType,");
        sb.AppendLine("        bool IsWorkersCompatible,");
        sb.AppendLine("        string Portability,");
        sb.AppendLine("        string? PortabilityReason,");
        sb.AppendLine("        global::System.Collections.Generic.IReadOnlyList<string> FilterTypes);");
    }

    private static void EmitRoutesField(StringBuilder sb, ImmutableArray<FeatureModel> features)
    {
        sb.AppendLine("    private static readonly SliceRouteDescriptor[] s_routes =");
        sb.AppendLine("    [");
        foreach (var feature in features)
        {
            var (portability, portabilityReason) = ClassifyPortability(feature);
            sb.AppendLine("        new SliceRouteDescriptor(");
            sb.AppendLine($"            {CSharpLiteral.String(feature.HttpMethod)},");
            sb.AppendLine($"            {CSharpLiteral.String(feature.Pattern)},");
            sb.AppendLine($"            {CSharpLiteral.String(TrimGlobalPrefix(feature.FullyQualifiedTypeName))},");
            sb.AppendLine($"            {CSharpLiteral.String(feature.Tag)},");
            sb.AppendLine($"            {CSharpLiteral.String(feature.EndpointName)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(feature.Summary)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(FindRequestType(feature))},");
            sb.AppendLine($"            {CSharpLiteral.String(TrimGlobalPrefix(feature.ReturnTypeFqn))},");
            sb.AppendLine($"            {BoolLiteral(portability == "portable")},");
            sb.AppendLine($"            {CSharpLiteral.String(portability)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(portabilityReason)},");
            sb.AppendLine($"            {FilterTypesLiteral(feature)}),");
        }
        sb.AppendLine("    ];");
    }

    private static void EmitAccessor(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the generated Slice route descriptors for this assembly.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::System.ReadOnlySpan<SliceRouteDescriptor> GetSliceRoutesGenerated()");
        sb.AppendLine("        => s_routes;");
    }

    private static string? FindRequestType(FeatureModel feature)
    {
        var nestedRequestType = feature.FullyQualifiedTypeName + ".Request";
        foreach (var parameter in feature.GetParams())
        {
            if (parameter.TypeFqn == nestedRequestType)
            {
                return TrimGlobalPrefix(parameter.TypeFqn);
            }
        }

        return null;
    }

    private static (string Status, string? Reason) ClassifyPortability(FeatureModel feature)
    {
        if (feature.ReturnsAspNetResult)
        {
            return ("aspnet-only", "returns ASP.NET IResult");
        }

        if (feature.RequiresReflectionValidation)
        {
            return ("partial", "DataAnnotations validation requires reflection in Workers");
        }

        foreach (var filter in feature.GetFilterFqns())
        {
            if (!IsSliceValidatorFilter(filter))
            {
                return ("partial", "non-validator endpoint filters do not run in Workers");
            }
        }

        return ("portable", null);
    }

    private static bool IsSliceValidatorFilter(string filter)
        => filter.StartsWith("global::Slice.SliceValidatorFilter<", StringComparison.Ordinal)
           || filter.StartsWith("Slice.SliceValidatorFilter<", StringComparison.Ordinal)
           || filter.StartsWith("SliceValidatorFilter<", StringComparison.Ordinal);

    private static string FilterTypesLiteral(FeatureModel feature)
    {
        var filters = feature.GetFilterFqns();
        if (filters.IsEmpty)
        {
            return "global::System.Array.Empty<string>()";
        }

        var values = filters
            .Select(static f => CSharpLiteral.String(TrimGlobalPrefix(f)));
        return $"new[] {{ {string.Join(", ", values)} }}";
    }

    private static string? SerializeFilterTypes(FeatureModel feature)
    {
        var filters = feature.GetFilterFqns();
        return filters.IsEmpty
            ? null
            : string.Join("\n", filters.Select(static f => TrimGlobalPrefix(f)));
    }

    private static string? SerializeParameters(FeatureModel feature)
    {
        var parameters = feature.GetParams();
        return parameters.IsEmpty
            ? null
            : string.Join("\n", parameters.Select(static p => $"{TrimGlobalPrefix(p.TypeFqn)}|{p.Name}"));
    }

    private static string TrimGlobalPrefix(string value)
        => value.Replace("global::", "");

    private static string BoolLiteral(bool value) => value ? "true" : "false";

    private static string CSharpNullableStringLiteral(string? value)
        => value is null ? "null" : CSharpLiteral.String(value);
}
