using System.Collections.Immutable;
using System.Text;

namespace Slice.SourceGenerator;

internal static class RouteManifestEmitter
{
    private const string LambdaEligible = "eligible";

    private static readonly HashSet<string> s_simpleTypes = new(StringComparer.Ordinal)
    {
        "global::System.String", "global::System.Guid",
        "global::System.Int32", "global::System.Int64", "global::System.Int16",
        "global::System.UInt32", "global::System.UInt64", "global::System.UInt16",
        "global::System.Boolean", "global::System.Double", "global::System.Single",
        "global::System.Decimal", "global::System.Byte", "global::System.Char",
        "global::System.DateTime", "global::System.DateTimeOffset",
        "global::System.DateOnly", "global::System.TimeOnly", "global::System.TimeSpan",
        "global::System.Uri",
        "string", "int", "long", "short", "bool", "double", "float", "decimal",
    };

    public static string Emit(
        ImmutableArray<FeatureModel> features,
        string assemblyName,
        bool emitLambdaPerFunctionHandlers,
        string? lambdaJsonContextFqn)
    {
        var className = GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceRouteManifest");
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        EmitRouteAttributes(sb, features, assemblyName, emitLambdaPerFunctionHandlers, lambdaJsonContextFqn);
        sb.AppendLine();
        sb.AppendLine("namespace Slice;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides generated Slice route metadata for tooling and deployment adapters.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        EmitDescriptor(sb);
        sb.AppendLine();
        EmitRoutesField(sb, features, assemblyName, emitLambdaPerFunctionHandlers, lambdaJsonContextFqn);
        sb.AppendLine();
        EmitAccessor(sb);
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitRouteAttributes(
        StringBuilder sb,
        ImmutableArray<FeatureModel> features,
        string assemblyName,
        bool emitLambdaPerFunctionHandlers,
        string? lambdaJsonContextFqn)
    {
        if (features.IsEmpty)
        {
            return;
        }

        sb.AppendLine();
        foreach (var feature in features)
        {
            var (portability, portabilityReason) = ClassifyPortability(feature);
            var (lambdaStatus, lambdaReason, lambdaHandlerAssembly, lambdaHandlerType, lambdaHandlerMethod) =
                GetEmittedLambdaMetadata(feature, assemblyName, emitLambdaPerFunctionHandlers, lambdaJsonContextFqn);

            sb.AppendLine(
                $"[assembly: global::Slice.SliceFeatureRouteAttribute({CSharpLiteral.String(feature.EndpointName)}, {CSharpLiteral.String(TrimGlobalPrefix(feature.FullyQualifiedTypeName))}, {CSharpLiteral.String(feature.HttpMethod)}, {CSharpLiteral.String(feature.Pattern)}, {CSharpLiteral.String(feature.Tag)}, {CSharpNullableStringLiteral(feature.Summary)}, {CSharpNullableStringLiteral(FindRequestType(feature))}, {CSharpLiteral.String(TrimGlobalPrefix(feature.ReturnTypeFqn))}, {CSharpLiteral.String(portability)}, {CSharpNullableStringLiteral(portabilityReason)}, {CSharpNullableStringLiteral(SerializeFilterTypes(feature))}, {CSharpNullableStringLiteral(SerializeParameters(feature))}, {CSharpNullableStringLiteral(lambdaStatus)}, {CSharpNullableStringLiteral(lambdaReason)}, {CSharpNullableStringLiteral(lambdaHandlerAssembly)}, {CSharpNullableStringLiteral(lambdaHandlerType)}, {CSharpNullableStringLiteral(lambdaHandlerMethod)})]");
        }
    }

    private static void EmitDescriptor(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Describes one generated Slice route.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed record SliceRouteDescriptor(");
        sb.AppendLine("        string Method,");
        sb.AppendLine("        string Pattern,");
        sb.AppendLine("        string FeatureType,");
        sb.AppendLine("        string Tag,");
        sb.AppendLine("        string EndpointName,");
        sb.AppendLine("        string? Summary,");
        sb.AppendLine("        string? RequestType,");
        sb.AppendLine("        string ReturnType,");
        sb.AppendLine("        bool IsWasiCompatible,");
        sb.AppendLine("        string Portability,");
        sb.AppendLine("        string? PortabilityReason,");
        sb.AppendLine("        string? LambdaPerFeatureStatus,");
        sb.AppendLine("        string? LambdaPerFeatureReason,");
        sb.AppendLine("        string? LambdaPerFeatureHandlerAssembly,");
        sb.AppendLine("        string? LambdaPerFeatureHandlerType,");
        sb.AppendLine("        string? LambdaPerFeatureHandlerMethod,");
        sb.AppendLine("        global::System.Collections.Generic.IReadOnlyList<string> FilterTypes);");
    }

    private static void EmitRoutesField(
        StringBuilder sb,
        ImmutableArray<FeatureModel> features,
        string assemblyName,
        bool emitLambdaPerFunctionHandlers,
        string? lambdaJsonContextFqn)
    {
        sb.AppendLine("    private static readonly SliceRouteDescriptor[] s_routes =");
        sb.AppendLine("    [");
        foreach (var feature in features)
        {
            var (portability, portabilityReason) = ClassifyPortability(feature);
            var (lambdaStatus, lambdaReason, lambdaHandlerAssembly, lambdaHandlerType, lambdaHandlerMethod) =
                GetEmittedLambdaMetadata(feature, assemblyName, emitLambdaPerFunctionHandlers, lambdaJsonContextFqn);

            sb.AppendLine("        new SliceRouteDescriptor(");
            sb.AppendLine($"            {CSharpLiteral.String(feature.HttpMethod)},");
            sb.AppendLine($"            {CSharpLiteral.String(feature.Pattern)},");
            sb.AppendLine($"            {CSharpLiteral.String(TrimGlobalPrefix(feature.FullyQualifiedTypeName))},");
            sb.AppendLine($"            {CSharpLiteral.String(feature.Tag)},");
            sb.AppendLine($"            {CSharpLiteral.String(feature.EndpointName)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(feature.Summary)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(FindRequestType(feature))},");
            sb.AppendLine($"            {CSharpLiteral.String(TrimGlobalPrefix(feature.ReturnTypeFqn))},");
            sb.AppendLine($"            {BoolLiteral(portability == "portable")},");
            sb.AppendLine($"            {CSharpLiteral.String(portability)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(portabilityReason)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(lambdaStatus)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(lambdaReason)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(lambdaHandlerAssembly)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(lambdaHandlerType)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(lambdaHandlerMethod)},");
            sb.AppendLine($"            {FilterTypesLiteral(feature)}),");
        }
        sb.AppendLine("    ];");
    }

    private static void EmitAccessor(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the generated Slice route descriptors for this assembly.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::System.ReadOnlySpan<SliceRouteDescriptor> GetSliceRoutesGenerated()");
        sb.AppendLine("        => s_routes;");
    }

    private static string? FindRequestType(FeatureModel feature)
    {
        var nestedRequestType = feature.FullyQualifiedTypeName + ".Request";
        foreach (var parameter in feature.GetParams())
        {
            if (parameter.TypeFqn == nestedRequestType)
            {
                return TrimGlobalPrefix(parameter.TypeFqn);
            }
        }

        return null;
    }

    private static (string Status, string? Reason) ClassifyPortability(FeatureModel feature)
    {
        if (feature.ReturnsAspNetResult)
        {
            return ("aspnet-only", "returns ASP.NET IResult");
        }

        if (feature.RequiresReflectionValidation)
        {
            return ("partial", "DataAnnotations validation requires reflection in the WASI path");
        }

        foreach (var filter in feature.GetFilterFqns())
        {
            if (!IsSliceValidatorFilter(filter))
            {
                return ("partial", "non-validator endpoint filters do not run in the WASI path");
            }
        }

        return ("portable", null);
    }

    private static bool IsSliceValidatorFilter(string filter)
        => filter.StartsWith("global::Slice.SliceValidatorFilter<", StringComparison.Ordinal)
           || filter.StartsWith("Slice.SliceValidatorFilter<", StringComparison.Ordinal)
           || filter.StartsWith("SliceValidatorFilter<", StringComparison.Ordinal);

    private static (string? Status, string? Reason, string? HandlerAssembly, string? HandlerType, string? HandlerMethod) GetEmittedLambdaMetadata(
        FeatureModel feature,
        string assemblyName,
        bool emitLambdaPerFunctionHandlers,
        string? lambdaJsonContextFqn)
    {
        if (!emitLambdaPerFunctionHandlers)
        {
            return (null, null, null, null, null);
        }

        var lambda = ClassifyLambdaPerFeature(feature, assemblyName, emitLambdaPerFunctionHandlers, lambdaJsonContextFqn);
        return (lambda.Status, lambda.Reason, lambda.HandlerAssembly, lambda.HandlerType, lambda.HandlerMethod);
    }

    internal static LambdaPerFeatureEligibility ClassifyLambdaPerFeature(
        FeatureModel feature,
        string assemblyName,
        bool emitLambdaPerFunctionHandlers,
        string? lambdaJsonContextFqn)
    {
        if (feature.ReturnsAspNetResult)
        {
            return LambdaPerFeatureEligibility.Ineligible("returns ASP.NET IResult");
        }

        foreach (var filter in feature.GetFilterFqns())
        {
            if (!IsSliceValidatorFilter(filter))
            {
                return LambdaPerFeatureEligibility.Ineligible("non-validator endpoint filters require the ASP.NET endpoint filter pipeline");
            }
        }

        if (feature.RequiresReflectionValidation)
        {
            return LambdaPerFeatureEligibility.Ineligible("DataAnnotations validation requires reflection in the Lambda per-feature path");
        }

        var parameters = feature.GetParams();
        var hasBodyParam = FindRequestType(feature) is not null;
        var hasJsonResponse = GetAwaitedReturnType(feature.ReturnTypeFqn) is not null;
        if (lambdaJsonContextFqn is null && (hasBodyParam || hasJsonResponse))
        {
            return LambdaPerFeatureEligibility.Ineligible("LambdaJsonContext is required for AOT-safe JSON body or response serialization");
        }

        foreach (var parameter in parameters)
        {
            if (parameter.TypeFqn == "global::System.Threading.CancellationToken"
                || parameter.IsInterfaceOrAbstract
                || parameter.TypeFqn == feature.FullyQualifiedTypeName + ".Request")
            {
                continue;
            }

            if (IsRouteParam(parameter.Name, feature.Pattern)
                && !IsSimpleType(parameter.TypeFqn))
            {
                return LambdaPerFeatureEligibility.Ineligible($"route parameter '{parameter.Name}' has unsupported type '{TrimGlobalPrefix(parameter.TypeFqn)}'");
            }
        }

        if (!emitLambdaPerFunctionHandlers)
        {
            return new LambdaPerFeatureEligibility(LambdaEligible, null, null, null, null);
        }

        return new LambdaPerFeatureEligibility(
            LambdaEligible,
            null,
            assemblyName,
            $"Slice.{GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceLambdaPerFunctionHandlers")}",
            SanitizeIdentifier(feature.EndpointName));
    }

    private static bool IsSimpleType(string typeFqn)
        => s_simpleTypes.Contains(typeFqn) || IsSimpleNullableType(typeFqn);

    private static bool IsSimpleNullableType(string typeFqn)
    {
        if (!typeFqn.StartsWith("global::System.Nullable<", StringComparison.Ordinal))
        {
            return false;
        }

        var inner = typeFqn.Substring("global::System.Nullable<".Length).TrimEnd('>');
        return s_simpleTypes.Contains(inner);
    }

    private static bool IsRouteParam(string name, string pattern)
    {
        for (var i = 0; i < pattern.Length; i++)
        {
            if (pattern[i] != '{')
            {
                continue;
            }

            if (i + 1 < pattern.Length && pattern[i + 1] == '{')
            {
                i++;
                continue;
            }

            var end = pattern.IndexOf('}', i + 1);
            if (end < 0)
            {
                return false;
            }

            var parameterName = NormalizeRouteParameterName(pattern.Substring(i + 1, end - i - 1));
            if (string.Equals(parameterName, name, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            i = end;
        }

        return false;
    }

    private static string NormalizeRouteParameterName(string token)
    {
        token = token.TrimStart('*');
        var terminator = token.IndexOfAny([':', '?', '=']);
        return terminator >= 0 ? token.Substring(0, terminator) : token;
    }

    private static string? GetAwaitedReturnType(string returnTypeFqn)
    {
        if (returnTypeFqn is "void"
            or "global::System.Threading.Tasks.Task"
            or "global::System.Threading.Tasks.ValueTask")
        {
            return null;
        }

        if (returnTypeFqn.StartsWith("global::System.Threading.Tasks.Task<", StringComparison.Ordinal))
        {
            return returnTypeFqn.Substring("global::System.Threading.Tasks.Task<".Length).TrimEnd('>');
        }

        if (returnTypeFqn.StartsWith("global::System.Threading.Tasks.ValueTask<", StringComparison.Ordinal))
        {
            return returnTypeFqn.Substring("global::System.Threading.Tasks.ValueTask<".Length).TrimEnd('>');
        }

        return returnTypeFqn;
    }

    private static string FilterTypesLiteral(FeatureModel feature)
    {
        var filters = feature.GetFilterFqns();
        if (filters.IsEmpty)
        {
            return "global::System.Array.Empty<string>()";
        }

        var values = filters
            .Select(static f => CSharpLiteral.String(TrimGlobalPrefix(f)));
        return $"new[] {{ {string.Join(", ", values)} }}";
    }

    private static string? SerializeFilterTypes(FeatureModel feature)
    {
        var filters = feature.GetFilterFqns();
        return filters.IsEmpty
            ? null
            : string.Join("\n", filters.Select(static f => TrimGlobalPrefix(f)));
    }

    private static string? SerializeParameters(FeatureModel feature)
    {
        var parameters = feature.GetParams();
        return parameters.IsEmpty
            ? null
            : string.Join("\n", parameters.Select(static p => $"{TrimGlobalPrefix(p.TypeFqn)}|{p.Name}"));
    }

    private static string TrimGlobalPrefix(string value)
        => value.Replace("global::", "");

    private static string BoolLiteral(bool value) => value ? "true" : "false";

    private static string CSharpNullableStringLiteral(string? value)
        => value is null ? "null" : CSharpLiteral.String(value);

    private static string SanitizeIdentifier(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        return sb.Length == 0 ? "_" : sb.ToString();
    }
}

internal readonly record struct LambdaPerFeatureEligibility(
    string Status,
    string? Reason,
    string? HandlerAssembly,
    string? HandlerType,
    string? HandlerMethod)
{
    internal static LambdaPerFeatureEligibility Ineligible(string reason)
        => new("ineligible", reason, null, null, null);
}
