using System.Collections.Immutable;
using System.Text;

namespace Slice.SourceGenerator;

internal static class RouteManifestEmitter
{
    public static string Emit(
        ImmutableArray<FeatureModel> features,
        string assemblyName,
        bool emitLambdaPerFunctionHandlers,
        JsonContextPlan wasiJsonContextPlan,
        JsonContextPlan lambdaJsonContextPlan)
    {
        var className = GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceRouteManifest");
        var routes = BuildRouteManifestEntries(
            features,
            assemblyName,
            emitLambdaPerFunctionHandlers,
            wasiJsonContextPlan,
            lambdaJsonContextPlan);
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        EmitRouteAttributes(sb, routes);
        sb.AppendLine();
        sb.AppendLine("namespace Slice;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides generated Slice route metadata for tooling and deployment adapters.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        EmitDescriptor(sb);
        sb.AppendLine();
        EmitRoutesField(sb, routes);
        sb.AppendLine();
        EmitAccessor(sb);
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitRouteAttributes(
        StringBuilder sb,
        ImmutableArray<RouteManifestEntry> routes)
    {
        if (routes.IsEmpty)
        {
            return;
        }

        sb.AppendLine();
        foreach (var route in routes)
        {
            var feature = route.Feature;

            sb.AppendLine(
                $"[assembly: global::Slice.SliceFeatureRouteAttribute({CSharpLiteral.String(feature.EndpointName)}, {CSharpLiteral.String(SourceGenerationHelpers.TrimGlobalAlias(feature.FullyQualifiedTypeName))}, {CSharpLiteral.String(feature.HttpMethod)}, {CSharpLiteral.String(feature.Pattern)}, {CSharpLiteral.String(feature.Tag)}, {CSharpNullableStringLiteral(feature.Summary)}, {CSharpNullableStringLiteral(FindRequestType(feature))}, {CSharpLiteral.String(SourceGenerationHelpers.TrimGlobalAlias(feature.ReturnTypeFqn))}, {CSharpLiteral.String(route.Portability)}, {CSharpNullableStringLiteral(route.PortabilityReason)}, {CSharpNullableStringLiteral(SerializeFilterTypes(feature))}, {CSharpNullableStringLiteral(SerializeParameters(feature))}, {CSharpNullableStringLiteral(route.LambdaStatus)}, {CSharpNullableStringLiteral(route.LambdaReason)}, {CSharpNullableStringLiteral(route.LambdaHandlerAssembly)}, {CSharpNullableStringLiteral(route.LambdaHandlerType)}, {CSharpNullableStringLiteral(route.LambdaHandlerMethod)}, {CSharpLiteral.String(SourceGenerationHelpers.ManifestSchemaVersion)}, {CSharpNullableStringLiteral(route.WasiStatus)}, {CSharpNullableStringLiteral(route.WasiReason)})]");
        }
    }

    private static void EmitDescriptor(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Describes one generated Slice route.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed record SliceRouteDescriptor(");
        sb.AppendLine("        string Method,");
        sb.AppendLine("        string Pattern,");
        sb.AppendLine("        string FeatureType,");
        sb.AppendLine("        string Tag,");
        sb.AppendLine("        string EndpointName,");
        sb.AppendLine("        string? Summary,");
        sb.AppendLine("        string? RequestType,");
        sb.AppendLine("        string ReturnType,");
        sb.AppendLine("        string ManifestSchemaVersion,");
        sb.AppendLine("        bool IsWasiCompatible,");
        sb.AppendLine("        string Portability,");
        sb.AppendLine("        string? PortabilityReason,");
        sb.AppendLine("        string? WasiDispatchStatus,");
        sb.AppendLine("        string? WasiDispatchReason,");
        sb.AppendLine("        string? LambdaPerFeatureStatus,");
        sb.AppendLine("        string? LambdaPerFeatureReason,");
        sb.AppendLine("        string? LambdaPerFeatureHandlerAssembly,");
        sb.AppendLine("        string? LambdaPerFeatureHandlerType,");
        sb.AppendLine("        string? LambdaPerFeatureHandlerMethod,");
        sb.AppendLine("        global::System.Collections.Generic.IReadOnlyList<string> FilterTypes);");
    }

    private static void EmitRoutesField(
        StringBuilder sb,
        ImmutableArray<RouteManifestEntry> routes)
    {
        sb.AppendLine("    private static readonly SliceRouteDescriptor[] s_routes =");
        sb.AppendLine("    [");
        foreach (var route in routes)
        {
            var feature = route.Feature;

            sb.AppendLine("        new SliceRouteDescriptor(");
            sb.AppendLine($"            {CSharpLiteral.String(feature.HttpMethod)},");
            sb.AppendLine($"            {CSharpLiteral.String(feature.Pattern)},");
            sb.AppendLine($"            {CSharpLiteral.String(SourceGenerationHelpers.TrimGlobalAlias(feature.FullyQualifiedTypeName))},");
            sb.AppendLine($"            {CSharpLiteral.String(feature.Tag)},");
            sb.AppendLine($"            {CSharpLiteral.String(feature.EndpointName)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(feature.Summary)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(FindRequestType(feature))},");
            sb.AppendLine($"            {CSharpLiteral.String(SourceGenerationHelpers.TrimGlobalAlias(feature.ReturnTypeFqn))},");
            sb.AppendLine($"            {CSharpLiteral.String(SourceGenerationHelpers.ManifestSchemaVersion)},");
            sb.AppendLine($"            {BoolLiteral(route.WasiStatus == SourceGenerationHelpers.ManifestEligible)},");
            sb.AppendLine($"            {CSharpLiteral.String(route.Portability)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.PortabilityReason)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.WasiStatus)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.WasiReason)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.LambdaStatus)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.LambdaReason)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.LambdaHandlerAssembly)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.LambdaHandlerType)},");
            sb.AppendLine($"            {CSharpNullableStringLiteral(route.LambdaHandlerMethod)},");
            sb.AppendLine($"            {FilterTypesLiteral(feature)}),");
        }
        sb.AppendLine("    ];");
    }

    private static ImmutableArray<RouteManifestEntry> BuildRouteManifestEntries(
        ImmutableArray<FeatureModel> features,
        string assemblyName,
        bool emitLambdaPerFunctionHandlers,
        JsonContextPlan wasiJsonContextPlan,
        JsonContextPlan lambdaJsonContextPlan)
    {
        var routes = ImmutableArray.CreateBuilder<RouteManifestEntry>(features.Length);
        foreach (var feature in features)
        {
            var (portability, portabilityReason) = ClassifyPortability(feature);
            var wasiStatus = JsonContextPlanner.StatusForWasi(feature, wasiJsonContextPlan);
            var wasiReason = JsonContextPlanner.ReasonForWasi(feature, wasiJsonContextPlan);
            var (lambdaStatus, lambdaReason, lambdaHandlerAssembly, lambdaHandlerType, lambdaHandlerMethod) =
                GetEmittedLambdaMetadata(feature, assemblyName, emitLambdaPerFunctionHandlers, lambdaJsonContextPlan);
            routes.Add(new RouteManifestEntry(
                feature,
                portability,
                portabilityReason,
                wasiStatus,
                wasiReason,
                lambdaStatus,
                lambdaReason,
                lambdaHandlerAssembly,
                lambdaHandlerType,
                lambdaHandlerMethod));
        }

        return routes.ToImmutable();
    }

    private static void EmitAccessor(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the generated Slice route descriptors for this assembly.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::System.ReadOnlySpan<SliceRouteDescriptor> GetSliceRoutesGenerated()");
        sb.AppendLine("        => s_routes;");
    }

    private static string? FindRequestType(FeatureModel feature)
    {
        var nestedRequestType = feature.FullyQualifiedTypeName + ".Request";
        foreach (var parameter in feature.GetParams())
        {
            if (parameter.TypeFqn == nestedRequestType)
            {
                return SourceGenerationHelpers.TrimGlobalAlias(parameter.TypeFqn);
            }
        }

        return null;
    }

    private static (string Status, string? Reason) ClassifyPortability(FeatureModel feature)
    {
        if (feature.ReturnsAspNetResult)
        {
            return (SourceGenerationHelpers.PortabilityAspNetOnly, "returns ASP.NET IResult");
        }

        if (feature.RequiresReflectionValidation)
        {
            return (SourceGenerationHelpers.PortabilityPartial, "DataAnnotations validation requires reflection in the WASI path");
        }

        foreach (var filter in feature.GetFilterFqns())
        {
            if (!IsSliceValidatorFilter(filter))
            {
                return (SourceGenerationHelpers.PortabilityPartial, "non-validator endpoint filters do not run in the WASI path");
            }
        }

        return (SourceGenerationHelpers.PortabilityPortable, null);
    }

    private static bool IsSliceValidatorFilter(string filter)
        => filter.StartsWith(SourceGenerationHelpers.SliceValidatorFilterPrefix, StringComparison.Ordinal)
           || filter.StartsWith("Slice.SliceValidatorFilter<", StringComparison.Ordinal)
           || filter.StartsWith("SliceValidatorFilter<", StringComparison.Ordinal);

    private static (string? Status, string? Reason, string? HandlerAssembly, string? HandlerType, string? HandlerMethod) GetEmittedLambdaMetadata(
        FeatureModel feature,
        string assemblyName,
        bool emitLambdaPerFunctionHandlers,
        JsonContextPlan lambdaJsonContextPlan)
    {
        if (!emitLambdaPerFunctionHandlers)
        {
            return (null, null, null, null, null);
        }

        var lambda = ClassifyLambdaPerFeature(feature, assemblyName, emitLambdaPerFunctionHandlers, lambdaJsonContextPlan);
        return (lambda.Status, lambda.Reason, lambda.HandlerAssembly, lambda.HandlerType, lambda.HandlerMethod);
    }

    internal static LambdaPerFeatureEligibility ClassifyLambdaPerFeature(
        FeatureModel feature,
        string assemblyName,
        bool emitLambdaPerFunctionHandlers,
        JsonContextPlan lambdaJsonContextPlan)
    {
        var reason = JsonContextPlanner.GetLambdaStructuralSkipReason(feature)
            ?? JsonContextPlanner.FindExclusion(lambdaJsonContextPlan, feature)?.Reason;
        if (reason is not null)
        {
            return LambdaPerFeatureEligibility.Ineligible(reason);
        }

        if (!emitLambdaPerFunctionHandlers)
        {
            return new LambdaPerFeatureEligibility(SourceGenerationHelpers.ManifestEligible, null, null, null, null);
        }

        return new LambdaPerFeatureEligibility(
            SourceGenerationHelpers.ManifestEligible,
            null,
            assemblyName,
            $"Slice.{GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceLambdaPerFunctionHandlers")}",
            SanitizeIdentifier(feature.EndpointName));
    }

    private static string FilterTypesLiteral(FeatureModel feature)
    {
        var filters = feature.GetFilterFqns();
        if (filters.IsEmpty)
        {
            return "global::System.Array.Empty<string>()";
        }

        var values = filters
            .Select(static f => CSharpLiteral.String(SourceGenerationHelpers.TrimGlobalAlias(f)));
        return $"new[] {{ {string.Join(", ", values)} }}";
    }

    private static string? SerializeFilterTypes(FeatureModel feature)
    {
        var filters = feature.GetFilterFqns();
        return filters.IsEmpty
            ? null
            : string.Join("\n", filters.Select(static f => SourceGenerationHelpers.TrimGlobalAlias(f)));
    }

    private static string? SerializeParameters(FeatureModel feature)
    {
        var parameters = feature.GetParams();
        return parameters.IsEmpty
            ? null
            : string.Join("\n", parameters.Select(static p => $"{SourceGenerationHelpers.TrimGlobalAlias(p.TypeFqn)}|{p.Name}"));
    }

    private static string BoolLiteral(bool value) => value ? "true" : "false";

    private static string CSharpNullableStringLiteral(string? value)
        => value is null ? "null" : CSharpLiteral.String(value);

    private static string SanitizeIdentifier(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        return sb.Length == 0 ? "_" : sb.ToString();
    }
}

internal readonly record struct RouteManifestEntry(
    FeatureModel Feature,
    string Portability,
    string? PortabilityReason,
    string WasiStatus,
    string? WasiReason,
    string? LambdaStatus,
    string? LambdaReason,
    string? LambdaHandlerAssembly,
    string? LambdaHandlerType,
    string? LambdaHandlerMethod);

internal readonly record struct LambdaPerFeatureEligibility(
    string Status,
    string? Reason,
    string? HandlerAssembly,
    string? HandlerType,
    string? HandlerMethod)
{
    internal static LambdaPerFeatureEligibility Ineligible(string reason)
        => new(SourceGenerationHelpers.ManifestIneligible, reason, null, null, null);
}
