using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Slice.SourceGenerator;

internal static class WorkersRegistrationEmitter
{
    private static readonly HashSet<string> s_simpleTypes = new(StringComparer.Ordinal)
    {
        "global::System.String", "global::System.Guid",
        "global::System.Int32", "global::System.Int64", "global::System.Int16",
        "global::System.UInt32", "global::System.UInt64", "global::System.UInt16",
        "global::System.Boolean", "global::System.Double", "global::System.Single",
        "global::System.Decimal", "global::System.Byte", "global::System.Char",
        "global::System.DateTime", "global::System.DateTimeOffset",
        "global::System.DateOnly", "global::System.TimeOnly", "global::System.TimeSpan",
        "global::System.Uri",
        "string", "int", "long", "short", "bool", "double", "float", "decimal",
    };

    private const string SliceValidatorFilterPrefix = "global::Slice.SliceValidatorFilter<";

    public static (string Source, ImmutableArray<Diagnostic> Diagnostics) Emit(
        ImmutableArray<FeatureModel> features,
        string assemblyName)
    {
        var className = assemblyName.Replace('.', '_') + "_SliceWorkersRegistrations";
        var sb = new StringBuilder();
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using global::Slice.Workers;");
        sb.AppendLine("using global::Slice.Workers.Binding;");
        sb.AppendLine("using global::Slice.Workers.Routing;");
        sb.AppendLine("using global::Slice.Workers.Validation;");
        sb.AppendLine();
        sb.AppendLine("namespace Slice.Generated;");
        sb.AppendLine();
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        // AddSliceGenerated — same name as ASP.NET version but targets WorkerHostBuilder
        sb.AppendLine("    public static global::Slice.Workers.WorkerHostBuilder AddSliceGenerated(");
        sb.AppendLine("        this global::Slice.Workers.WorkerHostBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        builder.AddRoutes(RegisterWorkerRoutes);");
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // RegisterWorkerRoutes
        sb.AppendLine("    public static void RegisterWorkerRoutes(global::Slice.Workers.Routing.WorkerRouteTable table)");
        sb.AppendLine("    {");

        foreach (var f in features)
        {
            var skipReason = GetSkipReason(f.ReturnTypeFqn);
            if (skipReason is not null)
            {
                diagnostics.Add(Diagnostic.Create(
                    SliceDiagnostics.UnsupportedReturnTypeForWorkers,
                    location: null,
                    f.TypeName,
                    f.ReturnTypeFqn));
                sb.AppendLine($"        // SLICE008: {ToSingleLineComment(f.EndpointName)} — return type '{f.ReturnTypeFqn}' not supported in Workers; skipped.");
                continue;
            }

            sb.AppendLine($"        // {ToSingleLineComment(f.EndpointName)}");
            EmitTableAdd(sb, f);
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return (sb.ToString(), diagnostics.ToImmutable());
    }

    private static string? GetSkipReason(string returnTypeFqn)
    {
        // Skip IResult-based returns (ASP.NET-specific)
        return returnTypeFqn == "global::Microsoft.AspNetCore.Http.IResult"
            || returnTypeFqn.Contains("IResult")
            ? "IResult is ASP.NET-specific"
            : null;
    }

    private static void EmitTableAdd(StringBuilder sb, FeatureModel f)
    {
        var @params = f.GetParams();
        var filterFqns = f.GetFilterFqns();

        var bodyParam = FindBodyParam(f, @params);
        // Find SliceValidatorFilter<T>
        var validatorTypeFqn = FindSliceValidatorType(filterFqns, bodyParam?.TypeFqn);

        sb.AppendLine($"        table.Add(");
        sb.AppendLine($"            {Str(f.HttpMethod)},");
        sb.AppendLine($"            {Str(f.Pattern)},");
        sb.AppendLine($"            static sp =>");
        sb.AppendLine($"            {{");
        sb.AppendLine($"                return async ctx =>");
        sb.AppendLine($"                {{");

        // 1. Body binding + null check + DataAnnotations
        if (bodyParam is not null)
        {
            sb.AppendLine($"                    var {bodyParam.Name} = await global::Slice.Workers.Binding.JsonBodyReader");
            sb.AppendLine($"                        .ReadAsync<{bodyParam.TypeFqn}>(ctx);");
            sb.AppendLine($"                    if ({bodyParam.Name} is null) return global::Slice.Workers.SliceResult.Problem(400, \"Bad Request\", \"Request body is required.\");");
            sb.AppendLine($"                    var __daErrors = global::Slice.Workers.Validation.WorkersValidationRunner.Validate({bodyParam.Name});");
            sb.AppendLine($"                    if (__daErrors is not null) return global::Slice.Workers.SliceResult.ValidationProblem(__daErrors);");

            if (validatorTypeFqn is not null)
            {
                sb.AppendLine($"                    var __validator = ctx.Services.GetService(typeof(global::Slice.ISliceValidator<{bodyParam.TypeFqn}>))");
                sb.AppendLine($"                        as global::Slice.ISliceValidator<{bodyParam.TypeFqn}>;");
                sb.AppendLine($"                    if (__validator is not null)");
                sb.AppendLine($"                    {{");
                sb.AppendLine($"                        var __vr = await __validator.ValidateAsync({bodyParam.Name}, ctx.CancellationToken);");
                sb.AppendLine($"                        if (!__vr.IsValid) return global::Slice.Workers.SliceResult.ValidationProblem(__vr.Errors!);");
                sb.AppendLine($"                    }}");
            }
        }

        // 2. Route / query / DI param bindings
        foreach (var p in @params)
        {
            if (p == bodyParam)
            {
                continue;
            }

            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                continue;
            }

            var source = ClassifyNonBodyParam(p, f.Pattern);
            if (source == ParamSource.Route)
            {
                sb.AppendLine($"                    if (!global::Slice.Workers.Binding.WorkerArgumentBinder");
                sb.AppendLine($"                        .TryGetFromRoute<{p.TypeFqn}>(ctx, {Str(p.Name)}, out var {p.Name}))");
                sb.AppendLine($"                        return global::Slice.Workers.SliceResult.Problem(400, \"Bad Request\", {Str($"Route value '{p.Name}' is missing or invalid.")});");
            }
            else if (source == ParamSource.Query)
            {
                sb.AppendLine($"                    if (!global::Slice.Workers.Binding.WorkerArgumentBinder");
                sb.AppendLine($"                        .TryGetFromQuery<{p.TypeFqn}>(ctx, {Str(p.Name)}, out var {p.Name}))");
                sb.AppendLine($"                        return global::Slice.Workers.SliceResult.Problem(400, \"Bad Request\", {Str($"Query value '{p.Name}' is invalid.")});");
            }
            else // DI
            {
                sb.AppendLine($"                    var {p.Name} = ({p.TypeFqn})ctx.Services.GetRequiredService(typeof({p.TypeFqn}));");
            }
        }

        // 3. Build call args
        var argList = new List<string>(@params.Length);
        foreach (var p in @params)
        {
            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                argList.Add("ctx.CancellationToken");
            }
            else
            {
                argList.Add(p.Name);
            }
        }

        var callExpr = $"{f.FullyQualifiedTypeName}.Handle({string.Join(", ", argList)})";
        if (f.ReturnTypeFqn == "void")
        {
            sb.AppendLine($"                    {callExpr};");
            sb.AppendLine($"                    return global::Slice.Workers.SliceResult.NoContent();");
        }
        else if (IsNonGenericAwaitable(f.ReturnTypeFqn))
        {
            sb.AppendLine($"                    await {callExpr};");
            sb.AppendLine($"                    return global::Slice.Workers.SliceResult.NoContent();");
        }
        else
        {
            if (IsGenericAwaitable(f.ReturnTypeFqn))
            {
                sb.AppendLine($"                    var __result = await {callExpr};");
            }
            else
            {
                sb.AppendLine($"                    var __result = {callExpr};");
            }

            sb.AppendLine($"                    return __result is global::Slice.Workers.WorkerResponse __wr");
            sb.AppendLine($"                        ? __wr");
            sb.AppendLine($"                        : global::Slice.Workers.SliceResult.Ok(__result);");
        }

        sb.AppendLine($"                }};");
        sb.AppendLine($"            }});");
    }

    private static HandleParamModel? FindBodyParam(FeatureModel feature, ImmutableArray<HandleParamModel> @params)
    {
        var nestedRequestType = feature.FullyQualifiedTypeName + ".Request";
        foreach (var p in @params)
        {
            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                continue;
            }

            if (p.TypeFqn == nestedRequestType)
            {
                return p;
            }
        }
        return null;
    }

    private static bool IsNonGenericAwaitable(string returnTypeFqn)
        => returnTypeFqn is "global::System.Threading.Tasks.Task"
        or "global::System.Threading.Tasks.ValueTask";

    private static bool IsGenericAwaitable(string returnTypeFqn)
        => returnTypeFqn.StartsWith("global::System.Threading.Tasks.Task<", StringComparison.Ordinal)
        || returnTypeFqn.StartsWith("global::System.Threading.Tasks.ValueTask<", StringComparison.Ordinal);

    private static string? FindSliceValidatorType(ImmutableArray<string> filterFqns, string? bodyTypeFqn)
    {
        if (bodyTypeFqn is null)
        {
            return null;
        }

        foreach (var fqn in filterFqns)
        {
            if (fqn.StartsWith(SliceValidatorFilterPrefix, StringComparison.Ordinal))
            {
                return fqn;
            }
        }
        return null;
    }

    private enum ParamSource { Route, Query, DI }

    private static ParamSource ClassifyNonBodyParam(HandleParamModel p, string pattern)
    {
        return !s_simpleTypes.Contains(p.TypeFqn) && !IsSimpleGenericTypeFqn(p.TypeFqn)
            ? ParamSource.DI
            : IsRouteParam(p.Name, pattern) ? ParamSource.Route : ParamSource.Query;
    }

    private static bool IsRouteParam(string name, string pattern)
        => pattern.Contains($"{{{name}}}") || pattern.Contains($"{{{name}:");

    private static bool IsSimpleGenericTypeFqn(string fqn)
    {
        // Handle Nullable<T> wrapper: "global::System.Nullable<global::System.Guid>" etc.
        if (!fqn.StartsWith("global::System.Nullable<", StringComparison.Ordinal))
        {
            return false;
        }

        var inner = fqn.Substring("global::System.Nullable<".Length).TrimEnd('>');
        return s_simpleTypes.Contains(inner);
    }

    private static string Str(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var ch in value)
        {
            switch (ch)
            {
                case '\\': sb.Append(@"\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append(@"\n"); break;
                case '\r': sb.Append(@"\r"); break;
                case '\t': sb.Append(@"\t"); break;
                default: sb.Append(ch); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    private static string ToSingleLineComment(string value)
        => value.Replace('\r', ' ').Replace('\n', ' ');
}
