using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Slice.SourceGenerator;

internal static class WorkersRegistrationEmitter
{
    private static readonly HashSet<string> s_simpleTypes = new(StringComparer.Ordinal)
    {
        "global::System.String", "global::System.Guid",
        "global::System.Int32", "global::System.Int64", "global::System.Int16",
        "global::System.UInt32", "global::System.UInt64", "global::System.UInt16",
        "global::System.Boolean", "global::System.Double", "global::System.Single",
        "global::System.Decimal", "global::System.Byte", "global::System.Char",
        "global::System.DateTime", "global::System.DateTimeOffset",
        "global::System.DateOnly", "global::System.TimeOnly", "global::System.TimeSpan",
        "global::System.Uri",
        "string", "int", "long", "short", "bool", "double", "float", "decimal",
    };

    private const string SliceValidatorFilterPrefix = "global::Slice.SliceValidatorFilter<";

    /// <summary>
    /// Emits Slice Workers registration source for the specified feature models.
    /// </summary>
    /// <param name="features">The feature models to include in generated registrations.</param>
    /// <param name="assemblyName">The target assembly name used to form the generated class name.</param>
    /// <param name="workersJsonContextFqn">The fully qualified JSON source-generation context type, when available.</param>
    /// <param name="referencedModules">The referenced Slice modules to aggregate from user-facing extension methods.</param>
    /// <param name="emitExtensions">Whether to emit the user-facing Workers extension method for this compilation.</param>
    /// <returns>The generated C# source and any diagnostics produced while emitting it.</returns>
    public static (string Source, ImmutableArray<Diagnostic> Diagnostics) Emit(
        ImmutableArray<FeatureModel> features,
        string assemblyName,
        string? workersJsonContextFqn,
        ImmutableArray<ReferencedSliceModule> referencedModules,
        bool emitExtensions)
    {
        var className = GeneratedIdentifier.FromAssemblyName(assemblyName, "_SliceWorkersRegistrations");
        var sb = new StringBuilder();
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using global::Slice.Workers;");
        sb.AppendLine("using global::Slice.Workers.Binding;");
        sb.AppendLine("using global::Slice.Workers.Routing;");
        sb.AppendLine("using global::Slice.Workers.Validation;");
        if (!features.IsEmpty)
        {
            sb.AppendLine();
            sb.AppendLine($"[assembly: global::Slice.SliceFeatureModuleAttribute(typeof(global::Slice.{className}))]");
        }

        sb.AppendLine();
        sb.AppendLine("namespace Slice;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides generated Slice Workers route registration infrastructure.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers this generated Slice Workers route module with the host builder.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"builder\">The Worker host builder to configure.</param>");
        sb.AppendLine("    /// <returns>The same Worker host builder for chaining.</returns>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static global::Slice.Workers.WorkerHostBuilder AddSliceWorkerRoutes(");
        sb.AppendLine("        global::Slice.Workers.WorkerHostBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        builder.AddRoutes(RegisterWorkerRoutes);");
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();

        if (emitExtensions)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Registers generated Slice Workers routes with the host builder.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    /// <param name=\"builder\">The Worker host builder to configure.</param>");
            sb.AppendLine("    /// <returns>The same Worker host builder for chaining.</returns>");
            sb.AppendLine("    public static global::Slice.Workers.WorkerHostBuilder AddSlice(");
            sb.AppendLine("        this global::Slice.Workers.WorkerHostBuilder builder)");
            sb.AppendLine("    {");
            sb.AppendLine($"        global::Slice.{className}.AddSliceWorkerRoutes(builder);");
            foreach (var module in referencedModules)
            {
                if (module.HasWorkerRoutes)
                {
                    sb.AppendLine($"        {module.RegistrationTypeFqn}.AddSliceWorkerRoutes(builder);");
                }
            }

            sb.AppendLine("        return builder;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        if (workersJsonContextFqn is not null)
        {
            EmitJsonTypeInfoHelper(sb, workersJsonContextFqn);
            sb.AppendLine();
        }

        // RegisterWorkerRoutes
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers generated Slice Workers routes in the route table.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"table\">The Worker route table to populate.</param>");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static void RegisterWorkerRoutes(global::Slice.Workers.Routing.WorkerRouteTable table)");
        sb.AppendLine("    {");

        foreach (var f in features)
        {
            var skipReason = GetSkipReason(f);
            if (skipReason is not null)
            {
                if (f.ReturnsAspNetResult)
                {
                    diagnostics.Add(Diagnostic.Create(
                        SliceDiagnostics.UnsupportedReturnTypeForWorkers,
                        location: null,
                        f.TypeName,
                        f.ReturnTypeFqn));
                    sb.AppendLine($"        // SLICE008: {ToSingleLineComment(f.EndpointName)} — return type '{f.ReturnTypeFqn}' not supported in Workers; skipped.");
                }
                else
                {
                    diagnostics.Add(Diagnostic.Create(
                        SliceDiagnostics.UnsupportedValidationForWorkers,
                        f.GetDiagnosticLocation(),
                        f.TypeName));
                    sb.AppendLine($"        // SLICE011: {ToSingleLineComment(f.EndpointName)} — {skipReason}; skipped.");
                }

                continue;
            }

            if (workersJsonContextFqn is null && FindBodyParam(f, f.GetParams()) is not null)
            {
                diagnostics.Add(Diagnostic.Create(
                    SliceDiagnostics.MissingWorkersJsonContext,
                    location: null,
                    f.TypeName));
            }

            sb.AppendLine($"        // {ToSingleLineComment(f.EndpointName)}");
            EmitTableAdd(sb, f, workersJsonContextFqn);
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        EmitValidationHelpers(sb, features);
        sb.AppendLine("}");

        return (sb.ToString(), diagnostics.ToImmutable());
    }

    private static string? GetSkipReason(FeatureModel feature)
    {
        if (feature.ReturnsAspNetResult)
        {
            return "IResult is ASP.NET-specific";
        }

        if (feature.RequiresReflectionValidation)
        {
            return "DataAnnotations validation requires reflection";
        }

        return null;
    }

    private static void EmitTableAdd(StringBuilder sb, FeatureModel f, string? workersJsonContextFqn)
    {
        var @params = f.GetParams();
        var filterFqns = f.GetFilterFqns();

        var bodyParam = FindBodyParam(f, @params);
        // Find SliceValidatorFilter<T>
        var validatorTypeFqn = FindSliceValidatorType(filterFqns, bodyParam?.TypeFqn);

        sb.AppendLine($"        table.Add(");
        sb.AppendLine($"            {Str(f.HttpMethod)},");
        sb.AppendLine($"            {Str(f.Pattern)},");
        sb.AppendLine($"            static sp =>");
        sb.AppendLine($"            {{");
        sb.AppendLine($"                return async ctx =>");
        sb.AppendLine($"                {{");

        // 1. Body binding + null check + DataAnnotations
        if (bodyParam is not null)
        {
            sb.AppendLine($"                    {bodyParam.TypeFqn}? {bodyParam.Name};");
            sb.AppendLine("                    try");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        {bodyParam.Name} = await global::Slice.Workers.Binding.JsonBodyReader");
            if (workersJsonContextFqn is not null)
            {
                sb.AppendLine($"                            .ReadAsync<{bodyParam.TypeFqn}>(ctx, __JsonTypeInfo<{bodyParam.TypeFqn}>());");
            }
            else
            {
                sb.AppendLine($"                            .ReadAsync<{bodyParam.TypeFqn}>(ctx);");
            }
            sb.AppendLine("                    }");
            sb.AppendLine("                    catch (global::System.Text.Json.JsonException)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        return global::Slice.Workers.SliceResult.Problem(400, \"Bad Request\", \"Request body contains malformed JSON.\");");
            sb.AppendLine("                    }");
            sb.AppendLine($"                    if ({bodyParam.Name} is null) return global::Slice.Workers.SliceResult.Problem(400, \"Bad Request\", \"Request body is required.\");");

            if (ShouldUseGeneratedValidation(f))
            {
                sb.AppendLine($"                    var __daErrors = {ValidationMethodName(f)}({bodyParam.Name});");
                sb.AppendLine($"                    if (__daErrors is not null) return global::Slice.Workers.SliceResult.ValidationProblem(__daErrors);");
            }

            if (validatorTypeFqn is not null)
            {
                sb.AppendLine($"                    var __validator = ctx.Services.GetService(typeof(global::Slice.ISliceValidator<{bodyParam.TypeFqn}>))");
                sb.AppendLine($"                        as global::Slice.ISliceValidator<{bodyParam.TypeFqn}>;");
                sb.AppendLine($"                    if (__validator is not null)");
                sb.AppendLine($"                    {{");
                sb.AppendLine($"                        var __vr = await __validator.ValidateAsync({bodyParam.Name}, ctx.CancellationToken);");
                sb.AppendLine($"                        if (!__vr.IsValid) return global::Slice.Workers.SliceResult.ValidationProblem(__vr.Errors!);");
                sb.AppendLine($"                                    }}");
            }
        }

        // 2. Route / query / DI param bindings
        foreach (var p in @params)
        {
            if (p == bodyParam)
            {
                continue;
            }

            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                continue;
            }

            var source = ClassifyNonBodyParam(p, f.Pattern);
            if (source == ParamSource.Route)
            {
                sb.AppendLine($"                    if (!global::Slice.Workers.Binding.WorkerArgumentBinder");
                sb.AppendLine($"                        .TryGetFromRoute<{p.TypeFqn}>(ctx, {Str(p.Name)}, out var {p.Name}))");
                sb.AppendLine($"                        return global::Slice.Workers.SliceResult.Problem(400, \"Bad Request\", {Str($"Route value '{p.Name}' is missing or invalid.")});");
            }
            else if (source == ParamSource.Query)
            {
                sb.AppendLine($"                    if (!global::Slice.Workers.Binding.WorkerArgumentBinder");
                sb.AppendLine($"                        .TryGetFromQuery<{p.TypeFqn}>(ctx, {Str(p.Name)}, out var {p.Name}))");
                sb.AppendLine($"                        return global::Slice.Workers.SliceResult.Problem(400, \"Bad Request\", {Str($"Query value '{p.Name}' is invalid.")});");
            }
            else // DI
            {
                sb.AppendLine($"                    var {p.Name} = ({p.TypeFqn})ctx.Services.GetRequiredService(typeof({p.TypeFqn}));");
            }
        }

        // 3. Build call args
        var argList = new List<string>(@params.Length);
        foreach (var p in @params)
        {
            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                argList.Add("ctx.CancellationToken");
            }
            else
            {
                argList.Add(p.Name);
            }
        }

        var callExpr = $"{f.FullyQualifiedTypeName}.Handle({string.Join(", ", argList)})";
        if (f.ReturnTypeFqn == "void")
        {
            sb.AppendLine($"                    {callExpr};");
            sb.AppendLine($"                    return global::Slice.Workers.SliceResult.NoContent();");
        }
        else if (IsNonGenericAwaitable(f.ReturnTypeFqn))
        {
            sb.AppendLine($"                    await {callExpr};");
            sb.AppendLine($"                    return global::Slice.Workers.SliceResult.NoContent();");
        }
        else
        {
            if (IsGenericAwaitable(f.ReturnTypeFqn))
            {
                sb.AppendLine($"                    var __result = await {callExpr};");
            }
            else
            {
                sb.AppendLine($"                    var __result = {callExpr};");
            }

            if (IsWorkerResponseType(GetAwaitedReturnType(f.ReturnTypeFqn)))
            {
                sb.AppendLine($"                    return __result;");
            }
            else
            {
                var resultType = GetAwaitedReturnType(f.ReturnTypeFqn);
                if (workersJsonContextFqn is not null)
                {
                    sb.AppendLine($"                    return global::Slice.Workers.SliceResult.Ok<{resultType}>(__result, __JsonTypeInfo<{resultType}>());");
                }
                else
                {
                    sb.AppendLine($"                    return global::Slice.Workers.SliceResult.Ok(__result);");
                }
            }
        }

        sb.AppendLine($"                }};");
        sb.AppendLine($"            }});");
    }

    private static bool ShouldUseGeneratedValidation(FeatureModel f)
        => !f.RequiresReflectionValidation && !string.IsNullOrEmpty(f.SerializedValidationRules);

    private static void EmitValidationMethod(StringBuilder sb, FeatureModel f)
    {
        var requestType = f.FullyQualifiedTypeName + ".Request";
        sb.AppendLine($"    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? {ValidationMethodName(f)}({requestType} value)");
        sb.AppendLine("    {");
        sb.AppendLine("        var errors = new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>>(global::System.StringComparer.Ordinal);");

        foreach (var line in f.SerializedValidationRules.Split('\n'))
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }

            var parts = line.Split('|');
            if (parts.Length < 2)
            {
                continue;
            }

            var propertyName = parts[0];
            var propertyAccess = $"value.{propertyName}";
            var localName = "__" + SanitizeIdentifier(propertyName);
            if (parts[1] == "Required")
            {
                var allowEmptyStrings = parts.Length > 2 && parts[2] == "true";
                var message = DecodeValidationMessage(parts, 3, $"The {propertyName} field is required.");
                if (allowEmptyStrings)
                {
                    sb.AppendLine($"        if ({propertyAccess} is null)");
                }
                else
                {
                    sb.AppendLine($"        if ({propertyAccess} is null || ({propertyAccess} is string {localName}Required && {localName}Required.Length == 0))");
                }
                sb.AppendLine("        {");
                sb.AppendLine($"            __AddValidationError(errors, {Str(propertyName)}, {Str(message)});");
                sb.AppendLine("        }");
            }
            else if (parts[1] == "StringLength" && parts.Length > 3)
            {
                var message = DecodeValidationMessage(parts, 4, $"The field {propertyName} must be a string with a minimum length of {parts[2]} and a maximum length of {parts[3]}.");
                sb.AppendLine($"        if ({propertyAccess} is string {localName}StringLength && ({localName}StringLength.Length < {parts[2]} || {localName}StringLength.Length > {parts[3]}))");
                sb.AppendLine("        {");
                sb.AppendLine($"            __AddValidationError(errors, {Str(propertyName)}, {Str(message)});");
                sb.AppendLine("        }");
            }
            else if (parts[1] == "MinLength" && parts.Length > 2)
            {
                var lengthMember = parts.Length > 3 ? parts[3] : "Length";
                var message = DecodeValidationMessage(parts, 4, $"The field {propertyName} must be a string or array type with a minimum length of '{parts[2]}'.");
                sb.AppendLine($"        if ({propertyAccess} is not null && {propertyAccess}.{lengthMember} < {parts[2]})");
                sb.AppendLine("        {");
                sb.AppendLine($"            __AddValidationError(errors, {Str(propertyName)}, {Str(message)});");
                sb.AppendLine("        }");
            }
        }

        sb.AppendLine();
        sb.AppendLine("        return __ToValidationErrors(errors);");
        sb.AppendLine("    }");
    }

    private static void EmitValidationHelpers(StringBuilder sb, ImmutableArray<FeatureModel> features)
    {
        var emittedAny = false;
        foreach (var f in features)
        {
            if (!ShouldUseGeneratedValidation(f))
            {
                continue;
            }

            if (!emittedAny)
            {
                emittedAny = true;
                sb.AppendLine();
            }

            EmitValidationMethod(sb, f);
            sb.AppendLine();
        }

        if (!emittedAny)
        {
            return;
        }

        sb.AppendLine("    private static void __AddValidationError(global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>> errors, string key, string message)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!errors.TryGetValue(key, out var messages))");
        sb.AppendLine("        {");
        sb.AppendLine("            messages = [];");
        sb.AppendLine("            errors.Add(key, messages);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        messages.Add(message);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string[]>? __ToValidationErrors(global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<string>> errors)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (errors.Count == 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var result = new global::System.Collections.Generic.Dictionary<string, string[]>(global::System.StringComparer.Ordinal);");
        sb.AppendLine("        foreach (var entry in errors)");
        sb.AppendLine("        {");
        sb.AppendLine("            result.Add(entry.Key, entry.Value.ToArray());");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private static string ValidationMethodName(FeatureModel f)
        => "__Validate_" + SanitizeIdentifier(f.FullyQualifiedTypeName);

    private static string DecodeValidationMessage(string[] parts, int index, string fallback)
    {
        if (parts.Length <= index)
        {
            return fallback;
        }

        return Encoding.UTF8.GetString(Convert.FromBase64String(parts[index]));
    }

    private static string SanitizeIdentifier(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        return sb.ToString();
    }

    private static void EmitJsonTypeInfoHelper(StringBuilder sb, string workersJsonContextFqn)
    {
        sb.AppendLine("    private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T> __JsonTypeInfo<T>()");
        sb.AppendLine($"        => (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T>){workersJsonContextFqn}.Default.GetTypeInfo(typeof(T))!;");
    }

    private static HandleParamModel? FindBodyParam(FeatureModel feature, ImmutableArray<HandleParamModel> @params)
    {
        var nestedRequestType = feature.FullyQualifiedTypeName + ".Request";
        foreach (var p in @params)
        {
            if (p.TypeFqn == "global::System.Threading.CancellationToken")
            {
                continue;
            }

            if (p.TypeFqn == nestedRequestType)
            {
                return p;
            }
        }
        return null;
    }

    private static bool IsNonGenericAwaitable(string returnTypeFqn)
        => returnTypeFqn is "global::System.Threading.Tasks.Task"
        or "global::System.Threading.Tasks.ValueTask";

    private static bool IsGenericAwaitable(string returnTypeFqn)
        => returnTypeFqn.StartsWith("global::System.Threading.Tasks.Task<", StringComparison.Ordinal)
        || returnTypeFqn.StartsWith("global::System.Threading.Tasks.ValueTask<", StringComparison.Ordinal);

    private static string? GetAwaitedReturnType(string returnTypeFqn)
    {
        if (returnTypeFqn is "void"
            or "global::System.Threading.Tasks.Task"
            or "global::System.Threading.Tasks.ValueTask")
        {
            return null;
        }

        if (returnTypeFqn.StartsWith("global::System.Threading.Tasks.Task<", StringComparison.Ordinal))
        {
            return GetSingleGenericArgument(returnTypeFqn, "global::System.Threading.Tasks.Task<");
        }

        if (returnTypeFqn.StartsWith("global::System.Threading.Tasks.ValueTask<", StringComparison.Ordinal))
        {
            return GetSingleGenericArgument(returnTypeFqn, "global::System.Threading.Tasks.ValueTask<");
        }

        return returnTypeFqn;
    }

    private static string GetSingleGenericArgument(string typeFqn, string prefix)
        => typeFqn.Substring(prefix.Length, typeFqn.Length - prefix.Length - 1);

    private static bool IsWorkerResponseType(string? typeFqn)
        => typeFqn == "global::Slice.Workers.WorkerResponse";

    private static string? FindSliceValidatorType(ImmutableArray<string> filterFqns, string? bodyTypeFqn)
    {
        if (bodyTypeFqn is null)
        {
            return null;
        }

        foreach (var fqn in filterFqns)
        {
            if (fqn.StartsWith(SliceValidatorFilterPrefix, StringComparison.Ordinal))
            {
                return fqn;
            }
        }
        return null;
    }

    private enum ParamSource { Route, Query, DI }

    private static ParamSource ClassifyNonBodyParam(HandleParamModel p, string pattern)
    {
        return !s_simpleTypes.Contains(p.TypeFqn) && !IsSimpleGenericTypeFqn(p.TypeFqn)
            ? ParamSource.DI
            : IsRouteParam(p.Name, pattern) ? ParamSource.Route : ParamSource.Query;
    }

    private static bool IsRouteParam(string name, string pattern)
    {
        for (var i = 0; i < pattern.Length; i++)
        {
            if (pattern[i] != '{')
            {
                continue;
            }

            if (i + 1 < pattern.Length && pattern[i + 1] == '{')
            {
                i++;
                continue;
            }

            var end = pattern.IndexOf('}', i + 1);
            if (end < 0)
            {
                return false;
            }

            var token = pattern.Substring(i + 1, end - i - 1);
            var colon = token.IndexOf(':');
            var parameterName = colon >= 0 ? token.Substring(0, colon) : token;
            if (string.Equals(parameterName, name, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            i = end;
        }

        return false;
    }

    private static bool IsSimpleGenericTypeFqn(string fqn)
    {
        // Handle Nullable<T> wrapper: "global::System.Nullable<global::System.Guid>" etc.
        if (!fqn.StartsWith("global::System.Nullable<", StringComparison.Ordinal))
        {
            return false;
        }

        var inner = fqn.Substring("global::System.Nullable<".Length).TrimEnd('>');
        return s_simpleTypes.Contains(inner);
    }

    private static string Str(string value) => CSharpLiteral.String(value);

    private static string ToSingleLineComment(string value)
        => value.Replace('\r', ' ').Replace('\n', ' ');
}
