// <auto-generated/>
// Shared between SliceFx.SourceGenerator and SliceFx.Cli via <Compile Include>.
// Keep this file free of any project-specific types.
#nullable enable

using System;

namespace SliceFx.Shared;

/// <summary>
/// Pure string-based helpers for determining JSON serialization roots.
/// Shared between the source generator (uses FeatureModel / HandleParamModel) and the CLI
/// (uses SliceRouteParameter from the route manifest).  Each consumer wraps these utilities
/// with a thin adapter that provides the required string values.
/// </summary>
internal static class JsonContextRootHelpers
{
    private const string GlobalPrefix = "global::";
    private const string SystemPrefix = "System.";
    private const string MicrosoftPrefix = "Microsoft.";
    private const string SliceResultPrefix = "global::SliceFx.SliceResult<";
    private const string SliceResultNonGenericFqn = "global::SliceFx.SliceResult";
    private const string TaskPrefix = "global::System.Threading.Tasks.Task<";
    private const string ValueTaskPrefix = "global::System.Threading.Tasks.ValueTask<";

    // Roslyn's FullyQualifiedFormat retains C# keyword aliases (e.g. "string", "int") inside
    // generic arguments such as Task<string>.  These are built-in types with native STJ converters
    // and never need an explicit [JsonSerializable] entry.
    private static readonly HashSet<string> s_csharpKeywordTypes = new(StringComparer.Ordinal)
    {
        "string", "int", "long", "short", "uint", "ulong", "ushort",
        "bool", "double", "float", "decimal", "byte", "sbyte", "char",
        "object", "void",
    };

    /// <summary>
    /// Returns true when <paramref name="paramTypeFqn"/> (fully-qualified, may include
    /// <c>global::</c> prefix) is a nested type of <paramref name="featureTypeFqn"/>.
    /// This heuristic identifies the conventional SliceFx <c>Request</c> record pattern:
    /// <c>CreateUser.Request</c> lives inside <c>CreateUser</c>.
    /// Detection-only — does not affect binding behavior.
    /// </summary>
    public static bool IsNestedTypeOf(string paramTypeFqn, string featureTypeFqn)
    {
        // Normalise both to bare (no global:: prefix) for comparison.
        var param = TrimGlobalAlias(paramTypeFqn);
        var feature = TrimGlobalAlias(featureTypeFqn);
        return param.StartsWith(feature + ".", StringComparison.Ordinal);
    }

    /// <summary>
    /// Unwraps <c>Task&lt;T&gt;</c>, <c>ValueTask&lt;T&gt;</c>, and <c>SliceResult&lt;T&gt;</c>
    /// recursively to reach the payload type FQN.  Returns <c>null</c> when the type is
    /// <c>Task</c> / <c>ValueTask</c> (void), <c>SliceResult</c> (non-generic), or a raw
    /// <c>IResult</c>-family type (pass-through).
    /// </summary>
    public static string? UnwrapReturnType(string? returnTypeFqn)
    {
        if (returnTypeFqn is null)
        {
            return null;
        }

        // Unwrap Task<T> and ValueTask<T>
        if (returnTypeFqn.StartsWith(TaskPrefix, StringComparison.Ordinal))
        {
            var inner = returnTypeFqn.Substring(TaskPrefix.Length).TrimEnd('>');
            return UnwrapReturnType(inner);
        }

        if (returnTypeFqn.StartsWith(ValueTaskPrefix, StringComparison.Ordinal))
        {
            var inner = returnTypeFqn.Substring(ValueTaskPrefix.Length).TrimEnd('>');
            return UnwrapReturnType(inner);
        }

        // SliceResult<T> → unwrap to T
        if (returnTypeFqn.StartsWith(SliceResultPrefix, StringComparison.Ordinal))
        {
            var inner = returnTypeFqn.Substring(SliceResultPrefix.Length).TrimEnd('>');
            return UnwrapReturnType(inner);
        }

        // Non-generic SliceResult (status-only) — no JSON root.
        if (string.Equals(returnTypeFqn, SliceResultNonGenericFqn, StringComparison.Ordinal))
        {
            return null;
        }

        // Bare Task / ValueTask — void
        if (string.Equals(returnTypeFqn, "global::System.Threading.Tasks.Task", StringComparison.Ordinal)
            || string.Equals(returnTypeFqn, "global::System.Threading.Tasks.ValueTask", StringComparison.Ordinal)
            || string.Equals(returnTypeFqn, "void", StringComparison.Ordinal))
        {
            return null;
        }

        return returnTypeFqn;
    }

    /// <summary>
    /// Returns true when <paramref name="typeFqn"/> is a framework type that has built-in
    /// STJ serializer support and does not require an explicit <c>[JsonSerializable]</c> entry.
    /// Covers:
    /// <list type="bullet">
    ///   <item>FQN forms prefixed with <c>System.</c> or <c>Microsoft.</c></item>
    ///   <item>C# keyword aliases (<c>string</c>, <c>int</c>, <c>bool</c>, …) that Roslyn may
    ///         emit inside generic arguments even when <c>FullyQualifiedFormat</c> is requested</item>
    /// </list>
    /// </summary>
    public static bool IsFrameworkType(string typeFqn)
    {
        // Fast path: C# keyword aliases (e.g. "string", "int") never have a global:: prefix.
        if (s_csharpKeywordTypes.Contains(typeFqn))
        {
            return true;
        }

        var bare = TrimGlobalAlias(typeFqn);
        return bare.StartsWith(SystemPrefix, StringComparison.Ordinal)
            || bare.StartsWith(MicrosoftPrefix, StringComparison.Ordinal);
    }

    /// <summary>Strips the <c>global::</c> alias from a fully-qualified type name.</summary>
    public static string TrimGlobalAlias(string typeFqn)
        => typeFqn.StartsWith(GlobalPrefix, StringComparison.Ordinal)
            ? typeFqn.Substring(GlobalPrefix.Length)
            : typeFqn;
}
