// <auto-generated/>
// Shared between SliceFx.SourceGenerator and SliceFx.Cli via <Compile Include>.
// Keep this file free of any project-specific types.
#nullable enable

using System;

namespace SliceFx.Shared;

/// <summary>
/// Pure string-based helpers for determining JSON serialization roots.
/// Shared between the source generator (uses FeatureModel / HandleParamModel) and the CLI
/// (uses SliceRouteParameter from the route manifest).  Each consumer wraps these utilities
/// with a thin adapter that provides the required string values.
/// </summary>
internal static class JsonContextRootHelpers
{
    private const string GlobalPrefix = "global::";
    private const string SystemPrefix = "System.";
    private const string MicrosoftPrefix = "Microsoft.";

    // Roslyn's FullyQualifiedFormat retains C# keyword aliases (e.g. "string", "int") inside
    // generic arguments such as Task<string>.  These are built-in types with native STJ converters
    // and never need an explicit [JsonSerializable] entry.
    private static readonly HashSet<string> s_csharpKeywordTypes = new(StringComparer.Ordinal)
    {
        "string", "int", "long", "short", "uint", "ulong", "ushort",
        "bool", "double", "float", "decimal", "byte", "sbyte", "char",
        "object", "void",
    };

    /// <summary>
    /// Returns true when <paramref name="paramTypeFqn"/> (fully-qualified, may include
    /// <c>global::</c> prefix) is a nested type of <paramref name="featureTypeFqn"/>.
    /// This heuristic identifies the conventional SliceFx <c>Request</c> record pattern:
    /// <c>CreateUser.Request</c> lives inside <c>CreateUser</c>.
    /// Detection-only — does not affect binding behavior.
    /// </summary>
    public static bool IsNestedTypeOf(string paramTypeFqn, string featureTypeFqn)
    {
        // Normalise both to bare (no global:: prefix) for comparison.
        var param = TrimGlobalAlias(paramTypeFqn);
        var feature = TrimGlobalAlias(featureTypeFqn);
        return param.StartsWith(feature + ".", StringComparison.Ordinal);
    }

    /// <summary>
    /// Returns true when <paramref name="typeFqn"/> is a framework type that has built-in
    /// STJ serializer support and does not require an explicit <c>[JsonSerializable]</c> entry.
    /// Covers:
    /// <list type="bullet">
    ///   <item>FQN forms prefixed with <c>System.</c> or <c>Microsoft.</c></item>
    ///   <item>C# keyword aliases (<c>string</c>, <c>int</c>, <c>bool</c>, …) that Roslyn may
    ///         emit inside generic arguments even when <c>FullyQualifiedFormat</c> is requested</item>
    /// </list>
    /// </summary>
    public static bool IsFrameworkType(string typeFqn)
    {
        // Fast path: C# keyword aliases (e.g. "string", "int") never have a global:: prefix.
        if (s_csharpKeywordTypes.Contains(typeFqn))
        {
            return true;
        }

        var bare = TrimGlobalAlias(typeFqn);
        return bare.StartsWith(SystemPrefix, StringComparison.Ordinal)
            || bare.StartsWith(MicrosoftPrefix, StringComparison.Ordinal);
    }

    /// <summary>
    /// Returns true when <paramref name="typeFqn"/> (a JSON root) needs an explicit
    /// <c>[JsonSerializable(typeof(T))]</c> entry because its type tree references any
    /// user-defined (non-framework) type. The check recurses through generic type arguments
    /// and array/tuple element types: a constructed framework container that wraps a user type
    /// (e.g. <c>List&lt;MyDto&gt;</c>, <c>Dictionary&lt;string, MyDto&gt;</c>) needs the
    /// <em>container itself</em> registered, so it returns true. Pure framework constructions
    /// (<c>System.Int32</c>, <c>byte[]</c>, <c>List&lt;string&gt;</c>, <c>Memory&lt;byte&gt;</c>, …)
    /// have built-in STJ support or are covered transitively and return false (skip) — matching the
    /// pre-existing behavior for scalar framework roots and avoiding spurious missing-root diagnostics.
    /// </summary>
    public static bool RequiresJsonSerializableRegistration(string typeFqn)
    {
        foreach (var leaf in EnumerateLeafTypeNames(typeFqn))
        {
            if (!IsFrameworkType(leaf))
            {
                return true;
            }
        }

        return false;
    }

    // Splits a fully-qualified type name into its leaf type-name tokens by treating generic-argument,
    // array, and tuple punctuation (plus whitespace) as separators. The dotted namespace inside a
    // single token is preserved; the leading global:: alias is left for IsFrameworkType to strip.
    private static IEnumerable<string> EnumerateLeafTypeNames(string typeFqn)
    {
        var start = 0;
        for (var i = 0; i <= typeFqn.Length; i++)
        {
            if (i == typeFqn.Length || IsTypeNameSeparator(typeFqn[i]))
            {
                if (i > start)
                {
                    var token = typeFqn.Substring(start, i - start);
                    if (!string.IsNullOrWhiteSpace(token))
                    {
                        yield return token;
                    }
                }

                start = i + 1;
            }
        }
    }

    private static bool IsTypeNameSeparator(char c)
        => c is '<' or '>' or ',' or '[' or ']' or '(' or ')' or ' ' or '\t' or '\n' or '\r';

    /// <summary>Strips the <c>global::</c> alias from a fully-qualified type name.</summary>
    public static string TrimGlobalAlias(string typeFqn)
        => typeFqn.StartsWith(GlobalPrefix, StringComparison.Ordinal)
            ? typeFqn.Substring(GlobalPrefix.Length)
            : typeFqn;
}
