using System.CommandLine;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using SliceFx.Cli.Internal;

namespace SliceFx.Cli.Commands;

internal static partial class GenerateCSharpClientCommand
{
    internal static Command Build()
    {
        var projectOpt = SharedOptions.CreateProject();
        var outputOpt = new Option<FileInfo?>("--output")
        {
            Description = "Output .cs file. Defaults to SliceApiClient.g.cs in the target project directory.",
        };
        var namespaceOpt = new Option<string?>("--namespace")
        {
            Description = "Namespace for the generated client. Defaults to <RootNamespace>.Client.",
        };
        var classOpt = new Option<string>("--class")
        {
            Description = "Generated client class name.",
            DefaultValueFactory = _ => "SliceApiClient",
        };
        var forceOpt = SharedOptions.CreateForce();

        var cmd = new Command("csharp", "Generate a C# typed HttpClient for portable Slice routes.")
        {
            projectOpt,
            outputOpt,
            namespaceOpt,
            classOpt,
            forceOpt
        };

        cmd.SetAction(async (parseResult, ct) =>
        {
            var project = parseResult.GetValue(projectOpt);
            var output = parseResult.GetValue(outputOpt);
            var @namespace = parseResult.GetValue(namespaceOpt);
            var className = parseResult.GetValue(classOpt) ?? "SliceApiClient";
            var force = parseResult.GetValue(forceOpt);

            try
            {
                await RunAsync(project, output, @namespace, className, force, ct).ConfigureAwait(false);
                return 0;
            }
            catch (CliException ex)
            {
                Console.Error.WriteLine(ex.Message);
                return 1;
            }
        });

        return cmd;
    }

    private static async Task RunAsync(
        FileInfo? project,
        FileInfo? output,
        string? @namespace,
        string className,
        bool force,
        CancellationToken ct)
    {
        var ctx = ProjectContextDiscovery.Discover(project);
        @namespace = CliValidation.RequireNamespace(
            string.IsNullOrWhiteSpace(@namespace) ? $"{ctx.RootNamespace}.Client" : @namespace,
            "Namespace");
        className = CliValidation.RequireClassName(className, "Class");

        var discovery = RouteCatalog.DiscoverDetailed(ctx);
        RouteCatalog.WriteAggregatedRouteNotice(discovery);
        var routes = discovery.Routes
            .Where(static route => route.Portability != RouteCatalog.PortabilityAspNetOnly)
            .ToArray();

        if (routes.Length == 0)
        {
            throw new CliException("No portable or partial Slice routes found for C# client generation.");
        }

        var outputFile = output?.FullName ?? Path.Combine(ctx.ProjectDirectory.FullName, $"{className}.g.cs");
        if (File.Exists(outputFile) && !force)
        {
            throw new CliException($"Output file already exists: {outputFile}. Pass --force to overwrite it.");
        }

        var outputDir = Path.GetDirectoryName(outputFile);
        if (!string.IsNullOrEmpty(outputDir))
        {
            Directory.CreateDirectory(outputDir);
        }

        var content = RenderClient(@namespace, className, routes);
        await File.WriteAllTextAsync(outputFile, content, ct).ConfigureAwait(false);
        Console.WriteLine($"Generated {outputFile}");
    }

    private static string RenderClient(string @namespace, string className, SliceRouteInfo[] routes)
    {
        var groups = routes
            .GroupBy(static route => route.Tag)
            .OrderBy(static group => group.Key, StringComparer.Ordinal)
            .ToArray();
        var groupNames = groups.ToDictionary(
            static group => group.Key,
            static group => ClientGenerationHelpers.ToPascalIdentifier(group.Key, "Default"),
            StringComparer.Ordinal);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using System.Net;");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"namespace {@namespace};");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"public partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly HttpClient _http;");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"    public {className}(HttpClient http)");
        sb.AppendLine("    {");
        sb.AppendLine("        _http = http ?? throw new ArgumentNullException(nameof(http));");
        foreach (var group in groups)
        {
            var groupName = groupNames[group.Key];
            sb.AppendLine(CultureInfo.InvariantCulture, $"        {groupName} = new {groupName}Client(_http, PrepareRequest);");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"    public {className}(HttpMessageHandler handler) : this(new HttpClient(handler)) {{ }}");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"    public static {className} Create(IHttpClientFactory factory, string? name = null)");
        sb.AppendLine(CultureInfo.InvariantCulture, $"        => new(factory.CreateClient(name ?? nameof({className})));");
        sb.AppendLine();
        sb.AppendLine("    partial void OnRequestPreparing(HttpRequestMessage request);");
        sb.AppendLine();
        sb.AppendLine("    private void PrepareRequest(HttpRequestMessage request) => OnRequestPreparing(request);");
        sb.AppendLine();
        foreach (var group in groups)
        {
            var groupName = groupNames[group.Key];
            sb.AppendLine(CultureInfo.InvariantCulture, $"    public {groupName}Client {groupName} {{ get; }}");
        }

        sb.AppendLine();
        sb.AppendLine("    private static string FormatRouteValue<T>(T value)");
        sb.AppendLine("        => Uri.EscapeDataString(Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty);");
        sb.AppendLine();
        sb.AppendLine("    private static readonly JsonSerializerOptions __ProblemJsonOptions = new() { PropertyNameCaseInsensitive = true };");
        sb.AppendLine();
        sb.AppendLine("    private static async Task __ThrowApiException(HttpResponseMessage response, string operation, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine("        SliceProblemDetails? problem = null;");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            var __body = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("            if (__body.Length > 0)");
        sb.AppendLine("            {");
        sb.AppendLine("                var __mediaType = response.Content.Headers.ContentType?.MediaType;");
        sb.AppendLine("                if (__mediaType is \"application/problem+json\" or \"application/json\")");
        sb.AppendLine("                {");
        sb.AppendLine("                    problem = JsonSerializer.Deserialize<SliceProblemDetails>(__body, __ProblemJsonOptions);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex) when (ex is not OperationCanceledException) { }");
        sb.AppendLine("        var __message = problem?.Title ?? $\"{operation} failed: {(int)response.StatusCode} {response.ReasonPhrase}\";");
        sb.AppendLine("        throw new SliceApiException(__message, response.StatusCode, problem);");
        sb.AppendLine("    }");

        foreach (var group in groups)
        {
            sb.AppendLine();
            EmitGroupClient(sb, className, groupNames[group.Key], group.OrderBy(static route => route.FeatureName, StringComparer.Ordinal));
        }

        sb.AppendLine();
        sb.AppendLine("    public sealed class SliceProblemDetails");
        sb.AppendLine("    {");
        sb.AppendLine("        public string? Type { get; set; }");
        sb.AppendLine("        public string? Title { get; set; }");
        sb.AppendLine("        public int? Status { get; set; }");
        sb.AppendLine("        public string? Detail { get; set; }");
        sb.AppendLine("        public IReadOnlyDictionary<string, string[]>? Errors { get; set; }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public class SliceApiException : HttpRequestException");
        sb.AppendLine("    {");
        sb.AppendLine("        public SliceProblemDetails? Problem { get; }");
        sb.AppendLine("        public IReadOnlyDictionary<string, string[]>? Errors => Problem?.Errors;");
        sb.AppendLine("        public SliceApiException(string message, HttpStatusCode statusCode, SliceProblemDetails? problem)");
        sb.AppendLine("            : base(message, null, statusCode)");
        sb.AppendLine("        {");
        sb.AppendLine("            Problem = problem;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitGroupClient(
        StringBuilder sb,
        string outerClassName,
        string groupName,
        IEnumerable<SliceRouteInfo> routes)
    {
        sb.AppendLine(CultureInfo.InvariantCulture, $"    public sealed class {groupName}Client");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly HttpClient _http;");
        sb.AppendLine("        private readonly Action<HttpRequestMessage> _prepareRequest;");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"        internal {groupName}Client(HttpClient http, Action<HttpRequestMessage> prepareRequest)");
        sb.AppendLine("        {");
        sb.AppendLine("            _http = http;");
        sb.AppendLine("            _prepareRequest = prepareRequest;");
        sb.AppendLine("        }");

        foreach (var route in routes)
        {
            sb.AppendLine();
            EmitRouteMethod(sb, outerClassName, route);
        }

        sb.AppendLine("    }");
    }

    private static void EmitRouteMethod(StringBuilder sb, string outerClassName, SliceRouteInfo route)
    {
        var responseType = ToClientType(route, ClientGenerationHelpers.UnwrapReturnType(route.ReturnType));
        var bodyParameter = ClientGenerationHelpers.FindBodyParameter(route);
        var routeParameters = ClientGenerationHelpers.FindRouteParameters(route);
        var queryParameters = ClientGenerationHelpers.FindQueryParameters(route, routeParameters, bodyParameter);
        var methodParameters = routeParameters
            .Concat(queryParameters)
            .Select(static parameter => $"{parameter.Type} {parameter.Name}")
            .ToList();

        if (bodyParameter is not null)
        {
            methodParameters.Add($"{ToClientType(route, bodyParameter.Type)} {bodyParameter.Name}");
        }

        methodParameters.Add("CancellationToken cancellationToken = default");
        var returnType = responseType == "void" ? "Task" : $"Task<{responseType}>";

        sb.AppendLine(CultureInfo.InvariantCulture, $"        public async {returnType} {route.FeatureName}Async({string.Join(", ", methodParameters)})");
        sb.AppendLine("        {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            var __url = {BuildPathExpression(outerClassName, route.Pattern, routeParameters)};");
        EmitQueryString(sb, outerClassName, queryParameters);

        if (route.Method == "GET" && bodyParameter is null && responseType != "void")
        {
            sb.AppendLine("            using var __message = new HttpRequestMessage(HttpMethod.Get, __url);");
            sb.AppendLine("            _prepareRequest(__message);");
            sb.AppendLine("            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);");
            sb.AppendLine("            if (!__response.IsSuccessStatusCode)");
            sb.AppendLine("            {");
            sb.AppendLine(CultureInfo.InvariantCulture, $"                await {outerClassName}.__ThrowApiException(__response, \"{route.FeatureName}\", cancellationToken).ConfigureAwait(false);");
            sb.AppendLine("            }");
            sb.AppendLine(CultureInfo.InvariantCulture, $"            return await __response.Content.ReadFromJsonAsync<{responseType}>(cancellationToken).ConfigureAwait(false)");
            sb.AppendLine(CultureInfo.InvariantCulture, $"                ?? throw new HttpRequestException(\"Route '{route.EndpointName}' returned an empty response body.\");");
            sb.AppendLine("        }");
            return;
        }

        sb.AppendLine(CultureInfo.InvariantCulture, $"            using var __message = new HttpRequestMessage(new HttpMethod(\"{route.Method}\"), __url);");
        if (bodyParameter is not null)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"            __message.Content = JsonContent.Create({bodyParameter.Name});");
        }

        sb.AppendLine("            _prepareRequest(__message);");
        sb.AppendLine("            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("            if (!__response.IsSuccessStatusCode)");
        sb.AppendLine("            {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"                await {outerClassName}.__ThrowApiException(__response, \"{route.FeatureName}\", cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("            }");

        if (responseType == "void")
        {
            sb.AppendLine("        }");
            return;
        }

        sb.AppendLine(CultureInfo.InvariantCulture, $"            return await __response.Content.ReadFromJsonAsync<{responseType}>(cancellationToken).ConfigureAwait(false)");
        sb.AppendLine(CultureInfo.InvariantCulture, $"                ?? throw new HttpRequestException(\"Route '{route.EndpointName}' returned an empty response body.\");");
        sb.AppendLine("        }");
    }

    private static void EmitQueryString(StringBuilder sb, string outerClassName, SliceRouteParameter[] queryParameters)
    {
        if (queryParameters.Length == 0)
        {
            return;
        }

        sb.AppendLine("            var __query = new List<string>();");
        foreach (var parameter in queryParameters)
        {
            if (ClientGenerationHelpers.NormalizeParameterType(parameter.Type).EndsWith("[]", StringComparison.Ordinal))
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"            if ({parameter.Name} is not null)");
                sb.AppendLine("            {");
                sb.AppendLine(CultureInfo.InvariantCulture, $"                foreach (var __value in {parameter.Name})");
                sb.AppendLine("                {");
                sb.AppendLine(CultureInfo.InvariantCulture, $"                    __query.Add(\"{parameter.Name}=\" + {outerClassName}.FormatRouteValue(__value));");
                sb.AppendLine("                }");
                sb.AppendLine("            }");
            }
            else
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"            __query.Add(\"{parameter.Name}=\" + {outerClassName}.FormatRouteValue({parameter.Name}));");
            }
        }

        sb.AppendLine("            __url += \"?\" + string.Join(\"&\", __query);");
    }

    private static string BuildPathExpression(string outerClassName, string pattern, SliceRouteParameter[] routeParameters)
    {
        var parameterNames = routeParameters.ToDictionary(
            static parameter => parameter.Name,
            static parameter => parameter.Name,
            StringComparer.OrdinalIgnoreCase);
        var sb = new StringBuilder("$\"");
        var index = 0;
        foreach (Match match in ClientGenerationHelpers.RouteParameterRegex().Matches(pattern))
        {
            sb.Append(EscapeInterpolatedText(pattern[index..match.Index]));
            var routeName = match.Groups["name"].Value;
            if (!parameterNames.TryGetValue(routeName, out var parameterName))
            {
                throw new CliException($"Route parameter '{{{routeName}}}' in '{pattern}' does not match a Handle parameter.");
            }

            sb.Append(CultureInfo.InvariantCulture, $"{{{outerClassName}.FormatRouteValue({parameterName})}}");
            index = match.Index + match.Length;
        }

        sb.Append(EscapeInterpolatedText(pattern[index..]));
        sb.Append('"');
        return sb.ToString();
    }

    private static string ToClientType(SliceRouteInfo route, string type)
    {
        var sb = new StringBuilder(type.Length);
        var index = 0;
        while (index < type.Length)
        {
            var ch = type[index];
            if (!IsIdentifierStart(ch))
            {
                sb.Append(ch);
                index++;
                continue;
            }

            var start = index;
            index++;
            while (index < type.Length && IsIdentifierPart(type[index]))
            {
                index++;
            }

            var identifier = type[start..index];
            if (identifier is "Request" or "Response" && !IsQualifiedTypeMember(type, start))
            {
                sb.Append(CultureInfo.InvariantCulture, $"global::{route.FeatureType}.{identifier}");
            }
            else
            {
                sb.Append(identifier);
            }
        }

        return sb.ToString();
    }

    private static bool IsQualifiedTypeMember(string type, int identifierStart)
    {
        for (var index = identifierStart - 1; index >= 0; index--)
        {
            if (char.IsWhiteSpace(type[index]))
            {
                continue;
            }

            return type[index] == '.';
        }

        return false;
    }

    private static string EscapeInterpolatedText(string value)
    {
        return value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("{", "{{", StringComparison.Ordinal)
            .Replace("}", "}}", StringComparison.Ordinal);
    }

    private static bool IsIdentifierStart(char value)
        => value == '_' || char.IsLetter(value);

    private static bool IsIdentifierPart(char value)
        => value == '_' || char.IsLetterOrDigit(value);

}
