// <auto-generated/>
#nullable enable
#pragma warning disable CS1591

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace SliceFx.BlazorSample.Client;

public partial class SliceApiClient
{
    private readonly HttpClient _http;

    public SliceApiClient(HttpClient http)
    {
        _http = http ?? throw new ArgumentNullException(nameof(http));
        Users = new UsersClient(_http, PrepareRequest);
    }

    public SliceApiClient(HttpMessageHandler handler) : this(new HttpClient(handler)) { }

    partial void OnRequestPreparing(HttpRequestMessage request);

    private void PrepareRequest(HttpRequestMessage request) => OnRequestPreparing(request);

    public UsersClient Users { get; }

    private static string FormatRouteValue<T>(T value)
        => Uri.EscapeDataString(Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty);

    private static readonly JsonSerializerOptions __ProblemJsonOptions = new() { PropertyNameCaseInsensitive = true };

    private static async Task __ThrowApiException(HttpResponseMessage response, string operation, CancellationToken cancellationToken)
    {
        SliceProblemDetails? problem = null;
        try
        {
            var __body = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
            if (__body.Length > 0)
            {
                var __mediaType = response.Content.Headers.ContentType?.MediaType;
                if (__mediaType is "application/problem+json" or "application/json")
                {
                    problem = JsonSerializer.Deserialize<SliceProblemDetails>(__body, __ProblemJsonOptions);
                }
            }
        }
        catch (Exception ex) when (ex is not OperationCanceledException) { }
        var __message = problem?.Title ?? $"{operation} failed: {(int)response.StatusCode} {response.ReasonPhrase}";
        throw new SliceApiException(__message, response.StatusCode, problem);
    }

    public sealed class UsersClient
    {
        private readonly HttpClient _http;
        private readonly Action<HttpRequestMessage> _prepareRequest;

        internal UsersClient(HttpClient http, Action<HttpRequestMessage> prepareRequest)
        {
            _http = http;
            _prepareRequest = prepareRequest;
        }

        public async Task<SliceFx.BlazorSample.Contracts.CreateUserResponse> CreateUserAsync(SliceFx.BlazorSample.Contracts.CreateUserRequest req, CancellationToken cancellationToken = default)
        {
            var __url = $"/users";
            using var __message = new HttpRequestMessage(new HttpMethod("POST"), __url);
            __message.Content = JsonContent.Create(req);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "CreateUser", cancellationToken).ConfigureAwait(false);
            }
            return await __response.Content.ReadFromJsonAsync<SliceFx.BlazorSample.Contracts.CreateUserResponse>(cancellationToken).ConfigureAwait(false)
                ?? throw new HttpRequestException("Route 'Users.CreateUser' returned an empty response body.");
        }

        public async Task<System.Collections.Generic.IReadOnlyList<SliceFx.BlazorSample.Contracts.UserSummary>> ListUsersAsync(CancellationToken cancellationToken = default)
        {
            var __url = $"/users";
            using var __message = new HttpRequestMessage(HttpMethod.Get, __url);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "ListUsers", cancellationToken).ConfigureAwait(false);
            }
            return await __response.Content.ReadFromJsonAsync<System.Collections.Generic.IReadOnlyList<SliceFx.BlazorSample.Contracts.UserSummary>>(cancellationToken).ConfigureAwait(false)
                ?? throw new HttpRequestException("Route 'Users.ListUsers' returned an empty response body.");
        }
    }

    public sealed class SliceProblemDetails
    {
        public string? Type { get; set; }
        public string? Title { get; set; }
        public int? Status { get; set; }
        public string? Detail { get; set; }
        public IReadOnlyDictionary<string, string[]>? Errors { get; set; }
    }

    public class SliceApiException : HttpRequestException
    {
        public SliceProblemDetails? Problem { get; }
        public IReadOnlyDictionary<string, string[]>? Errors => Problem?.Errors;
        public SliceApiException(string message, HttpStatusCode statusCode, SliceProblemDetails? problem)
            : base(message, null, statusCode)
        {
            Problem = problem;
        }
    }
}
